const nbaPlayerData = {
    "Atlanta Hawks": [
        { name: "Dominick Barlow", position: "Forward" },
        { name: "Bogdan Bogdanovic", position: "Shooting Guard" },
        { name: "Kobe Bufkin", position: "Guard" },
        { name: "Clint Capela", position: "Center" },
        { name: "Dyson Daniels", position: "Guard" },
        { name: "Mouhamed Gueye", position: "Forward" },
        { name: "De'Andre Hunter", position: "Small Forward" },
        { name: "Jalen Johnson", position: "Small Forward" },
        { name: "Vit Krejci", position: "Guard" },
        { name: "Seth Lundy", position: "Guard" },
        { name: "Garrison Mathews", position: "Shooting Guard" },
        { name: "Larry Nance Jr.", position: "Power Forward" },
        { name: "Onyeka Okongwu", position: "Power Forward" },
        { name: "Zaccharie Risacher", position: "Power Forward" },
        { name: "David Roddy", position: "Forward" },
        { name: "Keaton Wallace", position: "Guard" },
        { name: "Trae Young", position: "Point Guard" },
        { name: "Cody Zeller", position: "Center" }
    ],
   "Boston Celtics": [
        { name: "Jaylen Brown", position: "Shooting Guard" },
        { name: "JD Davison", position: "Shooting Guard" },
        { name: "Sam Hauser", position: "Small Forward" },
        { name: "Jrue Holiday", position: "Point Guard" },
        { name: "Al Horford", position: "Center" },
        { name: "Luke Kornet", position: "Center" },
        { name: "Drew Peterson", position: "Forward" },
        { name: "Kristaps Porzingis", position: "Center" },
        { name: "Payton Pritchard", position: "Point Guard" },
        { name: "Neemias Queta", position: "Center" },
        { name: "Baylor Scheierman", position: "Forward" },
        { name: "Jaden Springer", position: "Guard" },
        { name: "Jayson Tatum", position: "Small Forward" },
        { name: "Xavier Tillman", position: "Forward" },
        { name: "Jordan Walsh", position: "Guard" },
        { name: "Anton Watson", position: "Forward" },
        { name: "Derrick White", position: "Point Guard" }
    ],
    "Brooklyn Nets": [
        { name: "Bojan Bogdanovic", position: "Small Forward" },
        { name: "Nic Claxton", position: "Center" },
        { name: "Noah Clowney", position: "Forward" },
        { name: "Yongxi Cui", position: "Guard" },
        { name: "Dorian Finney-Smith", position: "Power Forward" },
        { name: "Cameron Johnson", position: "Small Forward" },
        { name: "Keon Johnson", position: "Guard" },
        { name: "Jaylen Martin", position: "Guard" },
        { name: "Tyrese Martin", position: "Guard" },
        { name: "Shake Milton", position: "Shooting Guard" },
        { name: "Dennis Schroder", position: "Point Guard" },
        { name: "Day'Ron Sharpe", position: "Center" },
        { name: "Ben Simmons", position: "Point Guard" },
        { name: "Cam Thomas", position: "Shooting Guard" },
        { name: "Trendon Watford", position: "Power Forward" },
        { name: "Dariq Whitehead", position: "Forward" },
        { name: "Ziaire Williams", position: "Forward" },
        { name: "Jalen Wilson", position: "Forward" }
    ],
    "Charlotte Hornets": [
        { name: "LaMelo Ball", position: "Point Guard" },
        { name: "Miles Bridges", position: "Small Forward" },
        { name: "Seth Curry", position: "Shooting Guard" },
        { name: "Moussa Diabate", position: "Forward" },
        { name: "Taj Gibson", position: "Forward" },
        { name: "Josh Green", position: "Shooting Guard" },
        { name: "DaQuan Jeffries", position: "Shooting Guard" },
        { name: "Tre Mann", position: "Point Guard" },
        { name: "Cody Martin", position: "Small Forward" },
        { name: "Vasilije Micic", position: "Guard" },
        { name: "Brandon Miller", position: "Forward" },
        { name: "Jared Rhoden", position: "Shooting Guard" },
        { name: "Nick Richards", position: "Center" },
        { name: "Tidjane Salaun", position: "Forward" },
        { name: "KJ Simpson", position: "Guard" },
        { name: "Nick Smith Jr.", position: "Guard" },
        { name: "Grant Williams", position: "Forward" },
        { name: "Mark Williams", position: "Center" }
    ],
    "Chicago Bulls": [
        { name: "Lonzo Ball", position: "Point Guard" },
        { name: "Matas Buzelis", position: "Forward" },
        { name: "Jevon Carter", position: "Point Guard" },
        { name: "Torrey Craig", position: "Small Forward" },
        { name: "Ayo Dosunmu", position: "Shooting Guard" },
        { name: "Chris Duarte", position: "Shooting Guard" },
        { name: "Josh Giddey", position: "Point Guard" },
        { name: "Talen Horton-Tucker", position: "Small Forward" },
        { name: "Zach LaVine", position: "Shooting Guard" },
        { name: "E.J. Liddell", position: "Power Forward" },
        { name: "Julian Phillips", position: "Small Forward" },
        { name: "Adama Sanogo", position: "Center" },
        { name: "Jalen Smith", position: "Power Forward" },
        { name: "DJ Steward", position: "Guard" },
        { name: "Dalen Terry", position: "Shooting Guard" },
        { name: "Nikola Vucevic", position: "Center" },
        { name: "Coby White", position: "Point Guard" },
        { name: "Patrick Williams", position: "Power Forward" }
    ],
    "Cleveland Cavaliers": [
        { name: "Jarrett Allen", position: "Center" },
        { name: "Emoni Bates", position: "Forward" },
        { name: "Darius Garland", position: "Point Guard" },
        { name: "Ty Jerome", position: "Point Guard" },
        { name: "Caris LeVert", position: "Shooting Guard" },
        { name: "Sam Merrill", position: "Shooting Guard" },
        { name: "Donovan Mitchell", position: "Shooting Guard" },
        { name: "Evan Mobley", position: "Power Forward" },
        { name: "Georges Niang", position: "Power Forward" },
        { name: "Isaac Okoro", position: "Small Forward" },
        { name: "Craig Porter Jr.", position: "Point Guard" },
        { name: "Max Strus", position: "Small Forward" },
        { name: "Tristan Thompson", position: "Center" },
        { name: "JT Thor", position: "Power Forward" },
        { name: "Luke Travers", position: "Small Forward" },
        { name: "Jaylon Tyson", position: "Forward" },
        { name: "Dean Wade", position: "Power Forward" }
    ],
    "Dallas Mavericks": [
        { name: "Spencer Dinwiddie", position: "Point Guard" },
        { name: "Luka Dončić", position: "Point Guard" },
        { name: "Kessler Edwards", position: "Forward" },
        { name: "Dante Exum", position: "Guard" },
        { name: "Daniel Gafford", position: "Center" },
        { name: "Jazian Gortman", position: "Guard" },
        { name: "Quentin Grimes", position: "Shooting Guard" },
        { name: "Jaden Hardy", position: "Shooting Guard" },
        { name: "Kyrie Irving", position: "Point Guard" },
        { name: "Maxi Kleber", position: "Power Forward" },
        { name: "Dereck Lively II", position: "Center" },
        { name: "Naji Marshall", position: "Small Forward" },
        { name: "Markieff Morris", position: "Power Forward" },
        { name: "Dwight Powell", position: "Center" },
        { name: "Olivier-Maxence Prosper", position: "Forward" },
        { name: "Klay Thompson", position: "Shooting Guard" },
        { name: "P.J. Washington", position: "Power Forward" },
        { name: "Brandon Williams", position: "Guard" }
    ],
    "Denver Nuggets": [
        { name: "Trey Alexander", position: "Guard" },
        { name: "Christian Braun", position: "Shooting Guard" },
        { name: "Vlatko Čančar", position: "Forward" },
        { name: "Aaron Gordon", position: "Power Forward" },
        { name: "PJ Hall", position: "Forward" },
        { name: "DaRon Holmes II", position: "Center" },
        { name: "Nikola Jokić", position: "Center" },
        { name: "Spencer Jones", position: "Forward" },
        { name: "DeAndre Jordan", position: "Center" },
        { name: "Jamal Murray", position: "Point Guard" },
        { name: "Zeke Nnaji", position: "Power Forward" },
        { name: "Jalen Pickett", position: "Point Guard" },
        { name: "Michael Porter Jr.", position: "Small Forward" },
        { name: "Dario Šarić", position: "Power Forward" },
        { name: "Julian Strawther", position: "Small Forward" },
        { name: "Hunter Tyson", position: "Forward" },
        { name: "Peyton Watson", position: "Small Forward" },
        { name: "Russell Westbrook", position: "Point Guard" }
    ],
    "Detroit Pistons": [
        { name: "Malik Beasley", position: "Shooting Guard" },
        { name: "Cade Cunningham", position: "Point Guard" },
        { name: "Jalen Duren", position: "Center" },
        { name: "Simone Fontecchio", position: "Small Forward" },
        { name: "Tim Hardaway Jr.", position: "Shooting Guard" },
        { name: "Tobias Harris", position: "Power Forward" },
        { name: "Ronald Holland II", position: "Forward" },
        { name: "Jaden Ivey", position: "Shooting Guard" },
        { name: "Daniss Jenkins", position: "Guard" },
        { name: "Bobi Klintman", position: "Forward" },
        { name: "Wendell Moore Jr.", position: "Small Forward" },
        { name: "Paul Reed", position: "Power Forward" },
        { name: "Marcus Sasser", position: "Guard" },
        { name: "Isaiah Stewart", position: "Power Forward" },
        { name: "Cole Swider", position: "Forward" },
        { name: "Ausar Thompson", position: "Small Forward" },
        { name: "Alondes Williams", position: "Guard" }
    ],
    "Golden State Warriors": [
        { name: "Kyle Anderson", position: "Forward" },
        { name: "Reece Beekman", position: "Guard" },
        { name: "Stephen Curry", position: "Point Guard" },
        { name: "Draymond Green", position: "Power Forward" },
        { name: "Buddy Hield", position: "Shooting Guard" },
        { name: "Trayce Jackson-Davis", position: "Forward" },
        { name: "Jonathan Kuminga", position: "Forward" },
        { name: "Kevon Looney", position: "Center" },
        { name: "De'Anthony Melton", position: "Shooting Guard" },
        { name: "Moses Moody", position: "Shooting Guard" },
        { name: "Gary Payton II", position: "Guard" },
        { name: "Brandin Podziemski", position: "Guard" },
        { name: "Quinten Post", position: "Forward" },
        { name: "Gui Santos", position: "Forward" },
        { name: "Pat Spencer", position: "Guard" },
        { name: "Lindy Waters III", position: "Forward" },
        { name: "Andrew Wiggins", position: "Small Forward" }
    ],
    "Houston Rockets": [
        { name: "Steven Adams", position: "Center" },
        { name: "Dillon Brooks", position: "Small Forward" },
        { name: "N'Faly Dante", position: "Forward" },
        { name: "Tari Eason", position: "Power Forward" },
        { name: "Jalen Green", position: "Shooting Guard" },
        { name: "Jeff Green", position: "Power Forward" },
        { name: "Aaron Holiday", position: "Point Guard" },
        { name: "Jock Landale", position: "Center" },
        { name: "Jack McVeigh", position: "Forward" },
        { name: "Alperen Sengun", position: "Center" },
        { name: "Reed Sheppard", position: "Guard" },
        { name: "Jabari Smith Jr.", position: "Power Forward" },
        { name: "Jae'Sean Tate", position: "Small Forward" },
        { name: "Amen Thompson", position: "Guard" },
        { name: "Fred VanVleet", position: "Point Guard" },
        { name: "Cam Whitmore", position: "Small Forward" },
        { name: "Nate Williams", position: "Forward" }
    ],
    "Indiana Pacers": [
        { name: "Enrique Freeman", position: "Forward" },
        { name: "Johnny Furphy", position: "Guard" },
        { name: "Tyrese Haliburton", position: "Point Guard" },
        { name: "Isaiah Jackson", position: "Center" },
        { name: "Quenton Jackson", position: "Guard" },
        { name: "James Johnson", position: "Forward" },
        { name: "Bennedict Mathurin", position: "Shooting Guard" },
        { name: "T.J. McConnell", position: "Point Guard" },
        { name: "Andrew Nembhard", position: "Point Guard" },
        { name: "Aaron Nesmith", position: "Forward" },
        { name: "Tristen Newton", position: "Guard" },
        { name: "Ben Sheppard", position: "Guard" },
        { name: "Pascal Siakam", position: "Forward" },
        { name: "Obi Toppin", position: "Forward" },
        { name: "Myles Turner", position: "Center" },
        { name: "Jarace Walker", position: "Forward" },
        { name: "James Wiseman", position: "Center" }
    ],
    "Los Angeles Clippers": [
        { name: "Mo Bamba", position: "Center" },
        { name: "Nicolas Batum", position: "Forward" },
        { name: "Kobe Brown", position: "Forward" },
        { name: "Cam Christie", position: "Guard" },
        { name: "Amir Coffey", position: "Guard" },
        { name: "Kris Dunn", position: "Guard" },
        { name: "Trentyn Flowers", position: "Forward" },
        { name: "James Harden", position: "Guard" },
        { name: "Bones Hyland", position: "Guard" },
        { name: "Kai Jones", position: "Center" },
        { name: "Derrick Jones Jr.", position: "Forward" },
        { name: "Kawhi Leonard", position: "Forward" },
        { name: "Terance Mann", position: "Guard" },
        { name: "Jordan Miller", position: "Forward" },
        { name: "Kevin Porter Jr.", position: "Guard" },
        { name: "Norman Powell", position: "Guard" },
        { name: "P.J. Tucker", position: "Forward" },
        { name: "Ivica Zubac", position: "Center" }
    ],
    "Los Angeles Lakers": [
        { name: "Max Christie", position: "Guard" },
        { name: "Anthony Davis", position: "Center" },
        { name: "Rui Hachimura", position: "Forward" },
        { name: "Jaxson Hayes", position: "Center" },
        { name: "Jalen Hood-Schifino", position: "Guard" },
        { name: "Bronny James", position: "Guard" },
        { name: "LeBron James", position: "Forward" },
        { name: "Dalton Knecht", position: "Forward" },
        { name: "Christian Koloko", position: "Center" },
        { name: "Maxwell Lewis", position: "Forward" },
        { name: "Quincy Olivari", position: "Guard" },
        { name: "Austin Reaves", position: "Guard" },
        { name: "Cam Reddish", position: "Forward" },
        { name: "D'Angelo Russell", position: "Guard" },
        { name: "Armel Traore", position: "Forward" },
        { name: "Jarred Vanderbilt", position: "Forward" },
        { name: "Gabe Vincent", position: "Guard" },
        { name: "Christian Wood", position: "Center" }
    ],
    "Memphis Grizzlies": [
        { name: "Santi Aldama", position: "Forward" },
        { name: "Desmond Bane", position: "Guard" },
        { name: "Colin Castleton", position: "Center" },
        { name: "Brandon Clarke", position: "Forward" },
        { name: "Zach Edey", position: "Center" },
        { name: "Jay Huff", position: "Center" },
        { name: "GG Jackson II", position: "Forward" },
        { name: "Jaren Jackson Jr.", position: "Forward" },
        { name: "Yuki Kawamura", position: "Guard" },
        { name: "Luke Kennard", position: "Guard" },
        { name: "John Konchar", position: "Guard" },
        { name: "Jake LaRavia", position: "Forward" },
        { name: "Ja Morant", position: "Guard" },
        { name: "Scotty Pippen Jr.", position: "Guard" },
        { name: "Marcus Smart", position: "Guard" },
        { name: "Cam Spencer", position: "Guard" },
        { name: "Jaylen Wells", position: "Forward" },
        { name: "Vince Williams Jr.", position: "Forward" }
    ],
    "Miami Heat": [
        { name: "Bam Adebayo", position: "Center" },
        { name: "Thomas Bryant", position: "Center" },
        { name: "Alec Burks", position: "Shooting Guard" },
        { name: "Jimmy Butler", position: "Small Forward" },
        { name: "Josh Christopher", position: "Shooting Guard" },
        { name: "Tyler Herro", position: "Point Guard" },
        { name: "Haywood Highsmith", position: "Forward" },
        { name: "Jaime Jaquez Jr.", position: "Guard" },
        { name: "Keshad Johnson", position: "Forward" },
        { name: "Nikola Jovic", position: "Forward" },
        { name: "Pelle Larsson", position: "Guard" },
        { name: "Kevin Love", position: "Power Forward" },
        { name: "Josh Richardson", position: "Shooting Guard" },
        { name: "Duncan Robinson", position: "Forward" },
        { name: "Terry Rozier", position: "Shooting Guard" },
        { name: "Dru Smith", position: "Guard" },
        { name: "Kel'el Ware", position: "Center" }
    ],
    "Milwaukee Bucks": [
        { name: "Giannis Antetokounmpo", position: "Power Forward" },
        { name: "MarJon Beauchamp", position: "Forward" },
        { name: "Pat Connaughton", position: "Shooting Guard" },
        { name: "AJ Green", position: "Guard" },
        { name: "Andre Jackson Jr.", position: "Guard" },
        { name: "AJ Johnson", position: "Guard" },
        { name: "Damian Lillard", position: "Point Guard" },
        { name: "Chris Livingston", position: "Forward" },
        { name: "Brook Lopez", position: "Center" },
        { name: "Khris Middleton", position: "Small Forward" },
        { name: "Bobby Portis", position: "Forward" },
        { name: "Taurean Prince", position: "Power Forward" },
        { name: "Liam Robbins", position: "Center" },
        { name: "Ryan Rollins", position: "Guard" },
        { name: "Tyler Smith", position: "Forward" },
        { name: "Gary Trent Jr.", position: "Shooting Guard" },
        { name: "Stanley Umude", position: "Forward" },
        { name: "Delon Wright", position: "Shooting Guard" }
    ],
    "Minnesota Timberwolves": [
        { name: "Nickeil Alexander-Walker", position: "Shooting Guard" },
        { name: "Jaylen Clark", position: "Guard" },
        { name: "Mike Conley", position: "Point Guard" },
        { name: "Donte DiVincenzo", position: "Shooting Guard" },
        { name: "Rob Dillingham", position: "Guard" },
        { name: "PJ Dozier", position: "Guard" },
        { name: "Anthony Edwards", position: "Shooting Guard" },
        { name: "Jesse Edwards", position: "Center" },
        { name: "Luka Garza", position: "Center" },
        { name: "Rudy Gobert", position: "Center" },
        { name: "Joe Ingles", position: "Shooting Guard" },
        { name: "Jaden McDaniels", position: "Power Forward" },
        { name: "Leonard Miller", position: "Forward" },
        { name: "Josh Minott", position: "Forward" },
        { name: "Daishen Nix", position: "Shooting Guard" },
        { name: "Julius Randle", position: "Power Forward" },
        { name: "Naz Reid", position: "Center" },
        { name: "Terrence Shannon Jr.", position: "Guard" }
    ],
    "New Orleans Pelicans": [
        { name: "Jose Alvarado", position: "Point Guard" },
        { name: "Brandon Boston Jr.", position: "Shooting Guard" },
        { name: "Jamal Cain", position: "Forward" },
        { name: "Javonte Green", position: "Guard" },
        { name: "Jordan Hawkins", position: "Guard" },
        { name: "Brandon Ingram", position: "Small Forward" },
        { name: "Trey Jemison III", position: "Center" },
        { name: "Herbert Jones", position: "Small Forward" },
        { name: "Karlo Matkovic", position: "Center" },
        { name: "CJ McCollum", position: "Shooting Guard" },
        { name: "Yves Missi", position: "Center" },
        { name: "Trey Murphy III", position: "Shooting Guard" },
        { name: "Dejounte Murray", position: "Shooting Guard" },
        { name: "Jaylen Nowell", position: "Guard" },
        { name: "Antonio Reeves", position: "Guard" },
        { name: "Jeremiah Robinson-Earl", position: "Forward" },
        { name: "Daniel Theis", position: "Center" },
        { name: "Zion Williamson", position: "Power Forward" }
    ],
    "New York Knicks": [
        { name: "Precious Achiuwa", position: "Power Forward" },
        { name: "OG Anunoby", position: "Small Forward" },
        { name: "Mikal Bridges", position: "Small Forward" },
        { name: "Jalen Brunson", position: "Point Guard" },
        { name: "Boo Buie", position: "Guard" },
        { name: "Pacome Dadiet", position: "Guard" },
        { name: "Josh Hart", position: "Shooting Guard" },
        { name: "Ariel Hukporti", position: "Center" },
        { name: "Tyler Kolek", position: "Guard" },
        { name: "Miles McBride", position: "Point Guard" },
        { name: "Kevin McCullar Jr.", position: "Forward" },
        { name: "Cameron Payne", position: "Point Guard" },
        { name: "Mitchell Robinson", position: "Center" },
        { name: "Matt Ryan", position: "Forward" },
        { name: "Jericho Sims", position: "Center" },
        { name: "Jacob Toppin", position: "Forward" },
        { name: "Karl-Anthony Towns", position: "Center" }
    ],
    "Oklahoma City Thunder": [
        { name: "Branden Carlson", position: "Center" },
        { name: "Alex Caruso", position: "Shooting Guard" },
        { name: "Ousmane Dieng", position: "Forward" },
        { name: "Luguentz Dort", position: "Guard" },
        { name: "Alex Ducas", position: "Guard" },
        { name: "Adam Flagler", position: "Forward" },
        { name: "Shai Gilgeous-Alexander", position: "Point Guard" },
        { name: "Isaiah Hartenstein", position: "Center" },
        { name: "Chet Holmgren", position: "Power Forward" },
        { name: "Isaiah Joe", position: "Shooting Guard" },
        { name: "Dillon Jones", position: "Forward" },
        { name: "Malevy Leons", position: "Forward" },
        { name: "Ajay Mitchell", position: "Guard" },
        { name: "Nikola Topic", position: "Guard" },
        { name: "Cason Wallace", position: "Guard" },
        { name: "Aaron Wiggins", position: "Shooting Guard" },
        { name: "Jalen Williams", position: "Forward" },
        { name: "Jaylin Williams", position: "Forward" },
        { name: "Kenrich Williams", position: "Small Forward" }
    ],
    "Orlando Magic": [
        { name: "Cole Anthony", position: "Point Guard" },
        { name: "Paolo Banchero", position: "Power Forward" },
        { name: "Goga Bitadze", position: "Center" },
        { name: "Anthony Black", position: "Guard" },
        { name: "Kentavious Caldwell-Pope", position: "Shooting Guard" },
        { name: "Wendell Carter Jr.", position: "Center" },
        { name: "Tristan da Silva", position: "Forward" },
        { name: "Gary Harris", position: "Shooting Guard" },
        { name: "Caleb Houstan", position: "Guard" },
        { name: "Jett Howard", position: "Guard" },
        { name: "Jonathan Isaac", position: "Power Forward" },
        { name: "Cory Joseph", position: "Point Guard" },
        { name: "Mac McClung", position: "Guard" },
        { name: "Trevelin Queen", position: "Shooting Guard" },
        { name: "Jalen Suggs", position: "Shooting Guard" },
        { name: "Franz Wagner", position: "Small Forward" },
        { name: "Moritz Wagner", position: "Center" }
    ],
    "Philadelphia 76ers": [
        { name: "Adem Bona", position: "Center" },
        { name: "Ricky Council IV", position: "Guard" },
        { name: "Jeff Dowtin Jr.", position: "Guard" },
        { name: "Andre Drummond", position: "Center" },
        { name: "Justin Edwards", position: "Forward" },
        { name: "Joel Embiid", position: "Center" },
        { name: "Paul George", position: "Forward" },
        { name: "Eric Gordon", position: "Shooting Guard" },
        { name: "Reggie Jackson", position: "Point Guard" },
        { name: "Kyle Lowry", position: "Point Guard" },
        { name: "Caleb Martin", position: "Small Forward" },
        { name: "KJ Martin", position: "Forward" },
        { name: "Tyrese Maxey", position: "Point Guard" },
        { name: "Jared McCain", position: "Guard" },
        { name: "Kelly Oubre Jr.", position: "Shooting Guard" },
        { name: "Lester Quinones", position: "Guard" },
        { name: "Guerschon Yabusele", position: "Forward" }
    ],
    "Phoenix Suns": [
        { name: "Grayson Allen", position: "Shooting Guard" },
        { name: "Bradley Beal", position: "Shooting Guard" },
        { name: "Bol Bol", position: "Center" },
        { name: "Devin Booker", position: "Shooting Guard" },
        { name: "Jalen Bridges", position: "Forward" },
        { name: "Ryan Dunn", position: "Forward" },
        { name: "Kevin Durant", position: "Power Forward" },
        { name: "Collin Gillespie", position: "Guard" },
        { name: "Oso Ighodaro", position: "Center" },
        { name: "Tyus Jones", position: "Point Guard" },
        { name: "Damion Lee", position: "Shooting Guard" },
        { name: "Monte Morris", position: "Point Guard" },
        { name: "Jusuf Nurkic", position: "Center" },
        { name: "Royce O'Neale", position: "Power Forward" },
        { name: "Josh Okogie", position: "Small Forward" },
        { name: "Mason Plumlee", position: "Center" },
        { name: "TyTy Washington Jr.", position: "Guard" }
    ],
    "Portland Trail Blazers": [
        { name: "Deni Avdija", position: "Small Forward" },
        { name: "Deandre Ayton", position: "Center" },
        { name: "Dalano Banton", position: "Guard" },
        { name: "Toumani Camara", position: "Forward" },
        { name: "Donovan Clingan", position: "Center" },
        { name: "Jerami Grant", position: "Small Forward" },
        { name: "Scoot Henderson", position: "Guard" },
        { name: "Bryce McGowens", position: "Guard" },
        { name: "Justin Minaya", position: "Forward" },
        { name: "Taze Moore", position: "Guard" },
        { name: "Kris Murray", position: "Forward" },
        { name: "Duop Reath", position: "Center" },
        { name: "Rayan Rupert", position: "Guard" },
        { name: "Shaedon Sharpe", position: "Shooting Guard" },
        { name: "Anfernee Simons", position: "Shooting Guard" },
        { name: "Matisse Thybulle", position: "Shooting Guard" },
        { name: "Jabari Walker", position: "Forward" },
        { name: "Robert Williams III", position: "Center" }
    ],
    "Sacramento Kings": [
        { name: "Isaiah Crawford", position: "Forward" },
        { name: "DeMar DeRozan", position: "Small Forward" },
        { name: "Keon Ellis", position: "Guard" },
        { name: "De'Aaron Fox", position: "Point Guard" },
        { name: "Kevin Huerter", position: "Shooting Guard" },
        { name: "Colby Jones", position: "Guard" },
        { name: "Isaac Jones", position: "Center" },
        { name: "Mason Jones", position: "Guard" },
        { name: "Alex Len", position: "Center" },
        { name: "Trey Lyles", position: "Power Forward" },
        { name: "Doug McDermott", position: "Small Forward" },
        { name: "Jordan McLaughlin", position: "Point Guard" },
        { name: "Malik Monk", position: "Shooting Guard" },
        { name: "Keegan Murray", position: "Small Forward" },
        { name: "Domantas Sabonis", position: "Power Forward" }
    ],
    "San Antonio Spurs": [
        { name: "Harrison Barnes", position: "Small Forward" },
        { name: "Charles Bassey", position: "Center" },
        { name: "Malaki Branham", position: "Guard" },
        { name: "Stephon Castle", position: "Guard" },
        { name: "Julian Champagnie", position: "Forward" },
        { name: "Sidy Cissoko", position: "Forward" },
        { name: "Zach Collins", position: "Power Forward" },
        { name: "David Duke Jr.", position: "Guard" },
        { name: "Harrison Ingram", position: "Forward" },
        { name: "Keldon Johnson", position: "Small Forward" },
        { name: "Tre Jones", position: "Point Guard" },
        { name: "Sandro Mamukelashvili", position: "Power Forward" },
        { name: "Riley Minix", position: "Forward" },
        { name: "Chris Paul", position: "Point Guard" },
        { name: "Jeremy Sochan", position: "Forward" },
        { name: "Devin Vassell", position: "Shooting Guard" },
        { name: "Victor Wembanyama", position: "Center" },
        { name: "Blake Wesley", position: "Shooting Guard" }
    ],
    "Toronto Raptors": [
        { name: "Ochai Agbaji", position: "Guard" },
        { name: "Scottie Barnes", position: "Small Forward" },
        { name: "RJ Barrett", position: "Shooting Guard" },
        { name: "Jamison Battle", position: "Forward" },
        { name: "Chris Boucher", position: "Power Forward" },
        { name: "Bruce Brown", position: "Small Forward" },
        { name: "D.J. Carton", position: "Guard" },
        { name: "Ulrich Chomche", position: "Center" },
        { name: "Gradey Dick", position: "Guard" },
        { name: "Bruno Fernando", position: "Forward" },
        { name: "Davion Mitchell", position: "Point Guard" },
        { name: "Jonathan Mogbo", position: "Forward" },
        { name: "Kelly Olynyk", position: "Power Forward" },
        { name: "Jakob Poeltl", position: "Center" },
        { name: "Immanuel Quickley", position: "Shooting Guard" },
        { name: "Jamal Shead", position: "Guard" },
        { name: "Garrett Temple", position: "Small Forward" },
        { name: "Ja'Kobe Walter", position: "Guard" }
    ],
    "Utah Jazz": [
        { name: "Jordan Clarkson", position: "Point Guard" },
        { name: "Isaiah Collier", position: "Guard" },
        { name: "John Collins", position: "Power Forward" },
        { name: "Drew Eubanks", position: "Power Forward" },
        { name: "Kyle Filipowski", position: "Forward" },
        { name: "Keyonte George", position: "Guard" },
        { name: "Taylor Hendricks", position: "Forward" },
        { name: "Johnny Juzang", position: "Guard" },
        { name: "Walker Kessler", position: "Center" },
        { name: "Lauri Markkanen", position: "Power Forward" },
        { name: "Patty Mills", position: "Point Guard" },
        { name: "Svi Mykhailiuk", position: "Shooting Guard" },
        { name: "Micah Potter", position: "Center" },
        { name: "Jason Preston", position: "Guard" },
        { name: "Brice Sensabaugh", position: "Forward" },
        { name: "Collin Sexton", position: "Point Guard" },
        { name: "Oscar Tshiebwe", position: "Center" },
        { name: "Cody Williams", position: "Forward" }
    ],
    "Washington Wizards": [
        { name: "Marvin Bagley III", position: "Power Forward" },
        { name: "Patrick Baldwin Jr.", position: "Forward" },
        { name: "Saddiq Bey", position: "Small Forward" },
        { name: "Malcolm Brogdon", position: "Point Guard" },
        { name: "Jared Butler", position: "Shooting Guard" },
        { name: "Carlton Carrington", position: "Guard" },
        { name: "Justin Champagnie", position: "Small Forward" },
        { name: "Bilal Coulibaly", position: "Shooting Guard" },
        { name: "Johnny Davis", position: "Guard" },
        { name: "Kyshawn George", position: "Forward" },
        { name: "Anthony Gill", position: "Power Forward" },
        { name: "Richaun Holmes", position: "Forward" },
        { name: "Corey Kispert", position: "Small Forward" },
        { name: "Kyle Kuzma", position: "Small Forward" },
        { name: "Jordan Poole", position: "Shooting Guard" },
        { name: "Alexandre Sarr", position: "Power Forward" },
        { name: "Jonas Valančiūnas", position: "Center" },
        { name: "Tristan Vukcevic", position: "Power Forward" }
    ]
};