const nflPlayerData = {
    "Arizona Cardinals": [
        { name: "Tua Tagovailoa", position: "Quarterback" },
        { name: "Skylar Thompson", position: "Quarterback" },
        { name: "De'Von Achane", position: "Running Back" },
        { name: "Raheem Mostert", position: "Running Back" },
        { name: "Jeff Wilson Jr.", position: "Running Back" },
        { name: "Jaylen Wright", position: "Running Back" },
        { name: "Alec Ingold", position: "Fullback" },
        { name: "Odell Beckham Jr.", position: "Wide Receiver" },
        { name: "River Cracraft", position: "Wide Receiver" },
        { name: "Dee Eskridge", position: "Wide Receiver" },
        { name: "Tyreek Hill", position: "Wide Receiver" },
        { name: "Jaylen Waddle", position: "Wide Receiver" },
        { name: "Malik Washington", position: "Wide Receiver" },
        { name: "Julian Hill", position: "Tight End" },
        { name: "Jonnu Smith", position: "Tight End" },
        { name: "Durham Smythe", position: "Tight End" },
        { name: "Jack Stoll", position: "Tight End" },
        { name: "Andrew Meyer", position: "Center" },
        { name: "Aaron Brewer", position: "Guard" },
        { name: "Lester Cotton", position: "Guard" },
        { name: "Robert Jones", position: "Guard" },
        { name: "Terron Armstead", position: "Offensive Tackle" },
        { name: "Jackson Carman", position: "Offensive Tackle" },
        { name: "Liam Eichenberg", position: "Offensive Tackle" },
        { name: "Kendall Lamm", position: "Offensive Tackle" },
        { name: "Patrick Paul", position: "Offensive Tackle" },
        { name: "Calais Campbell", position: "Defensive Tackle" },
        { name: "Neil Farrell", position: "Defensive Tackle" },
        { name: "Da'Shawn Hand", position: "Defensive Tackle" },
        { name: "Benito Jones", position: "Defensive Tackle" },
        { name: "Zach Sieler", position: "Defensive Tackle" },
        { name: "Quinton Bell", position: "Linebacker" },
        { name: "Tyus Bowser", position: "Linebacker" },
        { name: "Jordyn Brooks", position: "Linebacker" },
        { name: "Tyrel Dodson", position: "Linebacker" },
        { name: "Mohamed Kamara", position: "Linebacker" },
        { name: "Emmanuel Ogbah", position: "Linebacker" },
        { name: "Duke Riley", position: "Linebacker" },
        { name: "Chop Robinson", position: "Linebacker" },
        { name: "Channing Tindall", position: "Linebacker" },
        { name: "Anthony Walker Jr.", position: "Linebacker" },
        { name: "Ethan Bonner", position: "Cornerback" },
        { name: "Storm Duck", position: "Cornerback" },
        { name: "Kendall Fuller", position: "Cornerback" },
        { name: "Kader Kohou", position: "Cornerback" },
        { name: "Siran Neal", position: "Cornerback" },
        { name: "Jalen Ramsey", position: "Cornerback" },
        { name: "Cam Smith", position: "Cornerback" },
        { name: "Elijah Campbell", position: "Safety" },
        { name: "Jevon Holland", position: "Safety" },
        { name: "Marcus Maye", position: "Safety" },
        { name: "Jordan Poyer", position: "Safety" }
    ],
    "Buffalo Bills": [
        { name: "Josh Allen", position: "Quarterback" },
        { name: "Mitchell Trubisky", position: "Quarterback" },
        { name: "James Cook", position: "Running Back" },
        { name: "Ray Davis", position: "Running Back" },
        { name: "Ty Johnson", position: "Running Back" },
        { name: "Reggie Gilliam", position: "Fullback" },
        { name: "Keon Coleman", position: "Wide Receiver" },
        { name: "Amari Cooper", position: "Wide Receiver" },
        { name: "Mack Hollins", position: "Wide Receiver" },
        { name: "Curtis Samuel", position: "Wide Receiver" },
        { name: "Khalil Shakir", position: "Wide Receiver" },
        { name: "Jalen Virgil", position: "Wide Receiver" },
        { name: "Zach Davidson", position: "Tight End" },
        { name: "Dalton Kincaid", position: "Tight End" },
        { name: "Dawson Knox", position: "Tight End" },
        { name: "Quintin Morris", position: "Tight End" },
        { name: "Will Clapp", position: "Center" },
        { name: "Sedrick Van Pran-Granger", position: "Center" },
        { name: "David Edwards", position: "Guard" },
        { name: "Connor McGovern", position: "Guard" },
        { name: "O'Cyrus Torrence", position: "Guard" },
        { name: "Alec Anderson", position: "Offensive Tackle" },
        { name: "Spencer Brown", position: "Offensive Tackle" },
        { name: "Dion Dawkins", position: "Offensive Tackle" },
        { name: "Richard Gouraige", position: "Offensive Tackle" },
        { name: "Ryan Van Demark", position: "Offensive Tackle" },
        { name: "AJ Epenesa", position: "Defensive End" },
        { name: "Greg Rousseau", position: "Defensive End" },
        { name: "Javon Solomon", position: "Defensive End" },
        { name: "Casey Toohill", position: "Defensive End" },
        { name: "Quinton Jefferson", position: "Defensive Tackle" },
        { name: "Austin Johnson", position: "Defensive Tackle" },
        { name: "DaQuan Jones", position: "Defensive Tackle" },
        { name: "Ed Oliver", position: "Defensive Tackle" },
        { name: "Jordan Phillips", position: "Defensive Tackle" },
        { name: "Joe Andreessen", position: "Linebacker" },
        { name: "Terrel Bernard", position: "Linebacker" },
        { name: "Von Miller", position: "Linebacker" },
        { name: "Nicholas Morrow", position: "Linebacker" },
        { name: "Edefuan Ulofoshio", position: "Linebacker" },
        { name: "Dorian Williams", position: "Linebacker" },
        { name: "Christian Benford", position: "Cornerback" },
        { name: "Brandon Codrington", position: "Cornerback" },
        { name: "Rasul Douglas", position: "Cornerback" },
        { name: "Kaiir Elam", position: "Cornerback" },
        { name: "Ja'Marcus Ingram", position: "Cornerback" },
        { name: "Taron Johnson", position: "Cornerback" },
        { name: "Cam Lewis", position: "Cornerback" },
        { name: "Cole Bishop", position: "Safety" },
        { name: "Damar Hamlin", position: "Safety" },
        { name: "Taylor Rapp", position: "Safety" }
    ],
    "Miami Dolphins": [
        { name: "Jacoby Brissett", position: "Quarterback" },
    { name: "Drake Maye", position: "Quarterback" },
    { name: "Joe Milton III", position: "Quarterback" },
    { name: "Antonio Gibson", position: "Running Back" },
    { name: "JaMycal Hasty", position: "Running Back" },
    { name: "Rhamondre Stevenson", position: "Running Back" },
    { name: "Javon Baker", position: "Wide Receiver" },
    { name: "Kendrick Bourne", position: "Wide Receiver" },
    { name: "Kayshon Boutte", position: "Wide Receiver" },
    { name: "DeMario Douglas", position: "Wide Receiver" },
    { name: "Jalen Hurd", position: "Wide Receiver" },
    { name: "K.J. Osborn", position: "Wide Receiver" },
    { name: "Ja'Lynn Polk", position: "Wide Receiver" },
    { name: "Jaheim Bell", position: "Tight End" },
    { name: "Hunter Henry", position: "Tight End" },
    { name: "Austin Hooper", position: "Tight End" },
    { name: "Ben Brown", position: "Center" },
    { name: "Lecitus Smith", position: "Guard" },
    { name: "Michael Jordan", position: "Guard" },
    { name: "Layden Robinson", position: "Guard" },
    { name: "Tyrese Robinson", position: "Guard" },
    { name: "Sidy Sow", position: "Guard" },
    { name: "Demontrey Jacobs", position: "Offensive Tackle" },
    { name: "Vederian Lowe", position: "Offensive Tackle" },
    { name: "Mike Onwenu", position: "Offensive Tackle" },
    { name: "Keion White", position: "Defensive End" },
    { name: "Deatrich Wise Jr.", position: "Defensive End" },
    { name: "Christian Barmore", position: "Defensive Tackle" },
    { name: "Daniel Ekuale", position: "Defensive Tackle" },
    { name: "Davon Godchaux", position: "Defensive Tackle" },
    { name: "Eric Johnson II", position: "Defensive Tackle" },
    { name: "Jeremiah Pharms Jr.", position: "Defensive Tackle" },
    { name: "Jaquelin Roy", position: "Defensive Tackle" },
    { name: "Keshawn Banks", position: "Linebacker" },
    { name: "Christian Elliss", position: "Linebacker" },
    { name: "Joe Giles-Harris", position: "Linebacker" },
    { name: "Anfernee Jennings", position: "Linebacker" },
    { name: "Titus Leo", position: "Linebacker" },
    { name: "Yannick Ngakoue", position: "Linebacker" },
    { name: "Sione Takitaki", position: "Linebacker" },
    { name: "Jahlani Tavai", position: "Linebacker" },
    { name: "Alex Austin", position: "Cornerback" },
    { name: "Isaiah Bolden", position: "Cornerback" },
    { name: "Marcellas Dial Jr.", position: "Cornerback" },
    { name: "Christian Gonzalez", position: "Cornerback" },
    { name: "Jonathan Jones", position: "Cornerback" },
    { name: "Marcus Jones", position: "Cornerback" },
    { name: "Kyle Dugger", position: "Safety" },
    { name: "Jaylinn Hawkins", position: "Safety" },
    { name: "Marte Mapu", position: "Safety" },
    { name: "Jabrill Peppers", position: "Safety" },
    { name: "Dell Pettus", position: "Safety" },
    { name: "Brenden Schooler", position: "Safety" }
    ],
    "New England Patriots": [
        { name: "Jacoby Brissett", position: "Quarterback" },
        { name: "Drake Maye", position: "Quarterback" },
        { name: "Joe Milton III", position: "Quarterback" },
        { name: "Antonio Gibson", position: "Running Back" },
        { name: "JaMycal Hasty", position: "Running Back" },
        { name: "Rhamondre Stevenson", position: "Running Back" },
        { name: "Javon Baker", position: "Wide Receiver" },
        { name: "Kendrick Bourne", position: "Wide Receiver" },
        { name: "Kayshon Boutte", position: "Wide Receiver" },
        { name: "DeMario Douglas", position: "Wide Receiver" },
        { name: "Jalen Hurd", position: "Wide Receiver" },
        { name: "K.J. Osborn", position: "Wide Receiver" },
        { name: "Ja'Lynn Polk", position: "Wide Receiver" },
        { name: "Jaheim Bell", position: "Tight End" },
        { name: "Hunter Henry", position: "Tight End" },
        { name: "Austin Hooper", position: "Tight End" },
        { name: "Ben Brown", position: "Center" },
        { name: "Lecitus Smith", position: "Center" },
        { name: "Michael Jordan", position: "Guard" },
        { name: "Layden Robinson", position: "Guard" },
        { name: "Tyrese Robinson", position: "Guard" },
        { name: "Sidy Sow", position: "Guard" },
        { name: "Demontrey Jacobs", position: "Offensive Tackle" },
        { name: "Vederian Lowe", position: "Offensive Tackle" },
        { name: "Mike Onwenu", position: "Offensive Tackle" },
        { name: "Keion White", position: "Defensive End" },
        { name: "Deatrich Wise Jr.", position: "Defensive End" },
        { name: "Christian Barmore", position: "Defensive Tackle" },
        { name: "Daniel Ekuale", position: "Defensive Tackle" },
        { name: "Davon Godchaux", position: "Defensive Tackle" },
        { name: "Eric Johnson II", position: "Defensive Tackle" },
        { name: "Jeremiah Pharms Jr.", position: "Defensive Tackle" },
        { name: "Jaquelin Roy", position: "Defensive Tackle" },
        { name: "Keshawn Banks", position: "Linebacker" },
        { name: "Christian Elliss", position: "Linebacker" },
        { name: "Joe Giles-Harris", position: "Linebacker" },
        { name: "Anfernee Jennings", position: "Linebacker" },
        { name: "Titus Leo", position: "Linebacker" },
        { name: "Yannick Ngakoue", position: "Linebacker" },
        { name: "Sione Takitaki", position: "Linebacker" },
        { name: "Jahlani Tavai", position: "Linebacker" },
        { name: "Alex Austin", position: "Cornerback" },
        { name: "Isaiah Bolden", position: "Cornerback" },
        { name: "Marcellas Dial Jr.", position: "Cornerback" },
        { name: "Christian Gonzalez", position: "Cornerback" },
        { name: "Jonathan Jones", position: "Cornerback" },
        { name: "Marcus Jones", position: "Cornerback" },
        { name: "Kyle Dugger", position: "Safety" },
        { name: "Jaylinn Hawkins", position: "Safety" },
        { name: "Marte Mapu", position: "Safety" },
        { name: "Jabrill Peppers", position: "Safety" },
        { name: "Dell Pettus", position: "Safety" },
        { name: "Brenden Schooler", position: "Safety" }
    ],
    "New York Jets": [
        { name: "Aaron Rodgers", position: "Quarterback" },
    { name: "Tyrod Taylor", position: "Quarterback" },
    { name: "Israel Abanikanda", position: "Running Back" },
    { name: "Braelon Allen", position: "Running Back" },
    { name: "Isaiah Davis", position: "Running Back" },
    { name: "Breece Hall", position: "Running Back" },
    { name: "Davante Adams", position: "Wide Receiver" },
    { name: "Irvin Charles", position: "Wide Receiver" },
    { name: "Malachi Corley", position: "Wide Receiver" },
    { name: "Xavier Gipson", position: "Wide Receiver" },
    { name: "Garrett Wilson", position: "Wide Receiver" },
    { name: "Tyler Conklin", position: "Tight End" },
    { name: "Jeremy Ruckert", position: "Tight End" },
    { name: "Kenny Yeboah", position: "Tight End" },
    { name: "Jake Hanson", position: "Center" },
    { name: "Connor McGovern", position: "Center" },
    { name: "Joe Tippmann", position: "Center" },
    { name: "John Simpson", position: "Guard" },
    { name: "Alijah Vera-Tucker", position: "Guard" },
    { name: "Olu Fashanu", position: "Offensive Tackle" },
    { name: "Max Mitchell", position: "Offensive Tackle" },
    { name: "Morgan Moses", position: "Offensive Tackle" },
    { name: "Tyron Smith", position: "Offensive Tackle" },
    { name: "Carter Warren", position: "Offensive Tackle" },
    { name: "Micheal Clemons", position: "Defensive End" },
    { name: "Will McDonald IV", position: "Defensive End" },
    { name: "Braiden McGregor", position: "Defensive End" },
    { name: "Haason Reddick", position: "Defensive End" },
    { name: "Solomon Thomas", position: "Defensive End" },
    { name: "Eric Watts", position: "Defensive End" },
    { name: "Javon Kinlaw", position: "Defensive Tackle" },
    { name: "Leonard Taylor III", position: "Defensive Tackle" },
    { name: "Quinnen Williams", position: "Defensive Tackle" },
    { name: "Sam Eguavoen", position: "Linebacker" },
    { name: "Marcelino McCrary-Ball", position: "Linebacker" },
    { name: "C.J. Mosley", position: "Linebacker" },
    { name: "Jamien Sherwood", position: "Linebacker" },
    { name: "Chazz Surratt", position: "Linebacker" },
    { name: "Quincy Williams", position: "Linebacker" },
    { name: "Jarrick Bernard-Converse", position: "Cornerback" },
    { name: "Michael Carter II", position: "Cornerback" },
    { name: "Brandin Echols", position: "Cornerback" },
    { name: "Sauce Gardner", position: "Cornerback" },
    { name: "Isaiah Oliver", position: "Cornerback" },
    { name: "D.J. Reed", position: "Cornerback" },
    { name: "Qwantez Stiggers", position: "Cornerback" },
    { name: "Tony Adams", position: "Safety" },
    { name: "Chuck Clark", position: "Safety" },
    { name: "Ashtyn Davis", position: "Safety" },
    { name: "Jalen Mills", position: "Safety" }
    ],
    "Dallas Cowboys": [
        { name: "Trey Lance", position: "Quarterback" },
    { name: "Cooper Rush", position: "Quarterback" },
    { name: "Rico Dowdle", position: "Running Back" },
    { name: "Ezekiel Elliott", position: "Running Back" },
    { name: "Hunter Luepke", position: "Running Back" },
    { name: "Deuce Vaughn", position: "Running Back" },
    { name: "Jalen Brooks", position: "Wide Receiver" },
    { name: "Ryan Flournoy", position: "Wide Receiver" },
    { name: "CeeDee Lamb", position: "Wide Receiver" },
    { name: "Jonathan Mingo", position: "Wide Receiver" },
    { name: "Jalen Tolbert", position: "Wide Receiver" },
    { name: "KaVontae Turpin", position: "Wide Receiver" },
    { name: "Princeton Fant", position: "Tight End" },
    { name: "Jake Ferguson", position: "Tight End" },
    { name: "Luke Schoonmaker", position: "Tight End" },
    { name: "Breyn Spann-Ford", position: "Tight End" },
    { name: "Brock Hoffman", position: "Center" },
    { name: "T.J. Bass", position: "Guard" },
    { name: "Cooper Beebe", position: "Guard" },
    { name: "Zack Martin", position: "Guard" },
    { name: "Tyler Guyton", position: "Offensive Tackle" },
    { name: "Asim Richards", position: "Offensive Tackle" },
    { name: "Tyler Smith", position: "Offensive Tackle" },
    { name: "Terence Steele", position: "Offensive Tackle" },
    { name: "Matt Waletzko", position: "Offensive Tackle" },
    { name: "Chauncey Golston", position: "Defensive End" },
    { name: "KJ Henry", position: "Defensive End" },
    { name: "Carl Lawson", position: "Defensive End" },
    { name: "Carlos Watkins", position: "Defensive End" },
    { name: "Tyrus Wheat", position: "Defensive End" },
    { name: "Linval Joseph", position: "Defensive Tackle" },
    { name: "Osa Odighizuwa", position: "Defensive Tackle" },
    { name: "Mazi Smith", position: "Defensive Tackle" },
    { name: "Damone Clark", position: "Linebacker" },
    { name: "Buddy Johnson", position: "Linebacker" },
    { name: "Eric Kendricks", position: "Linebacker" },
    { name: "Marist Liufau", position: "Linebacker" },
    { name: "DeMarvion Overshown", position: "Linebacker" },
    { name: "Micah Parsons", position: "Linebacker" },
    { name: "Nick Vigil", position: "Linebacker" },
    { name: "DaRon Bland", position: "Cornerback" },
    { name: "Josh Butler", position: "Cornerback" },
    { name: "Caelen Carson", position: "Cornerback" },
    { name: "Trevon Diggs", position: "Cornerback" },
    { name: "C.J. Goodwin", position: "Cornerback" },
    { name: "Kemon Hall", position: "Cornerback" },
    { name: "Jourdan Lewis", position: "Cornerback" },
    { name: "Markquese Bell", position: "Safety" },
    { name: "Malik Hooker", position: "Safety" },
    { name: "Israel Mukuamu", position: "Safety" },
    { name: "Juanyeh Thomas", position: "Safety" },
    { name: "Donovan Wilson", position: "Safety" }
    ],
    "New York Giants": [
        { name: "Tommy DeVito", position: "Quarterback" },
    { name: "Daniel Jones", position: "Quarterback" },
    { name: "Drew Lock", position: "Quarterback" },
    { name: "Eric Gray", position: "Running Back" },
    { name: "Devin Singletary", position: "Running Back" },
    { name: "Tyrone Tracy Jr.", position: "Running Back" },
    { name: "Bryce Ford-Wheaton", position: "Wide Receiver" },
    { name: "Jalin Hyatt", position: "Wide Receiver" },
    { name: "Malik Nabers", position: "Wide Receiver" },
    { name: "Wan'Dale Robinson", position: "Wide Receiver" },
    { name: "Darius Slayton", position: "Wide Receiver" },
    { name: "Ihmir Smith-Marsette", position: "Wide Receiver" },
    { name: "Daniel Bellinger", position: "Tight End" },
    { name: "Theo Johnson", position: "Tight End" },
    { name: "Chris Manhertz", position: "Tight End" },
    { name: "John Michael Schmitz Jr.", position: "Center" },
    { name: "Jermaine Eluemunor", position: "Guard" },
    { name: "Joshua Ezeudu", position: "Guard" },
    { name: "Chris Hubbard", position: "Guard" },
    { name: "Jake Kubas", position: "Guard" },
    { name: "Jon Runyan", position: "Guard" },
    { name: "Aaron Stinnie", position: "Guard" },
    { name: "Greg Van Roten", position: "Guard" },
    { name: "Evan Neal", position: "Offensive Tackle" },
    { name: "Elijah Chatman", position: "Defensive Tackle" },
    { name: "D.J. Davidson", position: "Defensive Tackle" },
    { name: "Dexter Lawrence II", position: "Defensive Tackle" },
    { name: "Rakeem Nunez-Roches", position: "Defensive Tackle" },
    { name: "Jordon Riley", position: "Defensive Tackle" },
    { name: "Armon Watts", position: "Defensive Tackle" },
    { name: "Matthew Adams", position: "Linebacker" },
    { name: "Brian Burns", position: "Linebacker" },
    { name: "Tomon Fox", position: "Linebacker" },
    { name: "Patrick Johnson", position: "Linebacker" },
    { name: "Micah McFadden", position: "Linebacker" },
    { name: "Darius Muasau", position: "Linebacker" },
    { name: "Azeez Ojulari", position: "Linebacker" },
    { name: "Bobby Okereke", position: "Linebacker" },
    { name: "Isaiah Simmons", position: "Linebacker" },
    { name: "Ty Summers", position: "Linebacker" },
    { name: "Deonte Banks", position: "Cornerback" },
    { name: "Cor'Dale Flott", position: "Cornerback" },
    { name: "Art Green", position: "Cornerback" },
    { name: "Tre Hawkins III", position: "Cornerback" },
    { name: "Adoree' Jackson", position: "Cornerback" },
    { name: "Dru Phillips", position: "Cornerback" },
    { name: "Dane Belton", position: "Safety" },
    { name: "Anthony Johnson Jr.", position: "Safety" },
    { name: "Tyler Nubin", position: "Safety" },
    { name: "Jason Pinnock", position: "Safety" }
    ],
    "Philadelphia Eagles": [
        { name: "Jalen Hurts", position: "Quarterback" },
    { name: "Tanner McKee", position: "Quarterback" },
    { name: "Kenny Pickett", position: "Quarterback" },
    { name: "Saquon Barkley", position: "Running Back" },
    { name: "Kenneth Gainwell", position: "Running Back" },
    { name: "Will Shipley", position: "Running Back" },
    { name: "A.J. Brown", position: "Wide Receiver" },
    { name: "Jahan Dotson", position: "Wide Receiver" },
    { name: "Anias Smith", position: "Wide Receiver" },
    { name: "DeVonta Smith", position: "Wide Receiver" },
    { name: "Johnny Wilson", position: "Wide Receiver" },
    { name: "Grant Calcaterra", position: "Tight End" },
    { name: "Dallas Goedert", position: "Tight End" },
    { name: "Nick Gates", position: "Center" },
    { name: "Cam Jurgens", position: "Center" },
    { name: "Landon Dickerson", position: "Guard" },
    { name: "Trevor Keegan", position: "Guard" },
    { name: "Tyler Steen", position: "Guard" },
    { name: "Darian Kinnard", position: "Offensive Line" },
    { name: "Mekhi Becton", position: "Offensive Tackle" },
    { name: "Jack Driscoll", position: "Offensive Tackle" },
    { name: "Fred Johnson", position: "Offensive Tackle" },
    { name: "Lane Johnson", position: "Offensive Tackle" },
    { name: "Jordan Mailata", position: "Offensive Tackle" },
    { name: "Brandon Graham", position: "Defensive End" },
    { name: "Bryce Huff", position: "Defensive End" },
    { name: "Thomas Booker IV", position: "Defensive Tackle" },
    { name: "Jalen Carter", position: "Defensive Tackle" },
    { name: "Jordan Davis", position: "Defensive Tackle" },
    { name: "Moro Ojomo", position: "Defensive Tackle" },
    { name: "Milton Williams", position: "Defensive Tackle" },
    { name: "Zack Baun", position: "Linebacker" },
    { name: "Oren Burks", position: "Linebacker" },
    { name: "Nakobe Dean", position: "Linebacker" },
    { name: "Jalyx Hunt", position: "Linebacker" },
    { name: "Nolan Smith Jr.", position: "Linebacker" },
    { name: "Josh Sweat", position: "Linebacker" },
    { name: "Jeremiah Trotter Jr.", position: "Linebacker" },
    { name: "Ben VanSumeren", position: "Linebacker" },
    { name: "Cooper DeJean", position: "Cornerback" },
    { name: "Avonte Maddox", position: "Cornerback" },
    { name: "Quinyon Mitchell", position: "Cornerback" },
    { name: "Eli Ricks", position: "Cornerback" },
    { name: "Kelee Ringo", position: "Cornerback" },
    { name: "Isaiah Rodgers", position: "Cornerback" },
    { name: "Darius Slay Jr.", position: "Cornerback" },
    { name: "Reed Blankenship", position: "Safety" },
    { name: "Sydney Brown", position: "Safety" },
    { name: "C.J. Gardner-Johnson", position: "Safety" },
    { name: "Tristin McCollum", position: "Safety" }
    ],
    "Washington Commanders": [
        { name: "Jayden Daniels", position: "Quarterback" },
    { name: "Jeff Driskel", position: "Quarterback" },
    { name: "Marcus Mariota", position: "Quarterback" },
    { name: "Austin Ekeler", position: "Running Back" },
    { name: "Jeremy McNichols", position: "Running Back" },
    { name: "Brian Robinson Jr.", position: "Running Back" },
    { name: "Chris Rodriguez Jr.", position: "Running Back" },
    { name: "Dyami Brown", position: "Wide Receiver" },
    { name: "Noah Brown", position: "Wide Receiver" },
    { name: "Luke McCaffrey", position: "Wide Receiver" },
    { name: "Terry McLaurin", position: "Wide Receiver" },
    { name: "Olamide Zaccheaus", position: "Wide Receiver" },
    { name: "John Bates", position: "Tight End" },
    { name: "Zach Ertz", position: "Tight End" },
    { name: "Ben Sinnott", position: "Tight End" },
    { name: "Tyler Biadasz", position: "Center" },
    { name: "Nick Allegretti", position: "Guard" },
    { name: "Sam Cosmi", position: "Guard" },
    { name: "Michael Deiter", position: "Guard" },
    { name: "Chris Paul", position: "Guard" },
    { name: "Andrew Wylie", position: "Guard" },
    { name: "Brandon Coleman", position: "Offensive Tackle" },
    { name: "Cornelius Lucas", position: "Offensive Tackle" },
    { name: "Trent Scott", position: "Offensive Tackle" },
    { name: "Dorance Armstrong", position: "Defensive End" },
    { name: "Clelin Ferrell", position: "Defensive End" },
    { name: "Sheldon Day", position: "Defensive Tackle" },
    { name: "Jalyn Holmes", position: "Defensive Tackle" },
    { name: "Phidarian Mathis", position: "Defensive Tackle" },
    { name: "JerZhan Newton", position: "Defensive Tackle" },
    { name: "Daron Payne", position: "Defensive Tackle" },
    { name: "Nick Bellore", position: "Linebacker" },
    { name: "Dante Fowler Jr.", position: "Linebacker" },
    { name: "Frankie Luvu", position: "Linebacker" },
    { name: "Jordan Magee", position: "Linebacker" },
    { name: "Bobby Wagner", position: "Linebacker" },
    { name: "Mykal Walker", position: "Linebacker" },
    { name: "Michael Davis", position: "Cornerback" },
    { name: "Emmanuel Forbes Jr.", position: "Cornerback" },
    { name: "Noah Igbinoghene", position: "Cornerback" },
    { name: "Marshon Lattimore", position: "Cornerback" },
    { name: "Mike Sainristil", position: "Cornerback" },
    { name: "Benjamin St-Juste", position: "Cornerback" },
    { name: "Percy Butler", position: "Safety" },
    { name: "Jeremy Chinn", position: "Safety" },
    { name: "Darrick Forrest", position: "Safety" },
    { name: "Dominique Hampton", position: "Safety" },
    { name: "Quan Martin", position: "Safety" },
    { name: "Tyler Owens", position: "Safety" },
    { name: "Jeremy Reaves", position: "Safety" }
    ],
    "Baltimore Ravens": [
        { name: "Lamar Jackson", position: "Quarterback" },
    { name: "Josh Johnson", position: "Quarterback" },
    { name: "Rasheen Ali", position: "Running Back" },
    { name: "Derrick Henry", position: "Running Back" },
    { name: "Justice Hill", position: "Running Back" },
    { name: "Keaton Mitchell", position: "Running Back" },
    { name: "Patrick Ricard", position: "Fullback" },
    { name: "Nelson Agholor", position: "Wide Receiver" },
    { name: "Rashod Bateman", position: "Wide Receiver" },
    { name: "Zay Flowers", position: "Wide Receiver" },
    { name: "Diontae Johnson", position: "Wide Receiver" },
    { name: "Devontez Walker", position: "Wide Receiver" },
    { name: "Tylan Wallace", position: "Wide Receiver" },
    { name: "Mark Andrews", position: "Tight End" },
    { name: "Charlie Kolar", position: "Tight End" },
    { name: "Isaiah Likely", position: "Tight End" },
    { name: "Tyler Linderbaum", position: "Center" },
    { name: "Nick Samac", position: "Center" },
    { name: "Ben Cleveland", position: "Guard" },
    { name: "Patrick Mekari", position: "Guard" },
    { name: "Andrew Vorhees", position: "Guard" },
    { name: "Daniel Faalele", position: "Offensive Tackle" },
    { name: "Josh Jones", position: "Offensive Tackle" },
    { name: "Roger Rosengarten", position: "Offensive Tackle" },
    { name: "Ronnie Stanley", position: "Offensive Tackle" },
    { name: "Brent Urban", position: "Defensive End" },
    { name: "Travis Jones", position: "Defensive Tackle" },
    { name: "Nnadi Madubuike", position: "Defensive Tackle" },
    { name: "Broderick Washington", position: "Defensive Tackle" },
    { name: "Chris Board", position: "Linebacker" },
    { name: "Malik Harrison", position: "Linebacker" },
    { name: "Adisa Isaac", position: "Linebacker" },
    { name: "David Ojabo", position: "Linebacker" },
    { name: "Odafe Oweh", position: "Linebacker" },
    { name: "Tavius Robinson", position: "Linebacker" },
    { name: "Trenton Simpson", position: "Linebacker" },
    { name: "Roquan Smith", position: "Linebacker" },
    { name: "Kyle Van Noy", position: "Linebacker" },
    { name: "Kristian Welch", position: "Linebacker" },
    { name: "Jalyn Armour-Davis", position: "Cornerback" },
    { name: "Marlon Humphrey", position: "Cornerback" },
    { name: "Arthur Maulet", position: "Cornerback" },
    { name: "Brandon Stephens", position: "Cornerback" },
    { name: "Tre'Davious White", position: "Cornerback" },
    { name: "Nate Wiggins", position: "Cornerback" },
    { name: "Beau Brade", position: "Safety" },
    { name: "Kyle Hamilton", position: "Safety" },
    { name: "Eddie Jackson", position: "Safety" },
    { name: "Sanousi Kane", position: "Safety" },
    { name: "Ar'Darius Washington", position: "Safety" },
    { name: "Marcus Williams", position: "Safety" }
    ],
    "Cincinnati Bengals": [
        { name: "Jake Browning", position: "Quarterback" },
        { name: "Joe Burrow", position: "Quarterback" },
        { name: "Chase Brown", position: "Running Back" },
        { name: "Khalil Herbert", position: "Running Back" },
        { name: "Trayveon Williams", position: "Running Back" },
        { name: "Jermaine Burton", position: "Wide Receiver" },
        { name: "Ja'Marr Chase", position: "Wide Receiver" },
        { name: "Tee Higgins", position: "Wide Receiver" },
        { name: "Andrei Iosivas", position: "Wide Receiver" },
        { name: "Trenton Irwin", position: "Wide Receiver" },
        { name: "Charlie Jones", position: "Wide Receiver" },
        { name: "Isaiah Williams", position: "Wide Receiver" },
        { name: "Mike Gesicki", position: "Tight End" },
        { name: "Cam Grandy", position: "Tight End" },
        { name: "Tanner Hudson", position: "Tight End" },
        { name: "Tanner McLachlan", position: "Tight End" },
        { name: "Drew Sample", position: "Tight End" },
        { name: "Ted Karras", position: "Center" },
        { name: "Matt Lee", position: "Center" },
        { name: "Alex Cappa", position: "Guard" },
        { name: "Cody Ford", position: "Guard" },
        { name: "Cordell Volson", position: "Guard" },
        { name: "Orlando Brown Jr.", position: "Offensive Tackle" },
        { name: "Devin Cochran", position: "Offensive Tackle" },
        { name: "Amarius Mims", position: "Offensive Tackle" },
        { name: "Andrew Stueber", position: "Offensive Tackle" },
        { name: "Trey Hendrickson", position: "Defensive End" },
        { name: "Sam Hubbard", position: "Defensive End" },
        { name: "Cedric Johnson", position: "Defensive End" },
        { name: "Myles Murphy", position: "Defensive End" },
        { name: "Joseph Ossai", position: "Defensive End" },
        { name: "B.J. Hill", position: "Defensive Tackle" },
        { name: "McKinley Jackson", position: "Defensive Tackle" },
        { name: "Kris Jenkins Jr.", position: "Defensive Tackle" },
        { name: "Sheldon Rankins", position: "Defensive Tackle" },
        { name: "Jay Tufele", position: "Defensive Tackle" },
        { name: "Joe Bachie", position: "Linebacker" },
        { name: "Akeem Davis-Gaither", position: "Linebacker" },
        { name: "Shaka Heyward", position: "Linebacker" },
        { name: "Maema Njongmeta", position: "Linebacker" },
        { name: "Germaine Pratt", position: "Linebacker" },
        { name: "Logan Wilson", position: "Linebacker" },
        { name: "Mike Hilton", position: "Cornerback" },
        { name: "DJ Ivey", position: "Cornerback" },
        { name: "Josh Newton", position: "Cornerback" },
        { name: "Cam Taylor-Britt", position: "Cornerback" },
        { name: "Marco Wilson", position: "Cornerback" },
        { name: "Tycen Anderson", position: "Safety" },
        { name: "Daijahn Anthony", position: "Safety" },
        { name: "Jordan Battle", position: "Safety" },
        { name: "Vonn Bell", position: "Safety" },
        { name: "Geno Stone", position: "Safety" }
    ],
    "Cleveland Browns": [
        { name: "Dorian Thompson-Robinson", position: "Quarterback" },
        { name: "Jameis Winston", position: "Quarterback" },
        { name: "Bailey Zappe", position: "Quarterback" },
        { name: "Nick Chubb", position: "Running Back" },
        { name: "Jerome Ford", position: "Running Back" },
        { name: "D'Onta Foreman", position: "Running Back" },
        { name: "Pierre Strong Jr.", position: "Running Back" },
        { name: "Jaelon Darden", position: "Wide Receiver" },
        { name: "Jerry Jeudy", position: "Wide Receiver" },
        { name: "Elijah Moore", position: "Wide Receiver" },
        { name: "Jamari Thrash", position: "Wide Receiver" },
        { name: "Cedric Tillman", position: "Wide Receiver" },
        { name: "Kadarius Toney", position: "Wide Receiver" },
        { name: "Jordan Akins", position: "Tight End" },
        { name: "David Njoku", position: "Tight End" },
        { name: "Geoff Swaim", position: "Tight End" },
        { name: "Ethan Pocic", position: "Center" },
        { name: "Joel Bitonio", position: "Guard" },
        { name: "Michael Dunn", position: "Guard" },
        { name: "Germain Ifedi", position: "Guard" },
        { name: "Wyatt Teller", position: "Guard" },
        { name: "Zak Zinter", position: "Guard" },
        { name: "Geron Christian", position: "Offensive Line" },
        { name: "Jack Conklin", position: "Offensive Tackle" },
        { name: "Jedrick Wills Jr.", position: "Offensive Tackle" },
        { name: "Myles Garrett", position: "Defensive End" },
        { name: "Sam Kamara", position: "Defensive End" },
        { name: "Isaiah McGuire", position: "Defensive End" },
        { name: "Ogbo Okoronkwo", position: "Defensive End" },
        { name: "Shelby Harris", position: "Defensive Tackle" },
        { name: "Maurice Hurst II", position: "Defensive Tackle" },
        { name: "Dalvin Tomlinson", position: "Defensive Tackle" },
        { name: "Devin Bush", position: "Linebacker" },
        { name: "Mohamoud Diabate", position: "Linebacker" },
        { name: "Jordan Hicks", position: "Linebacker" },
        { name: "Khaleke Hudson", position: "Linebacker" },
        { name: "Winston Reid", position: "Linebacker" },
        { name: "Elerson G. Smith", position: "Linebacker" },
        { name: "Nathaniel Watson", position: "Linebacker" },
        { name: "Chigozie Anusiem", position: "Cornerback" },
        { name: "Martin Emerson Jr.", position: "Cornerback" },
        { name: "Mike Ford Jr.", position: "Cornerback" },
        { name: "Cameron Mitchell", position: "Cornerback" },
        { name: "Greg Newsome II", position: "Cornerback" },
        { name: "Denzel Ward", position: "Cornerback" },
        { name: "D'Anthony Bell", position: "Safety" },
        { name: "Grant Delpit", position: "Safety" },
        { name: "Ronnie Hickman", position: "Safety" },
        { name: "Rodney McLeod Jr.", position: "Safety" },
        { name: "Juan Thornhill", position: "Safety" }
    ],
    "Pittsburgh Steelers": [
        { name: "Kyle Allen", position: "Quarterback" },
        { name: "Justin Fields", position: "Quarterback" },
        { name: "Russell Wilson", position: "Quarterback" },
        { name: "Najee Harris", position: "Running Back" },
        { name: "Cordarrelle Patterson", position: "Running Back" },
        { name: "Jonathan Ward", position: "Running Back" },
        { name: "Jaylen Warren", position: "Running Back" },
        { name: "Calvin Austin III", position: "Wide Receiver" },
        { name: "Van Jefferson", position: "Wide Receiver" },
        { name: "Scotty Miller", position: "Wide Receiver" },
        { name: "George Pickens", position: "Wide Receiver" },
        { name: "Ben Skowronek", position: "Wide Receiver" },
        { name: "Mike Williams", position: "Wide Receiver" },
        { name: "Pat Freiermuth", position: "Tight End" },
        { name: "Connor Heyward", position: "Tight End" },
        { name: "MyCole Pruitt", position: "Tight End" },
        { name: "Darnell Washington", position: "Tight End" },
        { name: "Zach Frazier", position: "Center" },
        { name: "Ryan McCollum", position: "Center" },
        { name: "Spencer Anderson", position: "Guard" },
        { name: "Mason McCormick", position: "Guard" },
        { name: "Max Scharping", position: "Guard" },
        { name: "Isaac Seumalo", position: "Guard" },
        { name: "Calvin Anderson", position: "Offensive Tackle" },
        { name: "Broderick Jones", position: "Offensive Tackle" },
        { name: "Dan Moore Jr.", position: "Offensive Tackle" },
        { name: "Keeanu Benton", position: "Defensive Tackle" },
        { name: "Cameron Heyward", position: "Defensive Tackle" },
        { name: "Isaiahh Loudermilk", position: "Defensive Tackle" },
        { name: "Dean Lowry", position: "Defensive Tackle" },
        { name: "Larry Ogunjobi", position: "Defensive Tackle" },
        { name: "Nick Herbig", position: "Linebacker" },
        { name: "Alex Highsmith", position: "Linebacker" },
        { name: "Tyler Matakevich", position: "Linebacker" },
        { name: "Jeremiah Moon", position: "Linebacker" },
        { name: "Patrick Queen", position: "Linebacker" },
        { name: "Elandon Roberts", position: "Linebacker" },
        { name: "Mark Robinson", position: "Linebacker" },
        { name: "Preston Smith", position: "Linebacker" },
        { name: "T.J. Watt", position: "Linebacker" },
        { name: "Payton Wilson", position: "Linebacker" },
        { name: "Beanie Bishop Jr.", position: "Cornerback" },
        { name: "Donte Jackson", position: "Cornerback" },
        { name: "James Pierre", position: "Cornerback" },
        { name: "Joey Porter Jr.", position: "Cornerback" },
        { name: "Cameron Sutton", position: "Cornerback" },
        { name: "DeShon Elliott", position: "Safety" },
        { name: "Minkah Fitzpatrick", position: "Safety" },
        { name: "Damontae Kazee", position: "Safety" },
        { name: "Miles Killebrew", position: "Safety" }
    ],
    "Houston Texans": [
        { name: "Davis Mills", position: "Quarterback" },
        { name: "C.J. Stroud", position: "Quarterback" },
        { name: "Joe Mixon", position: "Running Back" },
        { name: "Dare Ogunbowale", position: "Running Back" },
        { name: "Dameon Pierce", position: "Running Back" },
        { name: "Nico Collins", position: "Wide Receiver" },
        { name: "Tank Dell", position: "Wide Receiver" },
        { name: "Xavier Hutchinson", position: "Wide Receiver" },
        { name: "John Metchie III", position: "Wide Receiver" },
        { name: "Steven Sims", position: "Wide Receiver" },
        { name: "Robert Woods", position: "Wide Receiver" },
        { name: "Teagan Quitoriano", position: "Tight End" },
        { name: "Dalton Schultz", position: "Tight End" },
        { name: "Cade Stover", position: "Tight End" },
        { name: "Jarrett Patterson", position: "Center" },
        { name: "Juice Scruggs", position: "Center" },
        { name: "Nick Broeker", position: "Guard" },
        { name: "Kendrick Green", position: "Guard" },
        { name: "Shaq Mason", position: "Guard" },
        { name: "Blake Fisher", position: "Offensive Tackle" },
        { name: "Tytus Howard", position: "Offensive Tackle" },
        { name: "Zach Thomas", position: "Offensive Tackle" },
        { name: "Laremy Tunsil", position: "Offensive Tackle" },
        { name: "Will Anderson Jr.", position: "Defensive End" },
        { name: "Denico Autry", position: "Defensive End" },
        { name: "Derek Barnett", position: "Defensive End" },
        { name: "Dylan Horton", position: "Defensive End" },
        { name: "Jerry Hughes", position: "Defensive End" },
        { name: "Danielle Hunter", position: "Defensive End" },
        { name: "Mario Edwards Jr.", position: "Defensive Tackle" },
        { name: "Folorunso Fatukasi", position: "Defensive Tackle" },
        { name: "Kurt Hinish", position: "Defensive Tackle" },
        { name: "Tim Settle Jr.", position: "Defensive Tackle" },
        { name: "Tommy Togiai", position: "Defensive Tackle" },
        { name: "Azeez Al-Shaair", position: "Linebacker" },
        { name: "Jake Hansen", position: "Linebacker" },
        { name: "Neville Hewitt", position: "Linebacker" },
        { name: "Jamal Hill", position: "Linebacker" },
        { name: "Del'Shawn Phillips", position: "Linebacker" },
        { name: "Henry To'oTo'o", position: "Linebacker" },
        { name: "Devin White", position: "Linebacker" },
        { name: "Kris Boyd", position: "Cornerback" },
        { name: "Kadar Hollman", position: "Cornerback" },
        { name: "Kamari Lassiter", position: "Cornerback" },
        { name: "Jeff Okudah", position: "Cornerback" },
        { name: "Derek Stingley Jr.", position: "Cornerback" },
        { name: "Calen Bullock", position: "Safety" },
        { name: "Eric Murray", position: "Safety" },
        { name: "Jalen Pitre", position: "Safety" },
        { name: "M.J. Stewart", position: "Safety" },
        { name: "Jimmie Ward", position: "Safety" }
    ],
    "Indianapolis Colts": [
        { name: "Sam Ehlinger", position: "Quarterback" },
        { name: "Joe Flacco", position: "Quarterback" },
        { name: "Anthony Richardson", position: "Quarterback" },
        { name: "Tyler Goodson", position: "Running Back" },
        { name: "Trey Sermon", position: "Running Back" },
        { name: "Jonathan Taylor", position: "Running Back" },
        { name: "Josh Downs", position: "Wide Receiver" },
        { name: "Ashton Dulin", position: "Wide Receiver" },
        { name: "Anthony Gould", position: "Wide Receiver" },
        { name: "Adonai Mitchell", position: "Wide Receiver" },
        { name: "Alec Pierce", position: "Wide Receiver" },
        { name: "Michael Pittman Jr.", position: "Wide Receiver" },
        { name: "Mo Alie-Cox", position: "Tight End" },
        { name: "Kylen Granson", position: "Tight End" },
        { name: "Will Mallory", position: "Tight End" },
        { name: "Drew Ogletree", position: "Tight End" },
        { name: "Danny Pinter", position: "Center" },
        { name: "Tanor Bortolini", position: "Guard" },
        { name: "Atonio Mafi", position: "Guard" },
        { name: "Quenton Nelson", position: "Guard" },
        { name: "Josh Sills", position: "Guard" },
        { name: "Dalton Tucker", position: "Guard" },
        { name: "Blake Freeland", position: "Offensive Tackle" },
        { name: "Matt Goncalves", position: "Offensive Tackle" },
        { name: "Bernhard Raimann", position: "Offensive Tackle" },
        { name: "Braden Smith", position: "Offensive Tackle" },
        { name: "Genard Avery", position: "Defensive End" },
        { name: "Isaiah Land", position: "Defensive End" },
        { name: "Laiatu Latu", position: "Defensive End" },
        { name: "Dayo Odeyingbo", position: "Defensive End" },
        { name: "Kwity Paye", position: "Defensive End" },
        { name: "Adetomiwa Adebawore", position: "Defensive Tackle" },
        { name: "Taven Bryan", position: "Defensive Tackle" },
        { name: "DeForest Buckner", position: "Defensive Tackle" },
        { name: "Raekwon Davis", position: "Defensive Tackle" },
        { name: "Grover Stewart", position: "Defensive Tackle" },
        { name: "Liam Anderson", position: "Linebacker" },
        { name: "Zaire Franklin", position: "Linebacker" },
        { name: "Cameron McGrone", position: "Linebacker" },
        { name: "Segun Olubi", position: "Linebacker" },
        { name: "E.J. Speed", position: "Linebacker" },
        { name: "Grant Stuard", position: "Linebacker" },
        { name: "Jaylon Jones", position: "Cornerback" },
        { name: "Chris Lammons", position: "Cornerback" },
        { name: "David Long Jr.", position: "Cornerback" },
        { name: "Kenny Moore II", position: "Cornerback" },
        { name: "Samuel Womack III", position: "Cornerback" },
        { name: "Julian Blackmon", position: "Safety" },
        { name: "Nick Cross", position: "Safety" },
        { name: "Darren Hall", position: "Safety" },
        { name: "Ronnie Harrison Jr.", position: "Safety" },
        { name: "Rodney Thomas II", position: "Safety" }
    ],
    "Jacksonville Jaguars": [
        { name: "C.J. Beathard", position: "Quarterback" },
        { name: "Mac Jones", position: "Quarterback" },
        { name: "Trevor Lawrence", position: "Quarterback" },
        { name: "Tank Bigsby", position: "Running Back" },
        { name: "Travis Etienne Jr.", position: "Running Back" },
        { name: "D'Ernest Johnson", position: "Running Back" },
        { name: "Devin Duvernay", position: "Wide Receiver" },
        { name: "Tim Jones", position: "Wide Receiver" },
        { name: "Velus Jones Jr.", position: "Wide Receiver" },
        { name: "Brian Thomas Jr.", position: "Wide Receiver" },
        { name: "Parker Washington", position: "Wide Receiver" },
        { name: "Josiah Deguara", position: "Tight End" },
        { name: "Evan Engram", position: "Tight End" },
        { name: "Luke Farrell", position: "Tight End" },
        { name: "Brenton Strange", position: "Tight End" },
        { name: "Luke Fortner", position: "Center" },
        { name: "Mitch Morse", position: "Center" },
        { name: "Ezra Cleveland", position: "Guard" },
        { name: "Blake Hance", position: "Guard" },
        { name: "Brandon Scherff", position: "Guard" },
        { name: "Javan Foster", position: "Offensive Tackle" },
        { name: "Anton Harrison", position: "Offensive Tackle" },
        { name: "Walker Little", position: "Offensive Tackle" },
        { name: "Cole Van Lanen", position: "Offensive Tackle" },
        { name: "Arik Armstead", position: "Defensive End" },
        { name: "Myles Cole", position: "Defensive End" },
        { name: "Josh Hines-Allen", position: "Defensive End" },
        { name: "Travon Walker", position: "Defensive End" },
        { name: "DaVon Hamilton", position: "Defensive Tackle" },
        { name: "Jordan Jefferson", position: "Defensive Tackle" },
        { name: "Tyler Lacy", position: "Defensive Tackle" },
        { name: "Jeremiah Ledbetter", position: "Defensive Tackle" },
        { name: "Esezi Otomewo", position: "Defensive Tackle" },
        { name: "Mason Smith", position: "Defensive Tackle" },
        { name: "Yasir Abdullah", position: "Linebacker" },
        { name: "Caleb Johnson", position: "Linebacker" },
        { name: "Devin Lloyd", position: "Linebacker" },
        { name: "Ventrell Miller", position: "Linebacker" },
        { name: "Chad Muma", position: "Linebacker" },
        { name: "Foyesade Oluokun", position: "Linebacker" },
        { name: "Anthony Pittman", position: "Linebacker" },
        { name: "Montaric Brown", position: "Cornerback" },
        { name: "Tyson Campbell", position: "Cornerback" },
        { name: "Ronald Darby", position: "Cornerback" },
        { name: "Jarrion Jones", position: "Cornerback" },
        { name: "De'Antre Prince", position: "Cornerback" },
        { name: "Andre Cisco", position: "Safety" },
        { name: "Antonio Johnson", position: "Safety" },
        { name: "Darrell Savage", position: "Safety" },
        { name: "Daniel Thomas", position: "Safety" },
        { name: "Andrew Wingard", position: "Safety" }
    ],
    "Tennessee Titans": [
        { name: "Will Levis", position: "Quarterback" },
        { name: "Mason Rudolph", position: "Quarterback" },
        { name: "Julius Chestnut", position: "Running Back" },
        { name: "Joshua Kelley", position: "Running Back" },
        { name: "Tony Pollard", position: "Running Back" },
        { name: "Tyjae Spears", position: "Running Back" },
        { name: "Tyler Boyd", position: "Wide Receiver" },
        { name: "Jha'Quan Jackson", position: "Wide Receiver" },
        { name: "Bryce Oliver", position: "Wide Receiver" },
        { name: "Calvin Ridley", position: "Wide Receiver" },
        { name: "Nick Westbrook-Ikhine", position: "Wide Receiver" },
        { name: "David Martin-Robinson", position: "Tight End" },
        { name: "Chig Okonkwo", position: "Tight End" },
        { name: "Nick Vannett", position: "Tight End" },
        { name: "Josh Whyle", position: "Tight End" },
        { name: "Logan Bruss", position: "Guard" },
        { name: "Corey Levin", position: "Offensive Line" },
        { name: "Daniel Brunskill", position: "Offensive Tackle" },
        { name: "JC Latham", position: "Offensive Tackle" },
        { name: "John Ojukwu", position: "Offensive Tackle" },
        { name: "Nicholas Petit-Frere", position: "Offensive Tackle" },
        { name: "Isaiah Prince", position: "Offensive Tackle" },
        { name: "Dillon Radunz", position: "Offensive Tackle" },
        { name: "Peter Skoronski", position: "Offensive Tackle" },
        { name: "Leroy Watson IV", position: "Offensive Tackle" },
        { name: "Keondre Coburn", position: "Defensive Tackle" },
        { name: "Sebastian Joseph-Day", position: "Defensive Tackle" },
        { name: "James Lynch", position: "Defensive Tackle" },
        { name: "Jeffrey Simmons", position: "Defensive Tackle" },
        { name: "T'Vondre Sweat", position: "Defensive Tackle" },
        { name: "Jerome Baker", position: "Linebacker" },
        { name: "Ali Gaye", position: "Linebacker" },
        { name: "Jack Gibbens", position: "Linebacker" },
        { name: "Luke Gifford", position: "Linebacker" },
        { name: "Cedric Gray", position: "Linebacker" },
        { name: "Jaylen Harrell", position: "Linebacker" },
        { name: "Arden Key", position: "Linebacker" },
        { name: "Harold Landry III", position: "Linebacker" },
        { name: "Kenneth Murray Jr.", position: "Linebacker" },
        { name: "Otis Reese IV", position: "Linebacker" },
        { name: "James Williams", position: "Linebacker" },
        { name: "Tre Avery", position: "Cornerback" },
        { name: "Darrell Baker Jr.", position: "Cornerback" },
        { name: "Jarvis Brownlee Jr.", position: "Cornerback" },
        { name: "Justin Hardee Sr.", position: "Cornerback" },
        { name: "Gabe Jeudy-Lally", position: "Cornerback" },
        { name: "Roger McCreary", position: "Cornerback" },
        { name: "L'Jarius Sneed", position: "Cornerback" },
        { name: "Daryl Worley", position: "Cornerback" },
        { name: "Mike Brown", position: "Safety" },
        { name: "Amani Hooker", position: "Safety" },
        { name: "Julius Wood", position: "Safety" }
    ],
    "Denver Broncos": [
        { name: "Bo Nix", position: "Quarterback" },
        { name: "Jarrett Stidham", position: "Quarterback" },
        { name: "Zach Wilson", position: "Quarterback" },
        { name: "Audric Estime", position: "Running Back" },
        { name: "Jaleel McLaughlin", position: "Running Back" },
        { name: "Javonte Williams", position: "Running Back" },
        { name: "Michael Burton", position: "Fullback" },
        { name: "Troy Franklin", position: "Wide Receiver" },
        { name: "Lil'Jordan Humphrey", position: "Wide Receiver" },
        { name: "Marvin Mims Jr.", position: "Wide Receiver" },
        { name: "Courtland Sutton", position: "Wide Receiver" },
        { name: "Devaughn Vele", position: "Wide Receiver" },
        { name: "Nate Adkins", position: "Tight End" },
        { name: "Greg Dulcich", position: "Tight End" },
        { name: "Lucas Krull", position: "Tight End" },
        { name: "Adam Trautman", position: "Tight End" },
        { name: "Alex Forsyth", position: "Center" },
        { name: "Luke Wattenberg", position: "Center" },
        { name: "Quinn Meinerz", position: "Guard" },
        { name: "Ben Powers", position: "Guard" },
        { name: "Calvin Throckmorton", position: "Guard" },
        { name: "Garett Bolles", position: "Offensive Tackle" },
        { name: "Frank Crum", position: "Offensive Tackle" },
        { name: "Mike McGlinchey", position: "Offensive Tackle" },
        { name: "Alex Palczewski", position: "Offensive Tackle" },
        { name: "Matt Peart", position: "Offensive Tackle" },
        { name: "Zach Allen", position: "Defensive End" },
        { name: "John Franklin-Myers", position: "Defensive End" },
        { name: "Eyoma Uwazurike", position: "Defensive End" },
        { name: "Jordan Jackson", position: "Defensive Tackle" },
        { name: "D.J. Jones", position: "Defensive Tackle" },
        { name: "Malcolm Roach", position: "Defensive Tackle" },
        { name: "Levelle Bailey", position: "Linebacker" },
        { name: "Cody Barton", position: "Linebacker" },
        { name: "Nik Bonitto", position: "Linebacker" },
        { name: "Jonathon Cooper", position: "Linebacker" },
        { name: "Zach Cunningham", position: "Linebacker" },
        { name: "Jonah Ellis", position: "Linebacker" },
        { name: "Justin Strnad", position: "Linebacker" },
        { name: "Dondrea Tillman", position: "Linebacker" },
        { name: "Kris Abrams-Draine", position: "Cornerback" },
        { name: "Damarri Mathis", position: "Cornerback" },
        { name: "Ja'Quan McMillian", position: "Cornerback" },
        { name: "Riley Moss", position: "Cornerback" },
        { name: "Tremon Smith", position: "Cornerback" },
        { name: "Pat Surtain II", position: "Cornerback" },
        { name: "Levi Wallace", position: "Cornerback" },
        { name: "Brandon Jones", position: "Safety" },
        { name: "Devon Key", position: "Safety" },
        { name: "P.J. Locke", position: "Safety" },
        { name: "JL Skinner", position: "Safety" },
        { name: "Keidron Smith", position: "Safety" }
    ],
    "Kansas City Chiefs": [
        { name: "Patrick Mahomes", position: "Quarterback" },
        { name: "Carson Wentz", position: "Quarterback" },
        { name: "Clyde Edwards-Helaire", position: "Running Back" },
        { name: "Kareem Hunt", position: "Running Back" },
        { name: "Samaje Perine", position: "Running Back" },
        { name: "Carson Steele", position: "Running Back" },
        { name: "Mecole Hardman", position: "Wide Receiver" },
        { name: "DeAndre Hopkins", position: "Wide Receiver" },
        { name: "JuJu Smith-Schuster", position: "Wide Receiver" },
        { name: "Justin Watson", position: "Wide Receiver" },
        { name: "Xavier Worthy", position: "Wide Receiver" },
        { name: "Noah Gray", position: "Tight End" },
        { name: "Peyton Hendershot", position: "Tight End" },
        { name: "Travis Kelce", position: "Tight End" },
        { name: "Creed Humphrey", position: "Center" },
        { name: "Hunter Nourzad", position: "Center" },
        { name: "Mike Caliendo", position: "Guard" },
        { name: "C.J. Hanson", position: "Guard" },
        { name: "Trey Smith", position: "Guard" },
        { name: "Joe Thuney", position: "Guard" },
        { name: "Ethan Driskell", position: "Offensive Tackle" },
        { name: "Wanya Morris", position: "Offensive Tackle" },
        { name: "Kingsley Suamataia", position: "Offensive Tackle" },
        { name: "Jawaan Taylor", position: "Offensive Tackle" },
        { name: "Felix Anudike-Uzomah", position: "Defensive End" },
        { name: "Mike Danna", position: "Defensive End" },
        { name: "Malik Herring", position: "Defensive End" },
        { name: "George Karlaftis", position: "Defensive End" },
        { name: "Cameron Thomas", position: "Defensive Tackle" },
        { name: "Chris Jones", position: "Defensive Tackle" },
        { name: "Derrick Nnadi", position: "Defensive Tackle" },
        { name: "Mike Pennel Jr.", position: "Defensive Tackle" },
        { name: "Marlon Tuipulotu", position: "Defensive Tackle" },
        { name: "Tershawn Wharton", position: "Defensive Tackle" },
        { name: "Nick Bolton", position: "Linebacker" },
        { name: "Leo Chenal", position: "Linebacker" },
        { name: "Cole Christiansen", position: "Linebacker" },
        { name: "Jack Cochrane", position: "Linebacker" },
        { name: "Cam Jones", position: "Linebacker" },
        { name: "Drue Tranquill", position: "Linebacker" },
        { name: "Joshua Uche", position: "Linebacker" },
        { name: "Trent McDuffie", position: "Cornerback" },
        { name: "Christian Roland-Wallace", position: "Cornerback" },
        { name: "Keith Taylor Jr.", position: "Cornerback" },
        { name: "Joshua Williams", position: "Cornerback" },
        { name: "Chamarri Conner", position: "Safety" },
        { name: "Bryan Cook", position: "Safety" },
        { name: "Jaden Hicks", position: "Safety" },
        { name: "Nazeeh Johnson", position: "Safety" },
        { name: "Justin Reid", position: "Safety" }
    ],
    "Las Vegas Raiders": [
        { name: "Gardner Minshew", position: "Quarterback" },
        { name: "Desmond Ridder", position: "Quarterback" },
        { name: "Ameer Abdullah", position: "Running Back" },
        { name: "Dylan Laube", position: "Running Back" },
        { name: "Alexander Mattison", position: "Running Back" },
        { name: "Zamir White", position: "Running Back" },
        { name: "Ramel Keyton", position: "Wide Receiver" },
        { name: "Terrace Marshall Jr.", position: "Wide Receiver" },
        { name: "Jakobi Meyers", position: "Wide Receiver" },
        { name: "Tre Tucker", position: "Wide Receiver" },
        { name: "DJ Turner", position: "Wide Receiver" },
        { name: "Brock Bowers", position: "Tight End" },
        { name: "Harrison Bryant", position: "Tight End" },
        { name: "Michael Mayer", position: "Tight End" },
        { name: "Justin Shorter", position: "Tight End" },
        { name: "Andre James", position: "Center" },
        { name: "Will Putnam", position: "Center" },
        { name: "Jordan Meredith", position: "Guard" },
        { name: "Dylan Parham", position: "Guard" },
        { name: "Jackson Powers-Johnson", position: "Guard" },
        { name: "Cody Whitehair", position: "Guard" },
        { name: "Andrus Peat", position: "Offensive Line" },
        { name: "DJ Glaze", position: "Offensive Tackle" },
        { name: "Kolton Miller", position: "Offensive Tackle" },
        { name: "Thayer Munford Jr.", position: "Offensive Tackle" },
        { name: "K'Lavon Chaisson", position: "Defensive End" },
        { name: "Maxx Crosby", position: "Defensive End" },
        { name: "Janarius Robinson", position: "Defensive End" },
        { name: "Charles Snowden", position: "Defensive End" },
        { name: "Tyree Wilson", position: "Defensive End" },
        { name: "Adam Butler", position: "Defensive Tackle" },
        { name: "Matthew Butler", position: "Defensive Tackle" },
        { name: "Zach Carter", position: "Defensive Tackle" },
        { name: "John Jenkins", position: "Defensive Tackle" },
        { name: "Jonah Laulu", position: "Defensive Tackle" },
        { name: "Amari Burney", position: "Linebacker" },
        { name: "Divine Deablo", position: "Linebacker" },
        { name: "Tommy Eichenberg", position: "Linebacker" },
        { name: "Amari Gainer", position: "Linebacker" },
        { name: "Kana'i Mauga", position: "Linebacker" },
        { name: "Robert Spillane", position: "Linebacker" },
        { name: "Jakorian Bennett", position: "Cornerback" },
        { name: "Nate Hobbs", position: "Cornerback" },
        { name: "Damany Holmes", position: "Cornerback" },
        { name: "Jack Jones", position: "Cornerback" },
        { name: "Decamerion Richardson", position: "Cornerback" },
        { name: "Sam Webb", position: "Cornerback" },
        { name: "Thomas Harper", position: "Safety" },
        { name: "Tre'von Moehrig", position: "Safety" },
        { name: "Isaiah Pola-Mao", position: "Safety" },
        { name: "Chris Smith II", position: "Safety" },
        { name: "Trey Taylor", position: "Safety" }
    ],
    "Los Angeles Chargers": [
        { name: "Taylor Heinicke", position: "Quarterback" },
        { name: "Justin Herbert", position: "Quarterback" },
        { name: "Easton Stick", position: "Quarterback" },
        { name: "J.K. Dobbins", position: "Running Back" },
        { name: "Gus Edwards", position: "Running Back" },
        { name: "Hassan Haskins", position: "Running Back" },
        { name: "Kimani Vidal", position: "Running Back" },
        { name: "DJ Chark Jr.", position: "Wide Receiver" },
        { name: "Derius Davis", position: "Wide Receiver" },
        { name: "Quentin Johnston", position: "Wide Receiver" },
        { name: "Ladd McConkey", position: "Wide Receiver" },
        { name: "Joshua Palmer", position: "Wide Receiver" },
        { name: "Jalen Reagor", position: "Wide Receiver" },
        { name: "Will Dissly", position: "Tight End" },
        { name: "Tucker Fisk", position: "Tight End" },
        { name: "Hayden Hurst", position: "Tight End" },
        { name: "Stone Smartt", position: "Tight End" },
        { name: "Bradley Bozeman", position: "Center" },
        { name: "Sam Mustipher", position: "Center" },
        { name: "Brenden Jaimes", position: "Guard" },
        { name: "Zion Johnson", position: "Guard" },
        { name: "Jordan McFadden", position: "Guard" },
        { name: "Jamaree Salyer", position: "Guard" },
        { name: "Joe Alt", position: "Offensive Tackle" },
        { name: "Trey Pipkins III", position: "Offensive Tackle" },
        { name: "Foster Sarell", position: "Offensive Tackle" },
        { name: "Rashawn Slater", position: "Offensive Tackle" },
        { name: "Morgan Fox", position: "Defensive End" },
        { name: "Justin Eboigbe", position: "Defensive Tackle" },
        { name: "Poona Ford", position: "Defensive Tackle" },
        { name: "Scott Matlock", position: "Defensive Tackle" },
        { name: "Otito Ogbonnia", position: "Defensive Tackle" },
        { name: "Teair Tart", position: "Defensive Tackle" },
        { name: "Joey Bosa", position: "Linebacker" },
        { name: "Bud Dupree", position: "Linebacker" },
        { name: "Troy Dye", position: "Linebacker" },
        { name: "Daiyan Henley", position: "Linebacker" },
        { name: "Khalil Mack", position: "Linebacker" },
        { name: "Caleb Murphy", position: "Linebacker" },
        { name: "Nick Niemann", position: "Linebacker" },
        { name: "Denzel Perryman", position: "Linebacker" },
        { name: "Shaq Quarterman", position: "Linebacker" },
        { name: "Tuli Tuipulotu", position: "Linebacker" },
        { name: "Eli Apple", position: "Cornerback" },
        { name: "Dicaprio Bootle", position: "Cornerback" },
        { name: "Kristian Fulton", position: "Cornerback" },
        { name: "Cam Hart", position: "Cornerback" },
        { name: "Elijah Molden", position: "Cornerback" },
        { name: "Tarheeb Still", position: "Cornerback" },
        { name: "Ja'Sir Taylor", position: "Cornerback" },
        { name: "AJ Finley", position: "Safety" },
        { name: "Alohi Gilman", position: "Safety" },
        { name: "Derwin James Jr.", position: "Safety" }
    ],
    "Chicago Bears": [
        { name: "Tyson Bagent", position: "Quarterback" },
        { name: "Caleb Williams", position: "Quarterback" },
        { name: "Travis Homer", position: "Running Back" },
        { name: "Roschon Johnson", position: "Running Back" },
        { name: "D'Andre Swift", position: "Running Back" },
        { name: "Keenan Allen", position: "Wide Receiver" },
        { name: "DeAndre Carter", position: "Wide Receiver" },
        { name: "DJ Moore", position: "Wide Receiver" },
        { name: "Rome Odunze", position: "Wide Receiver" },
        { name: "Tyler Scott", position: "Wide Receiver" },
        { name: "Gerald Everett", position: "Tight End" },
        { name: "Cole Kmet", position: "Tight End" },
        { name: "Marcedes Lewis", position: "Tight End" },
        { name: "Ryan Bates", position: "Center" },
        { name: "Doug Kramer Jr.", position: "Center" },
        { name: "Coleman Shelton", position: "Center" },
        { name: "Teven Jenkins", position: "Guard" },
        { name: "Matt Pryor", position: "Guard" },
        { name: "Kiran Amegadjie", position: "Offensive Tackle" },
        { name: "Larry Borom", position: "Offensive Tackle" },
        { name: "Jake Curhan", position: "Offensive Tackle" },
        { name: "Braxton Jones", position: "Offensive Tackle" },
        { name: "Darnell Wright", position: "Offensive Tackle" },
        { name: "Austin Booker", position: "Defensive End" },
        { name: "Daniel Hardy", position: "Defensive End" },
        { name: "Jacob Martin", position: "Defensive End" },
        { name: "Dominique Robinson", position: "Defensive End" },
        { name: "Montez Sweat", position: "Defensive End" },
        { name: "Darrell Taylor", position: "Defensive End" },
        { name: "DeMarcus Walker", position: "Defensive End" },
        { name: "Byron Cowart", position: "Defensive Tackle" },
        { name: "Gervon Dexter Sr.", position: "Defensive Tackle" },
        { name: "Zacch Pickens", position: "Defensive Tackle" },
        { name: "Chris Williams", position: "Defensive Tackle" },
        { name: "Tremaine Edmunds", position: "Linebacker" },
        { name: "T.J. Edwards", position: "Linebacker" },
        { name: "Amen Ogbongbemiga", position: "Linebacker" },
        { name: "Jack Sanborn", position: "Linebacker" },
        { name: "Noah Sewell", position: "Linebacker" },
        { name: "Josh Blackwell", position: "Cornerback" },
        { name: "Kyler Gordon", position: "Cornerback" },
        { name: "Jaylon Johnson", position: "Cornerback" },
        { name: "Terell Smith", position: "Cornerback" },
        { name: "Ameer Speed", position: "Cornerback" },
        { name: "Tyrique Stevenson", position: "Cornerback" },
        { name: "Kevin Byard III", position: "Safety" },
        { name: "Elijah Hicks", position: "Safety" },
        { name: "Tarvarius Moore", position: "Safety" },
        { name: "Jonathan Owens", position: "Safety" }
    ],
    "Detroit Lions": [
        { name: "Jared Goff", position: "Quarterback" },
        { name: "Hendon Hooker", position: "Quarterback" },
        { name: "Jahmyr Gibbs", position: "Running Back" },
        { name: "Justin Jackson", position: "Running Back" },
        { name: "David Montgomery", position: "Running Back" },
        { name: "Craig Reynolds", position: "Running Back" },
        { name: "Sione Vaki", position: "Running Back" },
        { name: "Tim Patrick", position: "Wide Receiver" },
        { name: "Kalif Raymond", position: "Wide Receiver" },
        { name: "Allen Robinson", position: "Wide Receiver" },
        { name: "Amon-Ra St. Brown", position: "Wide Receiver" },
        { name: "Jameson Williams", position: "Wide Receiver" },
        { name: "Sam LaPorta", position: "Tight End" },
        { name: "James Mitchell", position: "Tight End" },
        { name: "Brock Wright", position: "Tight End" },
        { name: "Shane Zylstra", position: "Tight End" },
        { name: "Frank Ragnow", position: "Center" },
        { name: "Kayode Awosika", position: "Guard" },
        { name: "Graham Glasgow", position: "Guard" },
        { name: "Christian Mahogany", position: "Guard" },
        { name: "Michael Niese", position: "Guard" },
        { name: "Kevin Zeitler", position: "Guard" },
        { name: "Taylor Decker", position: "Offensive Tackle" },
        { name: "Giovanni Manu", position: "Offensive Tackle" },
        { name: "Penei Sewell", position: "Offensive Tackle" },
        { name: "Dan Skipper", position: "Offensive Tackle" },
        { name: "Colby Sorsdal", position: "Offensive Tackle" },
        { name: "Pat O'Connor", position: "Defensive End" },
        { name: "Levi Onwuzurike", position: "Defensive End" },
        { name: "Josh Paschal", position: "Defensive End" },
        { name: "Za'Darius Smith", position: "Defensive End" },
        { name: "Alim McNeill", position: "Defensive Tackle" },
        { name: "DJ Reader", position: "Defensive Tackle" },
        { name: "Mekhi Wingo", position: "Defensive Tackle" },
        { name: "Jack Campbell", position: "Linebacker" },
        { name: "James Houston", position: "Linebacker" },
        { name: "Al-Quadin Muhammad", position: "Linebacker" },
        { name: "Ben Niemann", position: "Linebacker" },
        { name: "Trevor Nowaske", position: "Linebacker" },
        { name: "Malcolm Rodriguez", position: "Linebacker" },
        { name: "Ezekiel Turner", position: "Linebacker" },
        { name: "Terrion Arnold", position: "Cornerback" },
        { name: "Carlton Davis III", position: "Cornerback" },
        { name: "Khalil Dorsey", position: "Cornerback" },
        { name: "Ennis Rakestraw Jr.", position: "Cornerback" },
        { name: "Amik Robertson", position: "Cornerback" },
        { name: "Kindle Vildor", position: "Cornerback" },
        { name: "Brian Branch", position: "Safety" },
        { name: "Brandon Joseph", position: "Safety" },
        { name: "Kerby Joseph", position: "Safety" },
        { name: "Loren Strickland", position: "Safety" }
    ],
    "Green Bay Packers": [
        { name: "Jordan Love", position: "Quarterback" },
        { name: "Malik Willis", position: "Quarterback" },
        { name: "Chris Brooks", position: "Running Back" },
        { name: "Josh Jacobs", position: "Running Back" },
        { name: "MarShawn Lloyd", position: "Running Back" },
        { name: "Emanuel Wilson", position: "Running Back" },
        { name: "Romeo Doubs", position: "Wide Receiver" },
        { name: "Malik Heath", position: "Wide Receiver" },
        { name: "Bo Melton", position: "Wide Receiver" },
        { name: "Jayden Reed", position: "Wide Receiver" },
        { name: "Christian Watson", position: "Wide Receiver" },
        { name: "Dontayvion Wicks", position: "Wide Receiver" },
        { name: "John FitzPatrick", position: "Tight End" },
        { name: "Tucker Kraft", position: "Tight End" },
        { name: "Ben Sims", position: "Tight End" },
        { name: "Jacob Monk", position: "Center" },
        { name: "Josh Myers", position: "Center" },
        { name: "Elgton Jenkins", position: "Guard" },
        { name: "Sean Rhyan", position: "Guard" },
        { name: "Zach Tom", position: "Guard" },
        { name: "Andre Dillard", position: "Offensive Tackle" },
        { name: "Travis Glover", position: "Offensive Tackle" },
        { name: "Kadeem Telfort", position: "Offensive Tackle" },
        { name: "Rasheed Walker", position: "Offensive Tackle" },
        { name: "Karl Brooks", position: "Defensive End" },
        { name: "Brenton Cox Jr.", position: "Defensive End" },
        { name: "Kingsley Enagbare", position: "Defensive End" },
        { name: "Rashan Gary", position: "Defensive End" },
        { name: "Arron Mosby", position: "Defensive End" },
        { name: "Lukas Van Ness", position: "Defensive End" },
        { name: "Kenny Clark", position: "Defensive Tackle" },
        { name: "T.J. Slaton", position: "Defensive Tackle" },
        { name: "Colby Wooden", position: "Defensive Tackle" },
        { name: "Devonte Wyatt", position: "Defensive Tackle" },
        { name: "Edgerrin Cooper", position: "Linebacker" },
        { name: "Ty'Ron Hopper", position: "Linebacker" },
        { name: "Isaiah McDuffie", position: "Linebacker" },
        { name: "Quay Walker", position: "Linebacker" },
        { name: "Eric Wilson", position: "Linebacker" },
        { name: "Jaire Alexander", position: "Cornerback" },
        { name: "Corey Ballentine", position: "Cornerback" },
        { name: "Keisean Nixon", position: "Cornerback" },
        { name: "Robert Rochell", position: "Cornerback" },
        { name: "Eric Stokes", position: "Cornerback" },
        { name: "Carrington Valentine", position: "Cornerback" },
        { name: "Zayne Anderson", position: "Safety" },
        { name: "Javon Bullard", position: "Safety" },
        { name: "Xavier McKinney", position: "Safety" },
        { name: "Kitan Oladapo", position: "Safety" },
        { name: "Evan Williams", position: "Safety" }
    ],
    "Minnesota Vikings": [
        { name: "Sam Darnold", position: "Quarterback" },
        { name: "Nick Mullens", position: "Quarterback" },
        { name: "Brett Rypien", position: "Quarterback" },
        { name: "Cam Akers", position: "Running Back" },
        { name: "Ty Chandler", position: "Running Back" },
        { name: "Aaron Jones", position: "Running Back" },
        { name: "C.J. Ham", position: "Fullback" },
        { name: "Jordan Addison", position: "Wide Receiver" },
        { name: "Justin Jefferson", position: "Wide Receiver" },
        { name: "Jalen Nailor", position: "Wide Receiver" },
        { name: "Brandon Powell", position: "Wide Receiver" },
        { name: "Trent Sherfield Sr.", position: "Wide Receiver" },
        { name: "T.J. Hockenson", position: "Tight End" },
        { name: "Johnny Mundt", position: "Tight End" },
        { name: "Josh Oliver", position: "Tight End" },
        { name: "Garrett Bradbury", position: "Center" },
        { name: "Michael Jurgens", position: "Center" },
        { name: "Blake Brandel", position: "Guard" },
        { name: "Dan Feeney", position: "Guard" },
        { name: "Ed Ingram", position: "Guard" },
        { name: "Dalton Risner", position: "Guard" },
        { name: "Brian O’Neill", position: "Offensive Tackle" },
        { name: "David Quessenberry", position: "Offensive Tackle" },
        { name: "Cam Robinson", position: "Offensive Tackle" },
        { name: "Walter Rouse", position: "Offensive Tackle" },
        { name: "Jonathan Bullard", position: "Defensive End" },
        { name: "Harrison Phillips", position: "Defensive Tackle" },
        { name: "Jalen Redmond", position: "Defensive Tackle" },
        { name: "Levi Drake Rodriguez", position: "Defensive Tackle" },
        { name: "Jerry Tillery", position: "Defensive Tackle" },
        { name: "Brian Asamoah II", position: "Linebacker" },
        { name: "Blake Cashman", position: "Linebacker" },
        { name: "Jonathan Greenard", position: "Linebacker" },
        { name: "Kamu Grugier-Hill", position: "Linebacker" },
        { name: "Pat Jones II", position: "Linebacker" },
        { name: "Ivan Pace Jr.", position: "Linebacker" },
        { name: "Bo Richter", position: "Linebacker" },
        { name: "Dallas Turner", position: "Linebacker" },
        { name: "Andrew Van Ginkel", position: "Linebacker" },
        { name: "Jihad Ward", position: "Linebacker" },
        { name: "Akayleb Evans", position: "Cornerback" },
        { name: "Stephon Gilmore", position: "Cornerback" },
        { name: "Shaquill Griffin", position: "Cornerback" },
        { name: "Dwight McGlothern", position: "Cornerback" },
        { name: "Fabian Moreau", position: "Cornerback" },
        { name: "Byron Murphy Jr.", position: "Cornerback" },
        { name: "Camryn Bynum", position: "Safety" },
        { name: "Theo Jackson", position: "Safety" },
        { name: "Josh Metellus", position: "Safety" },
        { name: "Harrison Smith", position: "Safety" },
        { name: "Jay Ward", position: "Safety" }
    ],
    "Atlanta Falcons": [
        {name: "Kirk Cousins", position: "Quarterback"},
        {name: "Michael Penix Jr.", position: "Quarterback"},
        {name: "Tyler Allgeier", position: "Running Back"},
        {name: "Jase McClellan", position: "Running Back"},
        {name: "Bijan Robinson", position: "Running Back"},
        {name: "Avery Williams", position: "Running Back"},
        {name: "KhaDarel Hodge", position: "Wide Receiver"},
        {name: "Drake London", position: "Wide Receiver"},
        {name: "Ray-Ray McCloud III", position: "Wide Receiver"},
        {name: "Darnell Mooney", position: "Wide Receiver"},
        {name: "Casey Washington", position: "Wide Receiver"},
        {name: "Ross Dwelley", position: "Tight End"},
        {name: "Kyle Pitts", position: "Tight End"},
        {name: "Charlie Woerner", position: "Tight End"},
        {name: "Drew Dalman", position: "Center"},
        {name: "Matthew Bergeron", position: "Guard"},
        {name: "Jovaughn Gwyn", position: "Guard"},
        {name: "Kyle Hinton", position: "Guard"},
        {name: "Chris Lindstrom", position: "Guard"},
        {name: "Ryan Neuzil", position: "Guard"},
        {name: "Jake Matthews", position: "Offensive Tackle"},
        {name: "Kaleb McGary", position: "Offensive Tackle"},
        {name: "Storm Norton", position: "Offensive Tackle"},
        {name: "Brandon Parker", position: "Offensive Tackle"},
        {name: "Elijah Wilkinson", position: "Offensive Tackle"},
        {name: "Zach Harrison", position: "Defensive End"},
        {name: "Grady Jarrett", position: "Defensive End"},
        {name: "Brandon Dorilus", position: "Defensive Tackle"},
        {name: "Eddie Goldman", position: "Defensive Tackle"},
        {name: "David Onyemata", position: "Defensive Tackle"},
        {name: "Kentavius Street", position: "Defensive Tackle"},
        {name: "Troy Andersen", position: "Linebacker"},
        {name: "JD Bertrand", position: "Linebacker"},
        {name: "Lorenzo Carter", position: "Linebacker"},
        {name: "Arnold Ebiketie", position: "Linebacker"},
        {name: "Kaden Elliss", position: "Linebacker"},
        {name: "Rashaan Evans", position: "Linebacker"},
        {name: "Matthew Judon", position: "Linebacker"},
        {name: "Khalid Kareem", position: "Linebacker"},
        {name: "Nate Landman", position: "Linebacker"},
        {name: "DeAngelo Malone", position: "Linebacker"},
        {name: "Dee Alford", position: "Cornerback"},
        {name: "Natrone Brooks", position: "Cornerback"},
        {name: "Antonio Hamilton Sr.", position: "Cornerback"},
        {name: "Mike Hughes", position: "Cornerback"},
        {name: "Kevin King", position: "Cornerback"},
        {name: "Clark Phillips III", position: "Cornerback"},
        {name: "A.J. Terrell", position: "Cornerback"},
        {name: "Jessie Bates III", position: "Safety"},
        {name: "Dane Cruikshank", position: "Safety"},
        {name: "Richie Grant", position: "Safety"},
        {name: "Justin Simmons", position: "Safety"}
    ],
    "Carolina Panthers": [
        {name: "Andy Dalton", position: "Quarterback"},
        {name: "Bryce Young", position: "Quarterback"},
        {name: "Raheem Blackshear", position: "Running Back"},
        {name: "Jonathon Brooks", position: "Running Back"},
        {name: "Chuba Hubbard", position: "Running Back"},
        {name: "Miles Sanders", position: "Running Back"},
        {name: "Jalen Coker", position: "Wide Receiver"},
        {name: "Xavier Leggette", position: "Wide Receiver"},
        {name: "David Moore", position: "Wide Receiver"},
        {name: "Adam Thielen", position: "Wide Receiver"},
        {name: "Feleipe Franks", position: "Tight End"},
        {name: "Ja'Tavion Sanders", position: "Tight End"},
        {name: "Tommy Tremble", position: "Tight End"},
        {name: "Brady Christensen", position: "Guard"},
        {name: "Robert Hunt", position: "Guard"},
        {name: "Damien Lewis", position: "Guard"},
        {name: "Cade Mays", position: "Guard"},
        {name: "Chandler Zavala", position: "Guard"},
        {name: "Ikem Ekwonu", position: "Offensive Tackle"},
        {name: "Jarrett Kingston", position: "Offensive Tackle"},
        {name: "Taylor Moton", position: "Offensive Tackle"},
        {name: "Yosh Nijman", position: "Offensive Tackle"},
        {name: "Jonathan Harris", position: "Defensive End"},
        {name: "LaBryan Ray", position: "Defensive End"},
        {name: "A'Shawn Robinson", position: "Defensive End"},
        {name: "Jaden Crumedy", position: "Defensive Tackle"},
        {name: "Shy Tuttle", position: "Defensive Tackle"},
        {name: "DeShawn Williams", position: "Defensive Tackle"},
        {name: "Claudin Cherelus", position: "Linebacker"},
        {name: "Jadeveon Clowney", position: "Linebacker"},
        {name: "Cam Gill", position: "Linebacker"},
        {name: "Charles Harris", position: "Linebacker"},
        {name: "Thomas Incoom", position: "Linebacker"},
        {name: "Josey Jewell", position: "Linebacker"},
        {name: "DJ Johnson", position: "Linebacker"},
        {name: "Jon Rhattigan", position: "Linebacker"},
        {name: "Trevin Wallace", position: "Linebacker"},
        {name: "D.J. Wonnum", position: "Linebacker"},
        {name: "Shemar Bartholomew", position: "Cornerback"},
        {name: "Caleb Farley", position: "Cornerback"},
        {name: "Jaycee Horn", position: "Cornerback"},
        {name: "Dane Jackson", position: "Cornerback"},
        {name: "Michael Jackson", position: "Cornerback"},
        {name: "Lonnie Johnson Jr.", position: "Cornerback"},
        {name: "Chau Smith-Wade", position: "Cornerback"},
        {name: "Sam Franklin Jr.", position: "Safety"},
        {name: "Jordan Fuller", position: "Safety"},
        {name: "Demani Richardson", position: "Safety"},
        {name: "Jammie Robinson", position: "Safety"},
        {name: "Xavier Woods", position: "Safety"}
    ],
    "New Orleans Saints": [
        {name: "Derek Carr", position: "Quarterback"},
    {name: "Jake Haener", position: "Quarterback"},
    {name: "Spencer Rattler", position: "Quarterback"},
    {name: "Alvin Kamara", position: "Running Back"},
    {name: "Jordan Mims", position: "Running Back"},
    {name: "Jamaal Williams", position: "Running Back"},
    {name: "Adam Prentice", position: "Fullback"},
    {name: "Kevin Austin Jr.", position: "Wide Receiver"},
    {name: "Jermaine Jackson", position: "Wide Receiver"},
    {name: "Dante Pettis", position: "Wide Receiver"},
    {name: "Mason Tipton", position: "Wide Receiver"},
    {name: "Marquez Valdes-Scantling", position: "Wide Receiver"},
    {name: "Cedrick Wilson Jr.", position: "Wide Receiver"},
    {name: "Taysom Hill", position: "Tight End"},
    {name: "Dallin Holker", position: "Tight End"},
    {name: "Juwan Johnson", position: "Tight End"},
    {name: "Foster Moreau", position: "Tight End"},
    {name: "Shane Lemieux", position: "Center"},
    {name: "Erik McCoy", position: "Center"},
    {name: "Cesar Ruiz", position: "Guard"},
    {name: "Lucas Patrick", position: "Guard"},
    {name: "Taliese Fuaga", position: "Offensive Tackle"},
    {name: "Trevor Penning", position: "Offensive Tackle"},
    {name: "Nick Saldiveri", position: "Offensive Tackle"},
    {name: "Olisaemeka Udoh", position: "Offensive Tackle"},
    {name: "Landon Young", position: "Offensive Tackle"},
    {name: "Isaiah Foskey", position: "Defensive End"},
    {name: "Carl Granderson", position: "Defensive End"},
    {name: "Cameron Jordan", position: "Defensive End"},
    {name: "Payton Turner", position: "Defensive End"},
    {name: "Chase Young", position: "Defensive Tackle"},
    {name: "Khristian Boyd", position: "Defensive Tackle"},
    {name: "Bryan Bresee", position: "Defensive Tackle"},
    {name: "John Ridgeway III", position: "Defensive Tackle"},
    {name: "Khalen Saunders", position: "Defensive Tackle"},
    {name: "Nathan Shepherd", position: "Defensive Tackle"},
    {name: "Demario Davis", position: "Linebacker"},
    {name: "Jaylan Ford", position: "Linebacker"},
    {name: "Willie Gay", position: "Linebacker"},
    {name: "D'Marco Jackson", position: "Linebacker"},
    {name: "Anfernee Orji", position: "Linebacker"},
    {name: "Nephi Sewell", position: "Linebacker"},
    {name: "Pete Werner", position: "Linebacker"},
    {name: "Will Harris", position: "Cornerback"},
    {name: "Shemar Jean-Charles", position: "Cornerback"},
    {name: "Kool-Aid McKinstry", position: "Cornerback"},
    {name: "Rico Payton", position: "Cornerback"},
    {name: "Alontae Taylor", position: "Cornerback"},
    {name: "Ugo Amadi", position: "Safety"},
    {name: "Millard Bradford", position: "Safety"},
    {name: "J.T. Gray", position: "Safety"},
    {name: "Jordan Howden", position: "Safety"},
    {name: "Tyrann Mathieu", position: "Safety"}
    ],
    "Tampa Bay Buccaneers": [
        {name: "Baker Mayfield", position: "Quarterback"},
        {name: "Kyle Trask", position: "Quarterback"},
        {name: "Bucky Irving", position: "Running Back"},
        {name: "Sean Tucker", position: "Running Back"},
        {name: "Rachaad White", position: "Running Back"},
        {name: "Mike Evans", position: "Wide Receiver"},
        {name: "Rakim Jarrett", position: "Wide Receiver"},
        {name: "Jalen McMillan", position: "Wide Receiver"},
        {name: "Ryan Miller", position: "Wide Receiver"},
        {name: "Trey Palmer", position: "Wide Receiver"},
        {name: "Sterling Shepard", position: "Wide Receiver"},
        {name: "Devin Culp", position: "Tight End"},
        {name: "Payne Durham", position: "Tight End"},
        {name: "Ko Kieft", position: "Tight End"},
        {name: "Cade Otton", position: "Tight End"},
        {name: "Graham Barton", position: "Center"},
        {name: "Robert Hainsey", position: "Center"},
        {name: "Ben Bredeson", position: "Guard"},
        {name: "Elijah Klein", position: "Guard"},
        {name: "Cody Mauch", position: "Guard"},
        {name: "Royce Newman", position: "Guard"},
        {name: "Luke Goedeke", position: "Offensive Tackle"},
        {name: "Justin Skule", position: "Offensive Tackle"},
        {name: "Tristan Wirfs", position: "Offensive Tackle"},
        {name: "Earnest Brown IV", position: "Defensive End"},
        {name: "William Gholston", position: "Defensive End"},
        {name: "Logan Hall", position: "Defensive End"},
        {name: "C.J. Brewer", position: "Defensive Tackle"},
        {name: "Greg Gaines", position: "Defensive Tackle"},
        {name: "Calijah Kancey", position: "Defensive Tackle"},
        {name: "Vita Vea", position: "Defensive Tackle"},
        {name: "Chris Braswell", position: "Linebacker"},
        {name: "K.J. Britt", position: "Linebacker"},
        {name: "Lavonte David", position: "Linebacker"},
        {name: "Yaya Diaby", position: "Linebacker"},
        {name: "Antonio Grier Jr.", position: "Linebacker"},
        {name: "Anthony Nelson", position: "Linebacker"},
        {name: "Jose Ramirez", position: "Linebacker"},
        {name: "J.J. Russell", position: "Linebacker"},
        {name: "Joe Tryon-Shoyinka", position: "Linebacker"},
        {name: "Tyrek Funderburk", position: "Cornerback"},
        {name: "Troy Hill", position: "Cornerback"},
        {name: "Zyon McCollum", position: "Cornerback"},
        {name: "Tavierre Thomas", position: "Cornerback"},
        {name: "Mike Edwards", position: "Safety"},
        {name: "Josh Hayes", position: "Safety"},
        {name: "Christian Izien", position: "Safety"},
        {name: "Kaevon Merriweather", position: "Safety"},
        {name: "Tykee Smith", position: "Safety"},
        {name: "Jordan Whitehead", position: "Safety"},
        {name: "Antoine Winfield Jr.", position: "Safety"}
    ],
    "Los Angeles Rams": [
        {name: "Stetson Bennett", position: "Quarterback"},
        {name: "Jimmy Garoppolo", position: "Quarterback"},
        {name: "Matthew Stafford", position: "Quarterback"},
        {name: "Blake Corum", position: "Running Back"},
        {name: "Ronnie Rivers", position: "Running Back"},
        {name: "Cody Schrader", position: "Running Back"},
        {name: "Kyren Williams", position: "Running Back"},
        {name: "Tutu Atwell", position: "Wide Receiver"},
        {name: "Tyler Johnson", position: "Wide Receiver"},
        {name: "Cooper Kupp", position: "Wide Receiver"},
        {name: "Puka Nacua", position: "Wide Receiver"},
        {name: "Demarcus Robinson", position: "Wide Receiver"},
        {name: "Xavier Smith", position: "Wide Receiver"},
        {name: "Jordan Whittington", position: "Wide Receiver"},
        {name: "Davis Allen", position: "Tight End"},
        {name: "Hunter Long", position: "Tight End"},
        {name: "Colby Parkinson", position: "Tight End"},
        {name: "Beaux Limmer", position: "Center"},
        {name: "Dylan McMahon", position: "Center"},
        {name: "Steve Avila", position: "Guard"},
        {name: "Justin Dedich", position: "Guard"},
        {name: "Kevin Dotson", position: "Guard"},
        {name: "Jonah Jackson", position: "Guard"},
        {name: "Rob Havenstein", position: "Offensive Tackle"},
        {name: "Alaric Jackson", position: "Offensive Tackle"},
        {name: "Warren McClendon Jr.", position: "Offensive Tackle"},
        {name: "Joe Noteboom", position: "Offensive Tackle"},
        {name: "Desjuan Johnson", position: "Defensive End"},
        {name: "Jonah Williams", position: "Defensive End"},
        {name: "Bobby Brown III", position: "Defensive Tackle"},
        {name: "Tyler Davis", position: "Defensive Tackle"},
        {name: "Braden Fiske", position: "Defensive Tackle"},
        {name: "Neville Gallimore", position: "Defensive Tackle"},
        {name: "Kobie Turner", position: "Linebacker"},
        {name: "Nick Hampton", position: "Linebacker"},
        {name: "Michael Hoecht", position: "Linebacker"},
        {name: "Jacob Hummel", position: "Linebacker"},
        {name: "Brennan Jackson", position: "Linebacker"},
        {name: "Christian Rozeboom", position: "Linebacker"},
        {name: "Omar Speights", position: "Linebacker"},
        {name: "Jared Verse", position: "Linebacker"},
        {name: "Byron Young", position: "Linebacker"},
        {name: "Cobie Durant", position: "Cornerback"},
        {name: "Josh Wallace", position: "Cornerback"},
        {name: "Darious Williams", position: "Cornerback"},
        {name: "Ahkello Witherspoon", position: "Cornerback"},
        {name: "Charles Woods", position: "Cornerback"},
        {name: "Karmen Curl", position: "Safety"},
        {name: "Karmen Kinchens", position: "Safety"},
        {name: "Quentin Lake", position: "Safety"},
        {name: "Jaylen McCollough", position: "Safety"}
    ],
    "San Francisco 49ers": [
        {name: "Brandon Allen", position: "Quarterback"},
        {name: "Joshua Dobbs", position: "Quarterback"},
        {name: "Brock Purdy", position: "Quarterback"},
        {name: "Isaac Guerendo", position: "Running Back"},
        {name: "Jordan Mason", position: "Running Back"},
        {name: "Christian McCaffrey", position: "Running Back"},
        {name: "Kyle Juszczyk", position: "Fullback"},
        {name: "Ronnie Bell", position: "Wide Receiver"},
        {name: "Chris Conley", position: "Wide Receiver"},
        {name: "Jacob Cowing", position: "Wide Receiver"},
        {name: "Jauan Jennings", position: "Wide Receiver"},
        {name: "Ricky Pearsall", position: "Wide Receiver"},
        {name: "Deebo Samuel Sr.", position: "Wide Receiver"},
        {name: "George Kittle", position: "Tight End"},
        {name: "Eric Saubert", position: "Tight End"},
        {name: "Jake Tonges", position: "Tight End"},
        {name: "Brayden Willis", position: "Tight End"},
        {name: "Jake Brendel", position: "Center"},
        {name: "Aaron Banks", position: "Guard"},
        {name: "Ben Bartch", position: "Guard"},
        {name: "Jaylon Moore", position: "Guard"},
        {name: "Dominick Puni", position: "Guard"},
        {name: "Spencer Burford", position: "Offensive Tackle"},
        {name: "Colton McKivitz", position: "Offensive Tackle"},
        {name: "Trent Williams", position: "Offensive Tackle"},
        {name: "Nick Zakelj", position: "Offensive Tackle"},
        {name: "Robert Beal Jr.", position: "Defensive End"},
        {name: "Nick Bosa", position: "Defensive End"},
        {name: "Leonard Floyd", position: "Defensive End"},
        {name: "Yetur Gross-Matos", position: "Defensive End"},
        {name: "Evan Anderson", position: "Defensive Tackle"},
        {name: "Maliek Collins", position: "Defensive Tackle"},
        {name: "Kalie Davis", position: "Defensive Tackle"},
        {name: "Khalil Davis", position: "Defensive Tackle"},
        {name: "Jordan Elliott", position: "Defensive Tackle"},
        {name: "Kevin Givens", position: "Defensive Tackle"},
        {name: "Sam Okuayinonu", position: "Defensive Tackle"},
        {name: "Tatum Bethune", position: "Linebacker"},
        {name: "De'Vondre Campbell", position: "Linebacker"},
        {name: "Demetrius Flannigan-Fowles", position: "Linebacker"},
        {name: "Fred Warner", position: "Linebacker"},
        {name: "Dee Winters", position: "Linebacker"},
        {name: "Renardo Green", position: "Cornerback"},
        {name: "Deommodore Lenoir", position: "Cornerback"},
        {name: "Nick McCloud", position: "Cornerback"},
        {name: "Charvarius Ward", position: "Cornerback"},
        {name: "Rock Ya-Sin", position: "Cornerback"},
        {name: "Isaac Yiadom", position: "Cornerback"},
        {name: "Ji'Ayir Brown", position: "Safety"},
        {name: "Tashaun Gipson Sr.", position: "Safety"},
        {name: "Malik Mustapha", position: "Safety"},
        {name: "George Odum", position: "Safety"}
    ],
    "Seattle Seahawks": [
        {name: "Sam Howell", position: "Quarterback"},
        {name: "Geno Smith", position: "Quarterback"},
        {name: "Zach Charbonnet", position: "Running Back"},
        {name: "Kenny McIntosh", position: "Running Back"},
        {name: "Kenneth Walker III", position: "Running Back"},
        {name: "Jake Bobo", position: "Wide Receiver"},
        {name: "Tyler Lockett", position: "Wide Receiver"},
        {name: "DK Metcalf", position: "Wide Receiver"},
        {name: "Laviska Shenault Jr.", position: "Wide Receiver"},
        {name: "Jaxon Smith-Njigba", position: "Wide Receiver"},
        {name: "Cody White", position: "Wide Receiver"},
        {name: "Dareke Young", position: "Wide Receiver"},
        {name: "AJ Barner", position: "Tight End"},
        {name: "Pharaoh Brown", position: "Tight End"},
        {name: "Noah Fant", position: "Tight End"},
        {name: "N'Keal Harry", position: "Tight End"},
        {name: "Tyler Mabry", position: "Tight End"},
        {name: "Brady Russell", position: "Tight End"},
        {name: "Olu Oluwatimi", position: "Center"},
        {name: "Anthony Bradford", position: "Guard"},
        {name: "Christian Haynes", position: "Guard"},
        {name: "Laken Tomlinson", position: "Guard"},
        {name: "Charles Cross", position: "Offensive Tackle"},
        {name: "Michael Jerrell", position: "Offensive Tackle"},
        {name: "Sataoa Laumea", position: "Offensive Tackle"},
        {name: "Abraham Lucas", position: "Offensive Tackle"},
        {name: "Jalen Sundell", position: "Offensive Tackle"},
        {name: "Myles Adams", position: "Defensive End"},
        {name: "Dre'Mont Jones", position: "Defensive End"},
        {name: "Mike Morris", position: "Defensive End"},
        {name: "Leonard Williams", position: "Defensive Tackle"},
        {name: "Johnathan Hankins", position: "Defensive Tackle"},
        {name: "Byron Murphy II", position: "Defensive Tackle"},
        {name: "Jarren Reed", position: "Defensive Tackle"},
        {name: "Roy Robertson-Harris", position: "Defensive Tackle"},
        {name: "Trevis Gipson", position: "Linebacker"},
        {name: "Derick Hall", position: "Linebacker"},
        {name: "Ernest Jones IV", position: "Linebacker"},
        {name: "Tyrice Knight", position: "Linebacker"},
        {name: "Boye Mafe", position: "Linebacker"},
        {name: "Patrick O'Connell", position: "Linebacker"},
        {name: "Josh Ross", position: "Linebacker"},
        {name: "Drake Thomas", position: "Linebacker"},
        {name: "Tre Brown", position: "Cornerback"},
        {name: "Coby Bryant", position: "Cornerback"},
        {name: "Josh Jobe", position: "Cornerback"},
        {name: "Nehemiah Pritchett", position: "Cornerback"},
        {name: "Dee Williams", position: "Cornerback"},
        {name: "Devon Witherspoon", position: "Cornerback"},
        {name: "Riq Woolen", position: "Cornerback"},
        {name: "Julian Love", position: "Safety"},
        {name: "Ty Okada", position: "Safety"},
        {name: "Jerrick Reed II", position: "Safety"}
    ]
}