const nhlPlayerData = {
    "Boston Bruins": [
        { name: "Johnny Beecher", position: "Center" },
    { name: "Charlie Coyle", position: "Center" },
    { name: "Trent Frederic", position: "Center" },
    { name: "Morgan Geekie", position: "Center" },
    { name: "Tyler Johnson", position: "Center" },
    { name: "Mark Kastelic", position: "Center" },
    { name: "Elias Lindholm", position: "Center" },
    { name: "Georgii Merkulov", position: "Center" },
    { name: "Pavel Zacha", position: "Center" },
    { name: "Cole Koepke", position: "Left Wing" },
    { name: "Brad Marchand", position: "Left Wing" },
    { name: "Jeffrey Viel", position: "Left Wing" },
    { name: "Justin Brazeau", position: "Right Wing" },
    { name: "David Pastrnak", position: "Right Wing" },
    { name: "Brandon Carlo", position: "Defense" },
    { name: "Hampus Lindholm", position: "Defense" },
    { name: "Mason Lohrei", position: "Defense" },
    { name: "Charlie McAvoy", position: "Defense" },
    { name: "Jordan Oesterle", position: "Defense" },
    { name: "Andrew Peeke", position: "Defense" },
    { name: "Alec Regula", position: "Defense" },
    { name: "Parker Wotherspoon", position: "Defense" },
    { name: "Nikita Zadorov", position: "Defense" },
    { name: "Joonas Korpisalo", position: "Goalie" },
    { name: "Jeremy Swayman", position: "Goalie" }
    ],
    "Buffalo Sabres" : [
        { name: "Dylan Cozens", position: "Center" },
    { name: "Peyton Krebs", position: "Center" },
    { name: "Jiri Kulich", position: "Center" },
    { name: "Sam Lafferty", position: "Center" },
    { name: "Ryan McLeod", position: "Center" },
    { name: "Zach Benson", position: "Left Wing" },
    { name: "Ty Cheveldayoff", position: "Left Wing" },
    { name: "Jordan Greenway", position: "Left Wing" },
    { name: "Beck Malenstyn", position: "Left Wing" },
    { name: "Jason Zucker", position: "Left Wing" },
    { name: "Nicolas Aube-Kubel", position: "Right Wing" },
    { name: "JJ Peterka", position: "Right Wing" },
    { name: "Jack Quinn", position: "Right Wing" },
    { name: "Isak Rosen", position: "Right Wing" },
    { name: "Lukas Rousek", position: "Right Wing" },
    { name: "Tage Thompson", position: "Right Wing" },
    { name: "Alex Tuch", position: "Right Wing" },
    { name: "Jacob Bryson", position: "Defense" },
    { name: "Bowen Byram", position: "Defense" },
    { name: "Kale Clague", position: "Defense" },
    { name: "Connor Clifton", position: "Defense" },
    { name: "Rasmus Dahlin", position: "Defense" },
    { name: "Dennis Gilbert", position: "Defense" },
    { name: "Henri Jokiharju", position: "Defense" },
    { name: "Owen Power", position: "Defense" },
    { name: "Mattias Samuelsson", position: "Defense" },
    { name: "Ukko-Pekka Luukkonen", position: "Goalie" },
    { name: "James Reimer", position: "Goalie" }
    ],
    "Detroit Red Wings" : [
        { name: "Andrew Copp", position: "Center" },
    { name: "Marco Kasper", position: "Center" },
    { name: "Dylan Larkin", position: "Center" },
    { name: "Tyler Motte", position: "Center" },
    { name: "Michael Rasmussen", position: "Center" },
    { name: "Joe Veleno", position: "Center" },
    { name: "J.T. Compher", position: "Left Wing" },
    { name: "Lucas Raymond", position: "Left Wing" },
    { name: "Jonatan Berggren", position: "Right Wing" },
    { name: "Alex DeBrincat", position: "Right Wing" },
    { name: "Christian Fischer", position: "Right Wing" },
    { name: "Patrick Kane", position: "Right Wing" },
    { name: "Vladimir Tarasenko", position: "Right Wing" },
    { name: "Ben Chiarot", position: "Defense" },
    { name: "Simon Edvinsson", position: "Defense" },
    { name: "Justin Holl", position: "Defense" },
    { name: "Albert Johansson", position: "Defense" },
    { name: "Jeff Petry", position: "Defense" },
    { name: "Moritz Seider", position: "Defense" },
    { name: "Alex Lyon", position: "Goalie" },
    { name: "Cam Talbot", position: "Goalie" }
    ],
    "Florida Panthers": [
    { name: "Aleksander Barkov", position: "Center" },
    { name: "Sam Bennett", position: "Center" },
    { name: "Jesper Boqvist", position: "Center" },
    { name: "Anton Lundell", position: "Center" },
    { name: "Eetu Luostarinen", position: "Center" },
    { name: "Sam Reinhart", position: "Center" },
    { name: "Evan Rodrigues", position: "Center" },
    { name: "Carter Verhaeghe", position: "Center" },
    { name: "Jonah Gadjovich", position: "Left Wing" },
    { name: "A.J. Greer", position: "Left Wing" },
    { name: "Tomas Nosek", position: "Left Wing" },
    { name: "Hunter St. Martin", position: "Left Wing" },
    { name: "Matthew Tkachuk", position: "Left Wing" },
    { name: "MacKenzie Entwistle", position: "Right Wing" },
    { name: "Mackie Samoskevich", position: "Right Wing" },
    { name: "Uvis Balinskis", position: "Defense" },
    { name: "Adam Boqvist", position: "Defense" },
    { name: "Aaron Ekblad", position: "Defense" },
    { name: "Gustav Forsling", position: "Defense" },
    { name: "Dmitry Kulikov", position: "Defense" },
    { name: "Niko Mikkola", position: "Defense" },
    { name: "Nate Schmidt", position: "Defense" },
    { name: "Sergei Bobrovsky", position: "Goalie" },
    { name: "Spencer Knight", position: "Goalie" }
    ],
    "Montreal Canadiens": [
    { name: "Kirby Dach", position: "Center" },
    { name: "Christian Dvorak", position: "Center" },
    { name: "Jake Evans", position: "Center" },
    { name: "Alex Newhook", position: "Center" },
    { name: "Nick Suzuki", position: "Center" },
    { name: "Lucas Condotta", position: "Left Wing" },
    { name: "Emil Heineman", position: "Left Wing" },
    { name: "Patrik Laine", position: "Left Wing" },
    { name: "Michael Pezzetta", position: "Left Wing" },
    { name: "Juraj Slafkovsky", position: "Left Wing" },
    { name: "Josh Anderson", position: "Right Wing" },
    { name: "Joel Armia", position: "Right Wing" },
    { name: "Cole Caufield", position: "Right Wing" },
    { name: "Brendan Gallagher", position: "Right Wing" },
    { name: "Justin Barron", position: "Defense" },
    { name: "Kaiden Guhle", position: "Defense" },
    { name: "Lane Hutson", position: "Defense" },
    { name: "Gustav Lindstrom", position: "Defense" },
    { name: "Mike Matheson", position: "Defense" },
    { name: "David Savard", position: "Defense" },
    { name: "Jayden Struble", position: "Defense" },
    { name: "Tyler Wotherspoon", position: "Defense" },
    { name: "Arber Xhekaj", position: "Defense" },
    { name: "Sam Montembeault", position: "Goalie" },
    { name: "Cayden Primeau", position: "Goalie" }
],
"Ottawa Senators": [
    { name: "Nick Cousins", position: "Center" },
    { name: "Adam Gaudette", position: "Center" },
    { name: "Noah Gregor", position: "Center" },
    { name: "Ridly Greig", position: "Center" },
    { name: "Josh Norris", position: "Center" },
    { name: "Shane Pinto", position: "Center" },
    { name: "Tim Stutzle", position: "Center" },
    { name: "David Perron", position: "Left Wing" },
    { name: "Brady Tkachuk", position: "Left Wing" },
    { name: "Michael Amadio", position: "Right Wing" },
    { name: "Drake Batherson", position: "Right Wing" },
    { name: "Claude Giroux", position: "Right Wing" },
    { name: "Zack MacEwen", position: "Right Wing" },
    { name: "Jacob Bernard-Docker", position: "Defense" },
    { name: "Thomas Chabot", position: "Defense" },
    { name: "Travis Hamonic", position: "Defense" },
    { name: "Nick Jensen", position: "Defense" },
    { name: "Tyler Kleven", position: "Defense" },
    { name: "Jake Sanderson", position: "Defense" },
    { name: "Artem Zub", position: "Defense" },
    { name: "Anton Forsberg", position: "Goalie" },
    { name: "Linus Ullmark", position: "Goalie" }
],
"Tampa Bay Lightning": [
    { name: "Anthony Cirelli", position: "Center" },
    { name: "Michael Eyssimont", position: "Center" },
    { name: "Conor Geekie", position: "Center" },
    { name: "Luke Glendening", position: "Center" },
    { name: "Gage Goncalves", position: "Center" },
    { name: "Jake Guentzel", position: "Center" },
    { name: "Brayden Point", position: "Center" },
    { name: "Zemgus Girgensons", position: "Left Wing" },
    { name: "Brandon Hagel", position: "Left Wing" },
    { name: "Nick Paul", position: "Left Wing" },
    { name: "Cam Atkinson", position: "Right Wing" },
    { name: "Mitchell Chaffee", position: "Right Wing" },
    { name: "Nikita Kucherov", position: "Right Wing" },
    { name: "Erik Cernak", position: "Defense" },
    { name: "Victor Hedman", position: "Defense" },
    { name: "Emil Lilleberg", position: "Defense" },
    { name: "Ryan McDonagh", position: "Defense" },
    { name: "Janis Moser", position: "Defense" },
    { name: "Nick Perbix", position: "Defense" },
    { name: "Darren Raddysh", position: "Defense" },
    { name: "Jonas Johansson", position: "Goalie" },
    { name: "Andrei Vasilevskiy", position: "Goalie" }
],
"Toronto Maple Leafs": [
    { name: "Connor Dewar", position: "Center" },
    { name: "Max Domi", position: "Center" },
    { name: "Calle Jarnkrok", position: "Center" },
    { name: "David Kampf", position: "Center" },
    { name: "Auston Matthews", position: "Center" },
    { name: "Bobby McMann", position: "Center" },
    { name: "Fraser Minten", position: "Center" },
    { name: "Alex Steeves", position: "Center" },
    { name: "John Tavares", position: "Center" },
    { name: "Matthew Knies", position: "Left Wing" },
    { name: "Max Pacioretty", position: "Left Wing" },
    { name: "Nicholas Robertson", position: "Left Wing" },
    { name: "Pontus Holmberg", position: "Right Wing" },
    { name: "Mitch Marner", position: "Right Wing" },
    { name: "William Nylander", position: "Right Wing" },
    { name: "Ryan Reaves", position: "Right Wing" },
    { name: "Simon Benoit", position: "Defense" },
    { name: "Oliver Ekman-Larsson", position: "Defense" },
    { name: "Jani Hakanpaa", position: "Defense" },
    { name: "Steven Lorentz", position: "Defense" },
    { name: "Jake McCabe", position: "Defense" },
    { name: "Dakota Mermis", position: "Defense" },
    { name: "Morgan Rielly", position: "Defense" },
    { name: "Chris Tanev", position: "Defense" },
    { name: "Conor Timmins", position: "Defense" },
    { name: "Cade Webber", position: "Defense" },
    { name: "Anthony Stolarz", position: "Goalie" },
    { name: "Joseph Woll", position: "Goalie" }
],
"Chicago Blackhawks": [
    { name: "Connor Bedard", position: "Center" },
    { name: "Jason Dickinson", position: "Center" },
    { name: "Ryan Donato", position: "Center" },
    { name: "Philipp Kurashev", position: "Center" },
    { name: "Frank Nazar", position: "Center" },
    { name: "Craig Smith", position: "Center" },
    { name: "Tyler Bertuzzi", position: "Left Wing" },
    { name: "Nick Foligno", position: "Left Wing" },
    { name: "Taylor Hall", position: "Left Wing" },
    { name: "Pat Maroon", position: "Left Wing" },
    { name: "Lukas Reichel", position: "Left Wing" },
    { name: "Landon Slaggert", position: "Left Wing" },
    { name: "Teuvo Teravainen", position: "Left Wing" },
    { name: "Joey Anderson", position: "Right Wing" },
    { name: "Ilya Mikheyev", position: "Right Wing" },
    { name: "Nolan Allan", position: "Defense" },
    { name: "TJ Brodie", position: "Defense" },
    { name: "Louis Crevier", position: "Defense" },
    { name: "Seth Jones", position: "Defense" },
    { name: "Wyatt Kaiser", position: "Defense" },
    { name: "Alec Martinez", position: "Defense" },
    { name: "Connor Murphy", position: "Defense" },
    { name: "Austin Strand", position: "Defense" },
    { name: "Alex Vlasic", position: "Defense" },
    { name: "Laurent Brossoit", position: "Goalie" },
    { name: "Drew Commesso", position: "Goalie" },
    { name: "Petr Mrazek", position: "Goalie" },
    { name: "Arvid Soderblom", position: "Goalie" }
],
"Colorado Avalanche": [
    { name: "Ross Colton", position: "Center" },
    { name: "Maximillian Curran", position: "Center" },
    { name: "Ivan Ivan", position: "Center" },
    { name: "Nathan MacKinnon", position: "Center" },
    { name: "Jayson Megna", position: "Center" },
    { name: "Casey Mittelstadt", position: "Center" },
    { name: "Matt Stienburg", position: "Center" },
    { name: "T.J. Tynan", position: "Center" },
    { name: "Jonathan Drouin", position: "Left Wing" },
    { name: "Parker Kelly", position: "Left Wing" },
    { name: "Joel Kiviranta", position: "Left Wing" },
    { name: "Gabriel Landeskog", position: "Left Wing" },
    { name: "Artturi Lehkonen", position: "Left Wing" },
    { name: "Miles Wood", position: "Left Wing" },
    { name: "Nikolai Kovalenko", position: "Right Wing" },
    { name: "Valeri Nichushkin", position: "Right Wing" },
    { name: "Logan O'Connor", position: "Right Wing" },
    { name: "Mikko Rantanen", position: "Right Wing" },
    { name: "Calvin de Haan", position: "Defense" },
    { name: "Samuel Girard", position: "Defense" },
    { name: "Oliver Kylington", position: "Defense" },
    { name: "John Ludvig", position: "Defense" },
    { name: "Cale Makar", position: "Defense" },
    { name: "Sam Malinski", position: "Defense" },
    { name: "Josh Manson", position: "Defense" },
    { name: "Keaton Middleton", position: "Defense" },
    { name: "Devon Toews", position: "Defense" },
    { name: "Justus Annunen", position: "Goalie" },
    { name: "Alexandar Georgiev", position: "Goalie" },
    { name: "Kevin Mandolese", position: "Goalie" }
],
"Dallas Stars": [
    { name: "Oskar Back", position: "Center" },
    { name: "Colin Blackwell", position: "Center" },
    { name: "Mavrik Bourque", position: "Center" },
    { name: "Matt Duchene", position: "Center" },
    { name: "Roope Hintz", position: "Center" },
    { name: "Wyatt Johnston", position: "Center" },
    { name: "Tyler Seguin", position: "Center" },
    { name: "Logan Stankoven", position: "Center" },
    { name: "Sam Steel", position: "Center" },
    { name: "Jamie Benn", position: "Left Wing" },
    { name: "Mason Marchment", position: "Left Wing" },
    { name: "Jason Robertson", position: "Left Wing" },
    { name: "Evgenii Dadonov", position: "Right Wing" },
    { name: "Matt Dumba", position: "Defense" },
    { name: "Thomas Harley", position: "Defense" },
    { name: "Miro Heiskanen", position: "Defense" },
    { name: "Esa Lindell", position: "Defense" },
    { name: "Nils Lundkvist", position: "Defense" },
    { name: "Ilya Lyubushkin", position: "Defense" },
    { name: "Brendan Smith", position: "Defense" },
    { name: "Casey DeSmith", position: "Goalie" },
    { name: "Jake Oettinger", position: "Goalie" }
],
"Minnesota Wild": [
    { name: "Joel Eriksson Ek", position: "Center" },
    { name: "Frederick Gaudreau", position: "Center" },
    { name: "Ben Jones", position: "Center" },
    { name: "Marat Khusnutdinov", position: "Center" },
    { name: "Jakub Lauko", position: "Center" },
    { name: "Marco Rossi", position: "Center" },
    { name: "Devin Shore", position: "Center" },
    { name: "Yakov Trenin", position: "Center" },
    { name: "Matt Boldy", position: "Left Wing" },
    { name: "Marcus Foligno", position: "Left Wing" },
    { name: "Marcus Johansson", position: "Left Wing" },
    { name: "Kirill Kaprizov", position: "Left Wing" },
    { name: "Luke Toporowski", position: "Left Wing" },
    { name: "Ryan Hartman", position: "Right Wing" },
    { name: "Mats Zuccarello", position: "Right Wing" },
    { name: "Zach Bogosian", position: "Defense" },
    { name: "Jonas Brodin", position: "Defense" },
    { name: "Declan Chisholm", position: "Defense" },
    { name: "Cameron Crotty", position: "Defense" },
    { name: "Brock Faber", position: "Defense" },
    { name: "Jon Merrill", position: "Defense" },
    { name: "Jake Middleton", position: "Defense" },
    { name: "Jared Spurgeon", position: "Defense" },
    { name: "Marc-Andre Fleury", position: "Goalie" },
    { name: "Troy Grosenick", position: "Goalie" },
    { name: "Filip Gustavsson", position: "Goalie" }
],
"Nashville Predators": [
    { name: "Mark Jankowski", position: "Center" },
    { name: "Tommy Novak", position: "Center" },
    { name: "Gustav Nyquist", position: "Center" },
    { name: "Ryan O'Reilly", position: "Center" },
    { name: "Juuso Parssinen", position: "Center" },
    { name: "Colton Sissons", position: "Center" },
    { name: "Steven Stamkos", position: "Center" },
    { name: "Philip Tomasino", position: "Center" },
    { name: "Ozzy Wiesblatt", position: "Center" },
    { name: "Filip Forsberg", position: "Left Wing" },
    { name: "Zachary L'Heureux", position: "Left Wing" },
    { name: "Cole Smith", position: "Left Wing" },
    { name: "Luke Evangelista", position: "Right Wing" },
    { name: "Jonathan Marchessault", position: "Right Wing" },
    { name: "Michael McCarron", position: "Right Wing" },
    { name: "Austin Roest", position: "Right Wing" },
    { name: "Nick Blankenburg", position: "Defense" },
    { name: "Alexandre Carrier", position: "Defense" },
    { name: "Marc Del Gaizo", position: "Defense" },
    { name: "Roman Josi", position: "Defense" },
    { name: "Jeremy Lauzon", position: "Defense" },
    { name: "Tanner Molendyk", position: "Defense" },
    { name: "Luke Schenn", position: "Defense" },
    { name: "Brady Skjei", position: "Defense" },
    { name: "Spencer Stastney", position: "Defense" },
    { name: "Juuse Saros", position: "Goalie" },
    { name: "Scott Wedgewood", position: "Goalie" }
],
"St. Louis Blues": [
    { name: "Zack Bolduc", position: "Center" },
    { name: "Radek Faksa", position: "Center" },
    { name: "Jordan Kyrou", position: "Center" },
    { name: "Brayden Schenn", position: "Center" },
    { name: "Oskar Sundqvist", position: "Center" },
    { name: "Alexandre Texier", position: "Center" },
    { name: "Robert Thomas", position: "Center" },
    { name: "Pavel Buchnevich", position: "Left Wing" },
    { name: "Dylan Holloway", position: "Left Wing" },
    { name: "Jake Neighbours", position: "Left Wing" },
    { name: "Brandon Saad", position: "Left Wing" },
    { name: "Nathan Walker", position: "Left Wing" },
    { name: "Mathieu Joseph", position: "Right Wing" },
    { name: "Simon Robertson", position: "Right Wing" },
    { name: "Alexey Toropchenko", position: "Right Wing" },
    { name: "Philip Broberg", position: "Defense" },
    { name: "Justin Faulk", position: "Defense" },
    { name: "Pierre-Olivier Joseph", position: "Defense" },
    { name: "Matthew Kessel", position: "Defense" },
    { name: "Nick Leddy", position: "Defense" },
    { name: "Colton Parayko", position: "Defense" },
    { name: "Scott Perunovich", position: "Defense" },
    { name: "Corey Schueneman", position: "Defense" },
    { name: "Ryan Suter", position: "Defense" },
    { name: "Jordan Binnington", position: "Goalie" },
    { name: "Joel Hofer", position: "Goalie" }
],
"Utah Hockey Club": [
    { name: "Nick Bjugstad", position: "Center" },
    { name: "Logan Cooley", position: "Center" },
    { name: "Barrett Hayton", position: "Center" },
    { name: "Alexander Kerfoot", position: "Center" },
    { name: "Jack McBain", position: "Center" },
    { name: "Liam O'Brien", position: "Center" },
    { name: "Nick Schmaltz", position: "Center" },
    { name: "Kevin Stenlund", position: "Center" },
    { name: "Michael Carcone", position: "Left Wing" },
    { name: "Lawson Crouse", position: "Left Wing" },
    { name: "Matias Maccelli", position: "Left Wing" },
    { name: "Dylan Guenther", position: "Right Wing" },
    { name: "Clayton Keller", position: "Right Wing" },
    { name: "Kailer Yamamoto", position: "Right Wing" },
    { name: "Robert Bortuzzo", position: "Defense" },
    { name: "Ian Cole", position: "Defense" },
    { name: "Sean Durzi", position: "Defense" },
    { name: "Michael Kesselring", position: "Defense" },
    { name: "Vladislav Kolyachonok", position: "Defense" },
    { name: "Maveric Lamoureux", position: "Defense" },
    { name: "Olli Maatta", position: "Defense" },
    { name: "Mikhail Sergachev", position: "Defense" },
    { name: "Juuso Valimaki", position: "Defense" },
    { name: "Connor Ingram", position: "Goalie" },
    { name: "Karel Vejmelka", position: "Goalie" }
],
"Winnipeg Jets": [
    { name: "Mason Appleton", position: "Center" },
    { name: "Morgan Barron", position: "Center" },
    { name: "David Gustafsson", position: "Center" },
    { name: "Rasmus Kupari", position: "Center" },
    { name: "Adam Lowry", position: "Center" },
    { name: "Vladislav Namestnikov", position: "Center" },
    { name: "Cole Perfetti", position: "Center" },
    { name: "Mark Scheifele", position: "Center" },
    { name: "Gabriel Vilardi", position: "Center" },
    { name: "Kyle Connor", position: "Left Wing" },
    { name: "Nikolaj Ehlers", position: "Left Wing" },
    { name: "Alex Iafallo", position: "Left Wing" },
    { name: "Nino Niederreiter", position: "Right Wing" },
    { name: "Dylan Coghlan", position: "Defense" },
    { name: "Dylan DeMelo", position: "Defense" },
    { name: "Haydn Fleury", position: "Defense" },
    { name: "Colin Miller", position: "Defense" },
    { name: "Josh Morrissey", position: "Defense" },
    { name: "Neal Pionk", position: "Defense" },
    { name: "Dylan Samberg", position: "Defense" },
    { name: "Logan Stanley", position: "Defense" },
    { name: "Eric Comrie", position: "Goalie" },
    { name: "Connor Hellebuyck", position: "Goalie" }
],
"Carolina Hurricanes": [
    { name: "Sebastian Aho", position: "Center" },
    { name: "Jack Drury", position: "Center" },
    { name: "Seth Jarvis", position: "Center" },
    { name: "Tyson Jost", position: "Center" },
    { name: "Jesperi Kotkaniemi", position: "Center" },
    { name: "Martin Necas", position: "Center" },
    { name: "Jack Roslovic", position: "Center" },
    { name: "Jordan Staal", position: "Center" },
    { name: "William Carrier", position: "Left Wing" },
    { name: "Jordan Martinook", position: "Left Wing" },
    { name: "Eric Robinson", position: "Left Wing" },
    { name: "Jackson Blake", position: "Right Wing" },
    { name: "Jesper Fast", position: "Right Wing" },
    { name: "Andrei Svechnikov", position: "Right Wing" },
    { name: "Brent Burns", position: "Defense" },
    { name: "Jalen Chatfield", position: "Defense" },
    { name: "Shayne Gostisbehere", position: "Defense" },
    { name: "Dmitry Orlov", position: "Defense" },
    { name: "Jacob Slavin", position: "Defense" },
    { name: "Ty Smith", position: "Defense" },
    { name: "Sean Walker", position: "Defense" },
    { name: "Frederik Andersen", position: "Goalie" },
    { name: "Pyotr Kochetkov", position: "Goalie" },
    { name: "Spencer Martin", position: "Goalie" }
],
"Columbus Blue Jackets": [
    { name: "Zachary Aston-Reese", position: "Center" },
    { name: "Adam Fantilli", position: "Center" },
    { name: "Boone Jenner", position: "Center" },
    { name: "Sean Kuraly", position: "Center" },
    { name: "Cayden Lindstrom", position: "Center" },
    { name: "Sean Monahan", position: "Center" },
    { name: "Cole Sillinger", position: "Center" },
    { name: "Mikael Pyyhtia", position: "Left Wing" },
    { name: "James van Riemsdyk", position: "Left Wing" },
    { name: "Dmitri Voronkov", position: "Left Wing" },
    { name: "Yegor Chinakhov", position: "Right Wing" },
    { name: "Justin Danforth", position: "Right Wing" },
    { name: "Jordan Dumais", position: "Right Wing" },
    { name: "Kevin Labanc", position: "Right Wing" },
    { name: "Kirill Marchenko", position: "Right Wing" },
    { name: "Mathieu Olivier", position: "Right Wing" },
    { name: "Jake Christiansen", position: "Defense" },
    { name: "Dante Fabbro", position: "Defense" },
    { name: "Erik Gudbranson", position: "Defense" },
    { name: "Jordan Harris", position: "Defense" },
    { name: "David Jiricek", position: "Defense" },
    { name: "Jack Johnson", position: "Defense" },
    { name: "Ivan Provorov", position: "Defense" },
    { name: "Damon Severson", position: "Defense" },
    { name: "Zach Werenski", position: "Defense" },
    { name: "Elvis Merzlikins", position: "Goalie" },
    { name: "Daniil Tarasov", position: "Goalie" }
],
"New Jersey Devils": [
    { name: "Shane Bowers", position: "Center" },
    { name: "Paul Cotter", position: "Center" },
    { name: "Justin Dowling", position: "Center" },
    { name: "Nico Hischier", position: "Center" },
    { name: "Jack Hughes", position: "Center" },
    { name: "Curtis Lazar", position: "Center" },
    { name: "Dawson Mercer", position: "Center" },
    { name: "Jesper Bratt", position: "Left Wing" },
    { name: "Nolan Foote", position: "Left Wing" },
    { name: "Erik Haula", position: "Left Wing" },
    { name: "Kurtis MacDermid", position: "Left Wing" },
    { name: "Ondrej Palat", position: "Left Wing" },
    { name: "Tomas Tatar", position: "Left Wing" },
    { name: "Nathan Bastian", position: "Right Wing" },
    { name: "Timo Meier", position: "Right Wing" },
    { name: "Stefan Noesen", position: "Right Wing" },
    { name: "Nick DeSimone", position: "Defense" },
    { name: "Brenden Dillon", position: "Defense" },
    { name: "Dougie Hamilton", position: "Defense" },
    { name: "Santeri Hatakka", position: "Defense" },
    { name: "Luke Hughes", position: "Defense" },
    { name: "Johnathan Kovacevic", position: "Defense" },
    { name: "Daniil Misyul", position: "Defense" },
    { name: "Brett Pesce", position: "Defense" },
    { name: "Jonas Siegenthaler", position: "Defense" },
    { name: "Brendan Smith", position: "Defense" },
    { name: "Topias Vilen", position: "Defense" },
    { name: "Jake Allen", position: "Goalie" },
    { name: "Jacob Markstrom", position: "Goalie" }
],
"New York Islanders": [
    { name: "Mathew Barzal", position: "Center" },
    { name: "Casey Cizikas", position: "Center" },
    { name: "Bo Horvat", position: "Center" },
    { name: "Kyle MacLean", position: "Center" },
    { name: "Brock Nelson", position: "Center" },
    { name: "Jean-Gabriel Pageau", position: "Center" },
    { name: "Kyle Palmieri", position: "Center" },
    { name: "Anthony Duclair", position: "Left Wing" },
    { name: "Pierre Engvall", position: "Left Wing" },
    { name: "Anders Lee", position: "Left Wing" },
    { name: "Matt Martin", position: "Left Wing" },
    { name: "Hudson Fasching", position: "Right Wing" },
    { name: "Simon Holmstrom", position: "Right Wing" },
    { name: "Maxim Tsyplakov", position: "Right Wing" },
    { name: "Oliver Wahlstrom", position: "Right Wing" },
    { name: "Dennis Cholowski", position: "Defense" },
    { name: "Noah Dobson", position: "Defense" },
    { name: "Isaiah George", position: "Defense" },
    { name: "Grant Hutton", position: "Defense" },
    { name: "Scott Mayfield", position: "Defense" },
    { name: "Travis Mitchell", position: "Defense" },
    { name: "Adam Pelech", position: "Defense" },
    { name: "Ryan Pulock", position: "Defense" },
    { name: "Mike Reilly", position: "Defense" },
    { name: "Alexander Romanov", position: "Defense" },
    { name: "Ilya Sorokin", position: "Goalie" },
    { name: "Semyon Varlamov", position: "Goalie" }
],
"New York Rangers": [
    { name: "Jonny Brodzinski", position: "Center" },
    { name: "Sam Carrick", position: "Center" },
    { name: "Filip Chytil", position: "Center" },
    { name: "Adam Edstrom", position: "Center" },
    { name: "Jake Leschyshyn", position: "Center" },
    { name: "Vincent Trocheck", position: "Center" },
    { name: "Mika Zibanejad", position: "Center" },
    { name: "Anton Blidh", position: "Left Wing" },
    { name: "Will Cuylle", position: "Left Wing" },
    { name: "Chris Kreider", position: "Left Wing" },
    { name: "Alexis Lafreniere", position: "Left Wing" },
    { name: "Artemi Panarin", position: "Left Wing" },
    { name: "Adam Sykora", position: "Left Wing" },
    { name: "Jimmy Vesey", position: "Left Wing" },
    { name: "Kaapo Kakko", position: "Right Wing" },
    { name: "Reilly Smith", position: "Right Wing" },
    { name: "Adam Fox", position: "Defense" },
    { name: "Ben Harpur", position: "Defense" },
    { name: "Zac Jones", position: "Defense" },
    { name: "Ryan Lindgren", position: "Defense" },
    { name: "K'Andre Miller", position: "Defense" },
    { name: "Matthew Robertson", position: "Defense" },
    { name: "Chad Ruhwedel", position: "Defense" },
    { name: "Braden Schneider", position: "Defense" },
    { name: "Jacob Trouba", position: "Defense" },
    { name: "Jonathan Quick", position: "Goalie" },
    { name: "Igor Shesterkin", position: "Goalie" }
],
"Philadelphia Flyers": [
    { name: "Sean Couturier", position: "Center" },
    { name: "Morgan Frost", position: "Center" },
    { name: "Rhett Gardner", position: "Center" },
    { name: "Jacob Gaucher", position: "Center" },
    { name: "Scott Laughton", position: "Center" },
    { name: "Ryan Poehling", position: "Center" },
    { name: "Anthony Richard", position: "Center" },
    { name: "Noah Cates", position: "Left Wing" },
    { name: "Nicolas Deslauriers", position: "Left Wing" },
    { name: "Joel Farabee", position: "Left Wing" },
    { name: "Bobby Brink", position: "Right Wing" },
    { name: "Tyson Foerster", position: "Right Wing" },
    { name: "Alexis Gendron", position: "Right Wing" },
    { name: "Garnet Hathaway", position: "Right Wing" },
    { name: "Travis Konecny", position: "Right Wing" },
    { name: "Matvei Michkov", position: "Right Wing" },
    { name: "Owen Tippett", position: "Right Wing" },
    { name: "Emil Andrae", position: "Defense" },
    { name: "Jamie Drysdale", position: "Defense" },
    { name: "Spencer Gill", position: "Defense" },
    { name: "Helge Grans", position: "Defense" },
    { name: "Erik Johnson", position: "Defense" },
    { name: "Rasmus Ristolainen", position: "Defense" },
    { name: "Travis Sanheim", position: "Defense" },
    { name: "Nick Seeler", position: "Defense" },
    { name: "Cam York", position: "Defense" },
    { name: "Egor Zamula", position: "Defense" },
    { name: "Samuel Ersson", position: "Goalie" },
    { name: "Ivan Fedotov", position: "Goalie" },
    { name: "Aleksei Kolosov", position: "Goalie" }
],
"Pittsburgh Penguins": [
    { name: "Noel Acciari", position: "Center" },
    { name: "Sidney Crosby", position: "Center" },
    { name: "Cody Glass", position: "Center" },
    { name: "Blake Lizotte", position: "Center" },
    { name: "Evgeni Malkin", position: "Center" },
    { name: "Vasily Ponomarev", position: "Center" },
    { name: "Sam Poulin", position: "Center" },
    { name: "Anthony Beauvillier", position: "Left Wing" },
    { name: "Michael Bunting", position: "Left Wing" },
    { name: "Tanner Howe", position: "Left Wing" },
    { name: "Matt Nieto", position: "Left Wing" },
    { name: "Drew O'Connor", position: "Left Wing" },
    { name: "Kevin Hayes", position: "Right Wing" },
    { name: "Jesse Puljujarvi", position: "Right Wing" },
    { name: "Valtteri Puustinen", position: "Right Wing" },
    { name: "Rickard Rakell", position: "Right Wing" },
    { name: "Bryan Rust", position: "Right Wing" },
    { name: "Ryan Graves", position: "Defense" },
    { name: "Matt Grzelcyk", position: "Defense" },
    { name: "Erik Karlsson", position: "Defense" },
    { name: "Kris Letang", position: "Defense" },
    { name: "Marcus Pettersson", position: "Defense" },
    { name: "Owen Pickering", position: "Defense" },
    { name: "Ryan Shea", position: "Defense" },
    { name: "Jack St. Ivany", position: "Defense" },
    { name: "Tristan Jarry", position: "Goalie" },
    { name: "Alex Nedeljkovic", position: "Goalie" }
],
"Washington Capitals": [
    { name: "Nicklas Backstrom", position: "Center" },
    { name: "Pierre-Luc Dubois", position: "Center" },
    { name: "Lars Eller", position: "Center" },
    { name: "Hendrix Lapierre", position: "Center" },
    { name: "Connor McMichael", position: "Center" },
    { name: "Aliaksei Protas", position: "Center" },
    { name: "Michael Sgarbossa", position: "Center" },
    { name: "Dylan Strome", position: "Center" },
    { name: "Andrew Mangiapane", position: "Left Wing" },
    { name: "Sonny Milano", position: "Left Wing" },
    { name: "Ivan Miroshnichenko", position: "Left Wing" },
    { name: "Alex Ovechkin", position: "Left Wing" },
    { name: "Jakub Vrana", position: "Left Wing" },
    { name: "Nic Dowd", position: "Right Wing" },
    { name: "Brandon Duhaime", position: "Right Wing" },
    { name: "T.J. Oshie", position: "Right Wing" },
    { name: "Taylor Raddysh", position: "Right Wing" },
    { name: "Tom Wilson", position: "Right Wing" },
    { name: "Alexander Alexeyev", position: "Defense" },
    { name: "John Carlson", position: "Defense" },
    { name: "Jakob Chychrun", position: "Defense" },
    { name: "Martin Fehervary", position: "Defense" },
    { name: "Dylan McIlrath", position: "Defense" },
    { name: "Matt Roy", position: "Defense" },
    { name: "Rasmus Sandin", position: "Defense" },
    { name: "Trevor van Riemsdyk", position: "Defense" },
    { name: "Charlie Lindgren", position: "Goalie" },
    { name: "Logan Thompson", position: "Goalie" }
],
"Anaheim Ducks": [
    { name: "Leo Carlsson", position: "Center" },
    { name: "Robby Fabbri", position: "Center" },
    { name: "Jansen Harkins", position: "Center" },
    { name: "Isaac Lundestrom", position: "Center" },
    { name: "Mason McTavish", position: "Center" },
    { name: "Ryan Strome", position: "Center" },
    { name: "Trevor Zegras", position: "Center" },
    { name: "Cutter Gauthier", position: "Left Wing" },
    { name: "Ross Johnston", position: "Left Wing" },
    { name: "Alex Killorn", position: "Left Wing" },
    { name: "Brock McGinn", position: "Left Wing" },
    { name: "Sam Colangelo", position: "Right Wing" },
    { name: "Brett Leason", position: "Right Wing" },
    { name: "Troy Terry", position: "Right Wing" },
    { name: "Frank Vatrano", position: "Right Wing" },
    { name: "Brian Dumoulin", position: "Defense" },
    { name: "Cam Fowler", position: "Defense" },
    { name: "Radko Gudas", position: "Defense" },
    { name: "Drew Helleson", position: "Defense" },
    { name: "Tyson Hinds", position: "Defense" },
    { name: "Jackson LaCombe", position: "Defense" },
    { name: "Pavel Mintyukov", position: "Defense" },
    { name: "Urho Vaakanainen", position: "Defense" },
    { name: "Olen Zellweger", position: "Defense" },
    { name: "Lukas Dostal", position: "Goalie" },
    { name: "John Gibson", position: "Goalie" }
],
"Calgary Flames": [
    { name: "Mikael Backlund", position: "Center" },
    { name: "Blake Coleman", position: "Center" },
    { name: "Jonathan Huberdeau", position: "Center" },
    { name: "Nazem Kadri", position: "Center" },
    { name: "Martin Pospisil", position: "Center" },
    { name: "Kevin Rooney", position: "Center" },
    { name: "Yegor Sharangovich", position: "Center" },
    { name: "Connor Zary", position: "Center" },
    { name: "Dryden Hunt", position: "Left Wing" },
    { name: "Andrei Kuzmenko", position: "Left Wing" },
    { name: "Ryan Lomberg", position: "Left Wing" },
    { name: "Matt Coronato", position: "Right Wing" },
    { name: "Adam Klapka", position: "Right Wing" },
    { name: "Anthony Mantha", position: "Right Wing" },
    { name: "Rasmus Andersson", position: "Defense" },
    { name: "Kevin Bahl", position: "Defense" },
    { name: "Tyson Barrie", position: "Defense" },
    { name: "Jake Bean", position: "Defense" },
    { name: "Joel Hanley", position: "Defense" },
    { name: "Daniil Miromanov", position: "Defense" },
    { name: "Brayden Pachal", position: "Defense" },
    { name: "MacKenzie Weegar", position: "Defense" },
    { name: "Dan Vladar", position: "Goalie" },
    { name: "Dustin Wolf", position: "Goalie" }
],
"Edmonton Oilers": [
    { name: "Leon Draisaitl", position: "Center" },
    { name: "Adam Henrique", position: "Center" },
    { name: "Mattias Janmark", position: "Center" },
    { name: "Connor McDavid", position: "Center" },
    { name: "Ryan Nugent-Hopkins", position: "Center" },
    { name: "Derek Ryan", position: "Center" },
    { name: "Jeff Skinner", position: "Center" },
    { name: "Viktor Arvidsson", position: "Left Wing" },
    { name: "Zach Hyman", position: "Left Wing" },
    { name: "Connor Brown", position: "Right Wing" },
    { name: "Kasperi Kapanen", position: "Right Wing" },
    { name: "Corey Perry", position: "Right Wing" },
    { name: "Vasily Podkolzin", position: "Right Wing" },
    { name: "Evan Bouchard", position: "Defense" },
    { name: "Josh Brown", position: "Defense" },
    { name: "Travis Dermott", position: "Defense" },
    { name: "Mattias Ekholm", position: "Defense" },
    { name: "Ty Emberson", position: "Defense" },
    { name: "Brett Kulak", position: "Defense" },
    { name: "Darnell Nurse", position: "Defense" },
    { name: "Troy Stecher", position: "Defense" },
    { name: "Calvin Pickard", position: "Goalie" },
    { name: "Stuart Skinner", position: "Goalie" }
],
"Los Angeles Kings": [
    { name: "Phillip Danault", position: "Center" },
    { name: "Samuel Helenius", position: "Center" },
    { name: "Anze Kopitar", position: "Center" },
    { name: "Trevor Lewis", position: "Center" },
    { name: "Aki Thomas", position: "Center" },
    { name: "Alex Turcotte", position: "Center" },
    { name: "Kevin Fiala", position: "Left Wing" },
    { name: "Warren Foegele", position: "Left Wing" },
    { name: "Tanner Jeannot", position: "Left Wing" },
    { name: "Trevor Moore", position: "Left Wing" },
    { name: "Quinton Byfield", position: "Right Wing" },
    { name: "Arthur Kaliyev", position: "Right Wing" },
    { name: "Adrian Kempe", position: "Right Wing" },
    { name: "Alex Laferriere", position: "Right Wing" },
    { name: "Mikey Anderson", position: "Defense" },
    { name: "Kyle Burroughs", position: "Defense" },
    { name: "Brandt Clarke", position: "Defense" },
    { name: "Drew Doughty", position: "Defense" },
    { name: "Joel Edmundson", position: "Defense" },
    { name: "Andreas Englund", position: "Defense" },
    { name: "Vladislav Gavrikov", position: "Defense" },
    { name: "Caleb Jones", position: "Defense" },
    { name: "Jacob Moverare", position: "Defense" },
    { name: "Jordan Spence", position: "Defense" },
    { name: "Darcy Kuemper", position: "Goalie" },
    { name: "Erik Portillo", position: "Goalie" },
    { name: "David Rittich", position: "Goalie" }
],
"San Jose Sharks": [
    { name: "Thomas Bordeleau", position: "Center" },
    { name: "Macklin Celebrini", position: "Center" },
    { name: "Logan Couture", position: "Center" },
    { name: "Ty Dellandrea", position: "Center" },
    { name: "Barclay Goodrow", position: "Center" },
    { name: "Mikael Granlund", position: "Center" },
    { name: "Klim Kostin", position: "Center" },
    { name: "Luke Kunin", position: "Center" },
    { name: "Andrew Poturalski", position: "Center" },
    { name: "Will Smith", position: "Center" },
    { name: "Nico Sturm", position: "Center" },
    { name: "Alex Wennberg", position: "Center" },
    { name: "Igor Chernyshov", position: "Left_Wing" },
    { name: "William Eklund", position: "Left_Wing" },
    { name: "Fabian Zetterlund", position: "Left_Wing" },
    { name: "Carl Grundstrom", position: "Right_Wing" },
    { name: "Giovanni Smith", position: "Right_Wing" },
    { name: "Tyler Toffoli", position: "Right_Wing" },
    { name: "Cody Ceci", position: "Defense" },
    { name: "Mario Ferraro", position: "Defense" },
    { name: "Timothy Liljegren", position: "Defense" },
    { name: "Shakir Mukhamadullin", position: "Defense" },
    { name: "Jan Rutta", position: "Defense" },
    { name: "Jack Thompson", position: "Defense" },
    { name: "Henry Thrun", position: "Defense" },
    { name: "Marc-Edouard Vlasic", position: "Defense" },
    { name: "Jake Walman", position: "Defense" },
    { name: "Yaroslav Askarov", position: "Goalie" },
    { name: "Mackenzie Blackwood", position: "Goalie" },
    { name: "Vitek Vanecek", position: "Goalie" }
  ],
  "Seattle Kraken": [
    { name: "Matty Beniers", position: "Center" },
    { name: "Yanni Gourde", position: "Center" },
    { name: "Ben Meyers", position: "Center" },
    { name: "Jaden Schwartz", position: "Center" },
    { name: "Chandler Stephenson", position: "Center" },
    { name: "Shane Wright", position: "Center" },
    { name: "Andre Burakovsky", position: "Left_Wing" },
    { name: "Tye Kartye", position: "Left_Wing" },
    { name: "Jared McCann", position: "Left_Wing" },
    { name: "Carson Rehkopf", position: "Left_Wing" },
    { name: "Brandon Tanev", position: "Left_Wing" },
    { name: "Oliver Bjorkstrand", position: "Right_Wing" },
    { name: "Jordan Eberle", position: "Right_Wing" },
    { name: "Daniel Sprong", position: "Right_Wing" },
    { name: "Eeli Tolvanen", position: "Right_Wing" },
    { name: "Will Borgen", position: "Defense" },
    { name: "Vince Dunn", position: "Defense" },
    { name: "Ryker Evans", position: "Defense" },
    { name: "Adam Larsson", position: "Defense" },
    { name: "Joshua Mahura", position: "Defense" },
    { name: "Brandon Montour", position: "Defense" },
    { name: "Jamie Oleksiak", position: "Defense" },
    { name: "Caden Price", position: "Defense" },
    { name: "Joey Daccord", position: "Goalie" },
    { name: "Philipp Grubauer", position: "Goalie" }
  ],
  "Vancouver Canucks": [
    { name: "Teddy Blueger", position: "Center" },
    { name: "Dakota Joshua", position: "Center" },
    { name: "J.T. Miller", position: "Center" },
    { name: "Elias Pettersson", position: "Center" },
    { name: "Atu Raty", position: "Center" },
    { name: "Pius Suter", position: "Center" },
    { name: "Arshdeep Bains", position: "Left Wing" },
    { name: "Jake DeBrusk", position: "Left Wing" },
    { name: "Danton Heinen", position: "Left Wing" },
    { name: "Nils Hoglander", position: "Left Wing" },
    { name: "Kiefer Sherwood", position: "Left Wing" },
    { name: "Brock Boeser", position: "Right Wing" },
    { name: "Conor Garland", position: "Right Wing" },
    { name: "Jonathan Lekkerimaki", position: "Right Wing" },
    { name: "Erik Brannstrom", position: "Defense" },
    { name: "Vincent Desharnais", position: "Defense" },
    { name: "Derek Forbort", position: "Defense" },
    { name: "Mark Friedman", position: "Defense" },
    { name: "Filip Hronek", position: "Defense" },
    { name: "Quinn Hughes", position: "Defense" },
    { name: "Noah Juulsen", position: "Defense" },
    { name: "Tyler Myers", position: "Defense" },
    { name: "Elias N. Pettersson", position: "Defense" },
    { name: "Carson Soucy", position: "Defense" },
    { name: "Thatcher Demko", position: "Goalie" },
    { name: "Kevin Lankinen", position: "Goalie" },
    { name: "Arturs Silovs", position: "Goalie" }
  ],
  "Vegas Golden Knights": [
    { name: "Ivan Barbashev", position: "Center" },
    { name: "Brendan Brisson", position: "Center" },
    { name: "Callahan Burke", position: "Center" },
    { name: "Jack Eichel", position: "Center" },
    { name: "Tomas Hertl", position: "Center" },
    { name: "Brett Howden", position: "Center" },
    { name: "William Karlsson", position: "Center" },
    { name: "Nicolas Roy", position: "Center" },
    { name: "Pavel Dorofeyev", position: "Left Wing" },
    { name: "Mason Morelli", position: "Left Wing" },
    { name: "Tanner Pearson", position: "Left Wing" },
    { name: "Alexander Holtz", position: "Right Wing" },
    { name: "Keegan Kolesar", position: "Right Wing" },
    { name: "Jonas Rondbjerg", position: "Right Wing" },
    { name: "Cole Schwindt", position: "Right Wing" },
    { name: "Mark Stone", position: "Right Wing" },
    { name: "Nicolas Hague", position: "Defense" },
    { name: "Noah Hanifin", position: "Defense" },
    { name: "Ben Hutton", position: "Defense" },
    { name: "Kaedan Korczak", position: "Defense" },
    { name: "Brayden McNabb", position: "Defense" },
    { name: "Alex Pietrangelo", position: "Defense" },
    { name: "Shea Theodore", position: "Defense" },
    { name: "Zach Whitecloud", position: "Defense" },
    { name: "Adin Hill", position: "Goalie" },
    { name: "Ilya Samsonov", position: "Goalie" }
  ]

}