const premierPlayerData = {
    "AFC Bournemouth": [
    { name: "Kepa Arrizabalaga", position: "Goalkeeper" },
    { name: "William Dennis", position: "Goalkeeper" },
    { name: "Mark Travers", position: "Goalkeeper" },
    { name: "Dean Huijsen", position: "Defender" },
    { name: "Milos Kerkez", position: "Defender" },
    { name: "Marcos Senesi", position: "Defender" },
    { name: "Adam Smith", position: "Defender" },
    { name: "Julián Araujo", position: "Defender" },
    { name: "James Hill", position: "Defender" },
    { name: "Illia Zabarnyi", position: "Defender" },
    { name: "Max Aarons", position: "Defender" },
    { name: "Lewis Cook", position: "Midfielder" },
    { name: "David Brooks", position: "Midfielder" },
    { name: "Alex Scott", position: "Midfielder" },
    { name: "Ryan Christie", position: "Midfielder" },
    { name: "Tyler Adams", position: "Midfielder" },
    { name: "Marcus Tavernier", position: "Midfielder" },
    { name: "Philip Billing", position: "Midfielder" },
    { name: "Evanilson", position: "Forward" },
    { name: "Dango Ouattara", position: "Forward" },
    { name: "Luis Sinisterra", position: "Forward" },
    { name: "Justin Kluivert", position: "Forward" },
    { name: "Antoine Semenyo", position: "Forward" },
    { name: "Enes Ünal", position: "Forward" }
    ],
    "Arsenal" : [
        { name: "David Raya", position: "Goalkeeper" },
    { name: "Neto", position: "Goalkeeper" },
    { name: "Tommy Sefford", position: "Goalkeeper" },
    { name: "Alexei Rojas", position: "Goalkeeper" },
    { name: "Jack Porter", position: "Goalkeeper" },
    { name: "William Saliba", position: "Defender" },
    { name: "Kieran Tierney", position: "Defender" },
    { name: "Ben White", position: "Defender" },
    { name: "Gabriel Magalhães", position: "Defender" },
    { name: "Jurrien Timber", position: "Defender" },
    { name: "Jakub Kiwior", position: "Defender" },
    { name: "Oleksandr Zinchenko", position: "Defender" },
    { name: "Takehiro Tomiyasu", position: "Defender" },
    { name: "Riccardo Calafiori", position: "Defender" },
    { name: "Maldini Kacurri", position: "Defender" },
    { name: "Zane Monlouis", position: "Defender" },
    { name: "Josh Nichols", position: "Defender" },
    { name: "Josh Robinson", position: "Defender" },
    { name: "Ayden Heaven", position: "Defender" },
    { name: "Thomas Partey", position: "Midfielder" },
    { name: "Martin Ødegaard", position: "Midfielder" },
    { name: "Jorginho", position: "Midfielder" },
    { name: "Mikel Merino", position: "Midfielder" },
    { name: "Kai Havertz", position: "Midfielder" },
    { name: "Declan Rice", position: "Midfielder" },
    { name: "Myles Lewis-Skelly", position: "Midfielder" },
    { name: "Ethan Nwaneri", position: "Midfielder" },
    { name: "Salah-Eddine Oulad M'Hand", position: "Midfielder" },
    { name: "Bukayo Saka", position: "Forward" },
    { name: "Gabriel Jesus", position: "Forward" },
    { name: "Gabriel Martinelli", position: "Forward" },
    { name: "Leandro Trossard", position: "Forward" },
    { name: "Raheem Sterling", position: "Forward" },
    { name: "Nathan Butler-Oyedeji", position: "Forward" },
    { name: "Ismael Kabia", position: "Forward" }
    ],
    "Aston Villa" : [
        { name: "Joe Gauci", position: "Goalkeeper" },
    { name: "Emiliano Martinez", position: "Goalkeeper" },
    { name: "Robin Olsen", position: "Goalkeeper" },
    { name: "Oliwier Zych", position: "Goalkeeper" },
    { name: "Matty Cash", position: "Defender" },
    { name: "Diego Carlos", position: "Defender" },
    { name: "Ezri Konsa", position: "Defender" },
    { name: "Tyrone Mings", position: "Defender" },
    { name: "Lucas Digne", position: "Defender" },
    { name: "Pau Torres", position: "Defender" },
    { name: "Kosta Nedeljkovic", position: "Defender" },
    { name: "Ian Maatsen", position: "Defender" },
    { name: "Lamar Bogarde", position: "Defender" },
    { name: "Kortney Hause", position: "Defender" },
    { name: "Triston Rowe", position: "Defender" },
    { name: "Sil Swinkels", position: "Defender" },
    { name: "Travis Patterson", position: "Defender" },
    { name: "Thierry Katsukunya", position: "Defender" },
    { name: "Ross Barkley", position: "Midfielder" },
    { name: "John McGinn", position: "Midfielder" },
    { name: "Youri Tielemans", position: "Midfielder" },
    { name: "Emiliano Buendía", position: "Midfielder" },
    { name: "Amadou Onana", position: "Midfielder" },
    { name: "Leon Bailey", position: "Midfielder" },
    { name: "Jacob Ramsey", position: "Midfielder" },
    { name: "Boubacar Kamara", position: "Midfielder" },
    { name: "Aidan Borland", position: "Midfielder" },
    { name: "Jamalden Jimoh", position: "Midfielder" },
    { name: "Ben Broggio", position: "Midfielder" },
    { name: "Jhon Durán", position: "Forward" },
    { name: "Ollie Watkins", position: "Forward" },
    { name: "Jaden Philogene", position: "Forward" },
    { name: "Morgan Rogers", position: "Forward" },
    { name: "Kadan Young", position: "Forward" },
    { name: "Kobei Moore", position: "Forward" }
    ],
    "Brentford" : [
        { name: "Mark Flekken", position: "Goalkeeper" },
    { name: "Hakon Rafn Valdimarsson", position: "Goalkeeper" },
    { name: "Matthew Cox", position: "Goalkeeper" },
    { name: "Aaron Hickey", position: "Defender" },
    { name: "Rico Henry", position: "Defender" },
    { name: "Sepp van den Berg", position: "Defender" },
    { name: "Ethan Pinnock", position: "Defender" },
    { name: "Ben Mee", position: "Defender" },
    { name: "Kristoffer Ajer", position: "Defender" },
    { name: "Jayden Meghoma", position: "Defender" },
    { name: "Nathan Collins", position: "Defender" },
    { name: "Mads Roerslev", position: "Defender" },
    { name: "Kim Ji-Soo", position: "Defender" },
    { name: "Christian Norgaard", position: "Midfielder" },
    { name: "Kevin Schade", position: "Midfielder" },
    { name: "Mathias Jensen", position: "Midfielder" },
    { name: "Josh Dasilva", position: "Midfielder" },
    { name: "Yoane Wissa", position: "Midfielder" },
    { name: "Fabio Carvalho", position: "Midfielder" },
    { name: "Yehor Yarmoliuk", position: "Midfielder" },
    { name: "Bryan Mbeumo", position: "Midfielder" },
    { name: "Mikkel Damsgaard", position: "Midfielder" },
    { name: "Yunus Konak", position: "Midfielder" },
    { name: "Vitaly Janelt", position: "Midfielder" },
    { name: "Ryan Trevitt", position: "Midfielder" },
    { name: "Paris Maghoma", position: "Midfielder" },
    { name: "Tony Yogo", position: "Forward" },
    { name: "Thiago", position: "Forward" },
    { name: "Keane Lewis-Potter", position: "Forward" },
    { name: "Gustavo Nunes", position: "Forward" },
    { name: "Iwan Morgan", position: "Forward" }
    ], 
    "Brighton & Hove Albion" : [
        { name: "Bart Verbruggen", position: "Goalkeeper" },
    { name: "Jason Steele", position: "Goalkeeper" },
    { name: "Killian Cahill", position: "Goalkeeper" },
    { name: "Tariq Lamptey", position: "Defender" },
    { name: "Igor Julio", position: "Defender" },
    { name: "Adam Webster", position: "Defender" },
    { name: "Lewis Dunk", position: "Defender" },
    { name: "Jan Paul van Hecke", position: "Defender" },
    { name: "Pervis Estupiñán", position: "Defender" },
    { name: "Joël Veltman", position: "Defender" },
    { name: "Imari Samuels", position: "Defender" },
    { name: "Ed Turns", position: "Defender" },
    { name: "James Milner", position: "Midfielder" },
    { name: "Solly March", position: "Midfielder" },
    { name: "Brajan Gruda", position: "Midfielder" },
    { name: "Julio Enciso", position: "Midfielder" },
    { name: "Jakub Moder", position: "Midfielder" },
    { name: "Carlos Baleba", position: "Midfielder" },
    { name: "Kaoru Mitoma", position: "Midfielder" },
    { name: "Ferdi Kadıoğlu", position: "Midfielder" },
    { name: "Yasin Ayari", position: "Midfielder" },
    { name: "Mats Wieffer", position: "Midfielder" },
    { name: "Cameron Peupion", position: "Midfielder" },
    { name: "Matt O'Riley", position: "Midfielder" },
    { name: "Jack Hinshelwood", position: "Midfielder" },
    { name: "João Pedro", position: "Forward" },
    { name: "Simon Adingra", position: "Forward" },
    { name: "Georginio Rutter", position: "Forward" },
    { name: "Yankuba Minteh", position: "Forward" },
    { name: "Danny Welbeck", position: "Forward" },
    { name: "Evan Ferguson", position: "Forward" }
    ],
    "Chelsea" : [
        { name: "Robert Sánchez", position: "Goalkeeper" },
    { name: "Filip Jørgensen", position: "Goalkeeper" },
    { name: "Marcus Bettinelli", position: "Goalkeeper" },
    { name: "Lucas Bergström", position: "Goalkeeper" },
    { name: "Max Merrick", position: "Goalkeeper" },
    { name: "Axel Disasi", position: "Defender" },
    { name: "Marc Cucurella", position: "Defender" },
    { name: "Tosin Adarabioyo", position: "Defender" },
    { name: "Benoît Badiashile", position: "Defender" },
    { name: "Levi Colwill", position: "Defender" },
    { name: "Ben Chilwell", position: "Defender" },
    { name: "Reece James", position: "Defender" },
    { name: "Malo Gusto", position: "Defender" },
    { name: "Wesley Fofana", position: "Defender" },
    { name: "Josh Acheampong", position: "Defender" },
    { name: "Enzo Fernández", position: "Midfielder" },
    { name: "Mykhailo Mudryk", position: "Midfielder" },
    { name: "Carney Chukwuemeka", position: "Midfielder" },
    { name: "Cole Palmer", position: "Midfielder" },
    { name: "Kiernan Dewsbury-Hall", position: "Midfielder" },
    { name: "Moisés Caicedo", position: "Midfielder" },
    { name: "Cesare Casadei", position: "Midfielder" },
    { name: "Kiano Dyer", position: "Midfielder" },
    { name: "Renato Veiga", position: "Midfielder" },
    { name: "Romeo Lavia", position: "Midfielder" },
    { name: "Samuel Rak-Sakyi", position: "Midfielder" },
    { name: "Pedro Neto", position: "Forward" },
    { name: "Noni Madueke", position: "Forward" },
    { name: "João Félix", position: "Forward" },
    { name: "Nicolas Jackson", position: "Forward" },
    { name: "Christopher Nkunku", position: "Forward" },
    { name: "Jadon Sancho", position: "Forward" },
    { name: "Tyrique George", position: "Forward" },
    { name: "Deivid Washington", position: "Forward" },
    { name: "Omari Kellyman", position: "Forward" },
    { name: "Marc Guéhi", position: "Forward" },
    { name: "Shim Mheuka", position: "Forward" }
    ],
    "Crystal Palace" : [
        { name: "Dean Henderson", position: "Goalkeeper" },
    { name: "Matt Turner", position: "Goalkeeper" },
    { name: "Remi Matthews", position: "Goalkeeper" },
    { name: "Joel Ward", position: "Defender" },
    { name: "Tyrick Mitchell", position: "Defender" },
    { name: "Rob Holding", position: "Defender" },
    { name: "Maxence Lacroix", position: "Defender" },
    { name: "Marc Guéhi", position: "Defender" },
    { name: "Daniel Muñoz", position: "Defender" },
    { name: "Nathaniel Clyne", position: "Defender" },
    { name: "Chris Richards", position: "Defender" },
    { name: "Trevoh Chalobah", position: "Defender" },
    { name: "Chadi Riad", position: "Defender" },
    { name: "Caleb Kporha", position: "Defender" },
    { name: "Jefferson Lerma", position: "Midfielder" },
    { name: "Eberechi Eze", position: "Midfielder" },
    { name: "Jeff Schlupp", position: "Midfielder" },
    { name: "Daichi Kamada", position: "Midfielder" },
    { name: "Will Hughes", position: "Midfielder" },
    { name: "Adam Wharton", position: "Midfielder" },
    { name: "Cheick Doucouré", position: "Midfielder" },
    { name: "Kaden Rodney", position: "Midfielder" },
    { name: "Justin Devenny", position: "Midfielder" },
    { name: "Asher Aghionne", position: "Midfielder" },
    { name: "Ismaïla Sarr", position: "Forward" },
    { name: "Eddie Nketiah", position: "Forward" },
    { name: "Matheus França", position: "Forward" },
    { name: "Jean-Philippe Mateta", position: "Forward" },
    { name: "Franco Umeh-Chibueze", position: "Forward" },
    { name: "Zach Marsh", position: "Forward" }
    ],
    "Everton" : [
        { name: "Jordan Pickford", position: "Goalkeeper" },
    { name: "João Virgínia", position: "Goalkeeper" },
    { name: "Asmir Begović", position: "Goalkeeper" },
    { name: "Nathan Patterson", position: "Defender" },
    { name: "Michael Keane", position: "Defender" },
    { name: "James Tarkowski", position: "Defender" },
    { name: "Jake O'Brien", position: "Defender" },
    { name: "Ashley Young", position: "Defender" },
    { name: "Vitaliy Mykolenko", position: "Defender" },
    { name: "Seamus Coleman", position: "Defender" },
    { name: "Jarrad Branthwaite", position: "Defender" },
    { name: "Bradley Moonan", position: "Defender" },
    { name: "Roman Quintyne", position: "Defender" },
    { name: "Orel Mangala", position: "Midfielder" },
    { name: "Abdoulaye Doucouré", position: "Midfielder" },
    { name: "Idrissa Gueye", position: "Midfielder" },
    { name: "Jesper Lindstrøm", position: "Midfielder" },
    { name: "James Garner", position: "Midfielder" },
    { name: "Tim Iroegbunam", position: "Midfielder" },
    { name: "Harrison Armstrong", position: "Midfielder" },
    { name: "Luke Butterfield", position: "Midfielder" },
    { name: "Owen Barker", position: "Midfielder" },
    { name: "Callum Bates", position: "Midfielder" },
    { name: "Dwight McNeil", position: "Forward" },
    { name: "Dominic Calvert-Lewin", position: "Forward" },
    { name: "Iliman Ndiaye", position: "Forward" },
    { name: "Jack Harrison", position: "Forward" },
    { name: "Beto", position: "Forward" },
    { name: "Youssef Chermiti", position: "Forward" },
    { name: "Armando Broja", position: "Forward" },
    { name: "Martin Sheriff", position: "Forward" }
    ],
    "Fulham" : [
        { name: "Bernd Leno", position: "Goalkeeper" },
    { name: "Steven Benda", position: "Goalkeeper" },
    { name: "Alex Borto", position: "Goalkeeper" },
    { name: "Kenny Tete", position: "Defender" },
    { name: "Calvin Bassey", position: "Defender" },
    { name: "Joachim Andersen", position: "Defender" },
    { name: "Jorge Cuenca", position: "Defender" },
    { name: "Timothy Castagne", position: "Defender" },
    { name: "Issa Diop", position: "Defender" },
    { name: "Antonee Robinson", position: "Defender" },
    { name: "Luc de Fougerolles", position: "Defender" },
    { name: "Harrison Reed", position: "Midfielder" },
    { name: "Harry Wilson", position: "Midfielder" },
    { name: "Tom Cairney", position: "Midfielder" },
    { name: "Sander Berge", position: "Midfielder" },
    { name: "Andreas Pereira", position: "Midfielder" },
    { name: "Sasa Lukic", position: "Midfielder" },
    { name: "Josh King", position: "Midfielder" },
    { name: "Ryan Sessegnon", position: "Midfielder" },
    { name: "Emile Smith Rowe", position: "Midfielder" },
    { name: "Raúl Jiménez", position: "Forward" },
    { name: "Rodrigo Muniz", position: "Forward" },
    { name: "Adama Traoré", position: "Forward" },
    { name: "Carlos Vinícius", position: "Forward" },
    { name: "Alex Iwobi", position: "Forward" },
    { name: "Reiss Nelson", position: "Forward" },
    { name: "Martial Godo", position: "Forward" }
    ],
    "Ipswich Town Squad" : [
        { name: "Aro Muric", position: "Goalkeeper" },
    { name: "Cieran Slicker", position: "Goalkeeper" },
    { name: "Christian Walton", position: "Goalkeeper" },
    { name: "Harrison Clarke", position: "Defender" },
    { name: "Leif Davis", position: "Defender" },
    { name: "Luke Woolfenden", position: "Defender" },
    { name: "Cameron Burgess", position: "Defender" },
    { name: "Ben Johnson", position: "Defender" },
    { name: "Conor Townsend", position: "Defender" },
    { name: "Jacob Greaves", position: "Defender" },
    { name: "Dara O'Shea", position: "Defender" },
    { name: "Axel Tuanzebe", position: "Defender" },
    { name: "Janoi Donacien", position: "Defender" },
    { name: "Sam Morsy", position: "Midfielder" },
    { name: "Kalvin Phillips", position: "Midfielder" },
    { name: "Jens Cajuste", position: "Midfielder" },
    { name: "Jack Taylor", position: "Midfielder" },
    { name: "Sammie Szmodics", position: "Midfielder" },
    { name: "Massimo Luongo", position: "Midfielder" },
    { name: "Wes Burns", position: "Midfielder" },
    { name: "Conor Chaplin", position: "Midfielder" },
    { name: "Ali Ibrahim Al-Hamadi", position: "Forward" },
    { name: "Liam Delap", position: "Forward" },
    { name: "Omari Hutchinson", position: "Forward" },
    { name: "Chiedozie Ogbene", position: "Forward" },
    { name: "George Hirst", position: "Forward" },
    { name: "Nathan Broadhead", position: "Forward" },
    { name: "Jack Clarke", position: "Forward" }
    ],
    "Leicester City" : [
        { name: "Danny Ward", position: "Goalkeeper" },
    { name: "Mads Hermansen", position: "Goalkeeper" },
    { name: "Daniel Iversen", position: "Goalkeeper" },
    { name: "Jakub Stolarczyk", position: "Goalkeeper" },
    { name: "James Justin", position: "Defender" },
    { name: "Wout Faes", position: "Defender" },
    { name: "Conor Coady", position: "Defender" },
    { name: "Caleb Okoli", position: "Defender" },
    { name: "Victor Kristiansen", position: "Defender" },
    { name: "Ricardo Pereira", position: "Defender" },
    { name: "Jannik Vestergaard", position: "Defender" },
    { name: "Luke Thomas", position: "Defender" },
    { name: "Wilfred Ndidi", position: "Midfielder" },
    { name: "Harry Winks", position: "Midfielder" },
    { name: "Bilal El Khannous", position: "Midfielder" },
    { name: "Hamza Choudhury", position: "Midfielder" },
    { name: "Oliver Skipp", position: "Midfielder" },
    { name: "Boubakary Soumaré", position: "Midfielder" },
    { name: "Michael Golding", position: "Midfielder" },
    { name: "Kasey McAteer", position: "Midfielder" },
    { name: "Will Alves", position: "Midfielder" },
    { name: "Facundo Buonanotte", position: "Midfielder" },
    { name: "Fatawu Issahaku", position: "Forward" },
    { name: "Jamie Vardy", position: "Forward" },
    { name: "Stephy Mavididi", position: "Forward" },
    { name: "Bobby De Cordova-Reid", position: "Forward" },
    { name: "Jordan Ayew", position: "Forward" },
    { name: "Patson Daka", position: "Forward" },
    { name: "Odsonne Édouard", position: "Forward" }
    ],
    "Liverpool" : [
        { name: "Alisson Becker", position: "Goalkeeper" },
    { name: "Vitezslav Jaros", position: "Goalkeeper" },
    { name: "Caoimhín Kelleher", position: "Goalkeeper" },
    { name: "Harvey Davies", position: "Goalkeeper" },
    { name: "Joe Gomez", position: "Defender" },
    { name: "Virgil van Dijk", position: "Defender" },
    { name: "Ibrahima Konaté", position: "Defender" },
    { name: "Kostas Tsimikas", position: "Defender" },
    { name: "Andrew Robertson", position: "Defender" },
    { name: "Trent Alexander-Arnold", position: "Defender" },
    { name: "Jarell Quansah", position: "Defender" },
    { name: "Conor Bradley", position: "Defender" },
    { name: "Wataru Endo", position: "Midfielder" },
    { name: "Dominik Szoboszlai", position: "Midfielder" },
    { name: "Alexis Mac Allister", position: "Midfielder" },
    { name: "Curtis Jones", position: "Midfielder" },
    { name: "Harvey Elliott", position: "Midfielder" },
    { name: "Ryan Gravenberch", position: "Midfielder" },
    { name: "Tyler Morton", position: "Midfielder" },
    { name: "Trey Nyoni", position: "Midfielder" },
    { name: "Luis Díaz", position: "Forward" },
    { name: "Darwin Núñez", position: "Forward" },
    { name: "Mohamed Salah", position: "Forward" },
    { name: "Federico Chiesa", position: "Forward" },
    { name: "Cody Gakpo", position: "Forward" },
    { name: "Diogo Jota", position: "Forward" },
    { name: "Ranel Young", position: "Forward" }
    ],
    "Manchester City" : [
        { name: "Stefan Ortega", position: "Goalkeeper" },
    { name: "Ederson", position: "Goalkeeper" },
    { name: "Scott Carson", position: "Goalkeeper" },
    { name: "Kyle Walker", position: "Defender" },
    { name: "Rúben Dias", position: "Defender" },
    { name: "John Stones", position: "Defender" },
    { name: "Nathan Aké", position: "Defender" },
    { name: "Joško Gvardiol", position: "Defender" },
    { name: "Manuel Akanji", position: "Defender" },
    { name: "Kaden Braithwaite", position: "Defender" },
    { name: "Jahmai Simpson-Pusey", position: "Defender" },
    { name: "Rico Lewis", position: "Defender" },
    { name: "Josh Wilson-Esbrand", position: "Defender" },
    { name: "Mateo Kovacic", position: "Midfielder" },
    { name: "Jack Grealish", position: "Midfielder" },
    { name: "Rodri", position: "Midfielder" },
    { name: "Kevin De Bruyne", position: "Midfielder" },
    { name: "Ilkay Gündogan", position: "Midfielder" },
    { name: "Bernardo Silva", position: "Midfielder" },
    { name: "Matheus Nunes", position: "Midfielder" },
    { name: "Phil Foden", position: "Midfielder" },
    { name: "Oscar Bobb", position: "Midfielder" },
    { name: "Jacob Wright", position: "Midfielder" },
    { name: "Nico O'Reilly", position: "Midfielder" },
    { name: "James McAtee", position: "Forward" },
    { name: "Farid Alfa-Ruprecht", position: "Forward" },
    { name: "Erling Haaland", position: "Forward" },
    { name: "Jérémy Doku", position: "Forward" },
    { name: "Savinho", position: "Forward" }
    ],
    "Manchester United" : [
        { name: "Altay Bayindir", position: "Goalkeeper" },
    { name: "Tom Heaton", position: "Goalkeeper" },
    { name: "André Onana", position: "Goalkeeper" },
    { name: "Victor Lindelöf", position: "Defender" },
    { name: "Noussair Mazraoui", position: "Defender" },
    { name: "Matthijs de Ligt", position: "Defender" },
    { name: "Harry Maguire", position: "Defender" },
    { name: "Lisandro Martínez", position: "Defender" },
    { name: "Tyrell Malacia", position: "Defender" },
    { name: "Leny Yoro", position: "Defender" },
    { name: "Diogo Dalot", position: "Defender" },
    { name: "Luke Shaw", position: "Defender" },
    { name: "Jonny Evans", position: "Defender" },
    { name: "Harry Amass", position: "Defender" },
    { name: "Habeeb Ogunneye", position: "Defender" },
    { name: "Mason Mount", position: "Midfielder" },
    { name: "Bruno Fernandes", position: "Midfielder" },
    { name: "Christian Eriksen", position: "Midfielder" },
    { name: "Casemiro", position: "Midfielder" },
    { name: "Manuel Ugarte", position: "Midfielder" },
    { name: "Kobbie Mainoo", position: "Midfielder" },
    { name: "Toby Collyer", position: "Midfielder" },
    { name: "Daniel Gore", position: "Midfielder" },
    { name: "Jack Fletcher", position: "Midfielder" },
    { name: "Jayce Fitzgerald", position: "Midfielder" },
    { name: "Rasmus Højlund", position: "Forward" },
    { name: "Marcus Rashford", position: "Forward" },
    { name: "Joshua Zirkzee", position: "Forward" },
    { name: "Amad", position: "Forward" },
    { name: "Alejandro Garnacho", position: "Forward" },
    { name: "Antony", position: "Forward" },
    { name: "Ethan Wheatley", position: "Forward" }
    ],
    "Newcastle United" : [
        { name: "Martin Dúbravka", position: "Goalkeeper" },
    { name: "Odysseas Vlachodimos", position: "Goalkeeper" },
    { name: "Nick Pope", position: "Goalkeeper" },
    { name: "John Ruddy", position: "Goalkeeper" },
    { name: "Mark Gillespie", position: "Goalkeeper" },
    { name: "Kieran Trippier", position: "Defender" },
    { name: "Sven Botman", position: "Defender" },
    { name: "Fabian Schär", position: "Defender" },
    { name: "Jamaal Lascelles", position: "Defender" },
    { name: "Matt Targett", position: "Defender" },
    { name: "Emil Krafth", position: "Defender" },
    { name: "Lewis Hall", position: "Defender" },
    { name: "Valentino Livramento", position: "Defender" },
    { name: "Lloyd Kelly", position: "Defender" },
    { name: "Dan Burn", position: "Defender" },
    { name: "Alex Murphy", position: "Defender" },
    { name: "Isaac Hayden", position: "Midfielder" },
    { name: "Sandro Tonali", position: "Midfielder" },
    { name: "Harvey Barnes", position: "Midfielder" },
    { name: "Jacob Murphy", position: "Midfielder" },
    { name: "Miguel Almirón", position: "Midfielder" },
    { name: "Joe Willock", position: "Midfielder" },
    { name: "Sean Longstaff", position: "Midfielder" },
    { name: "Bruno Guimarães", position: "Midfielder" },
    { name: "Lewis Miley", position: "Midfielder" },
    { name: "Joelinton", position: "Forward" },
    { name: "Callum Wilson", position: "Forward" },
    { name: "Anthony Gordon", position: "Forward" },
    { name: "Alexander Isak", position: "Forward" },
    { name: "William Ouala", position: "Forward" },
    { name: "Garang Kuol", position: "Forward" }
    ],
    "Nottingham Forest" : [
        { name: "Matz Sels", position: "Goalkeeper" },
    { name: "Carlos Miguel", position: "Goalkeeper" },
    { name: "Morato", position: "Defender" },
    { name: "Murillo", position: "Defender" },
    { name: "Neco Williams", position: "Defender" },
    { name: "Andrew Omobamidele", position: "Defender" },
    { name: "Harry Toffolo", position: "Defender" },
    { name: "Álex Moreno", position: "Defender" },
    { name: "Willy Boly", position: "Defender" },
    { name: "Nikola Milenkovic", position: "Defender" },
    { name: "Ola Aina", position: "Defender" },
    { name: "Zach Abbott", position: "Defender" },
    { name: "Ibrahim Sangaré", position: "Midfielder" },
    { name: "Elliot Anderson", position: "Midfielder" },
    { name: "Morgan Gibbs-White", position: "Midfielder" },
    { name: "Nicolás Domínguez", position: "Midfielder" },
    { name: "James Ward-Prowse", position: "Midfielder" },
    { name: "Ryan Yates", position: "Midfielder" },
    { name: "Danilo", position: "Midfielder" },
    { name: "Ben Perry", position: "Midfielder" },
    { name: "Taiwo Awoniyi", position: "Forward" },
    { name: "Chris Wood", position: "Forward" },
    { name: "Callum Hudson-Odoi", position: "Forward" },
    { name: "Eric Da Silva Moreira", position: "Forward" },
    { name: "Jota Silva", position: "Forward" },
    { name: "Anthony Elanga", position: "Forward" },
    { name: "Ramón Sosa", position: "Forward" },
    { name: "Emmanuel Dennis", position: "Forward" }
    ],
    "Southampton" : [
        { name: "Alex McCarthy", position: "Goalkeeper" },
    { name: "Joe Lumley", position: "Goalkeeper" },
    { name: "Aaron Ramsdale", position: "Goalkeeper" },
    { name: "Gavin Bazunu", position: "Goalkeeper" },
    { name: "Kyle Walker-Peters", position: "Defender" },
    { name: "Ryan Manning", position: "Defender" },
    { name: "Jack Stephens", position: "Defender" },
    { name: "Taylor Harwood-Bellis", position: "Defender" },
    { name: "Ronnie Edwards", position: "Defender" },
    { name: "James Bree", position: "Defender" },
    { name: "Nathan Wood", position: "Defender" },
    { name: "Yukinari Sugawara", position: "Defender" },
    { name: "Charlie Taylor", position: "Defender" },
    { name: "Juan Larios", position: "Defender" },
    { name: "Jan Bednarek", position: "Defender" },
    { name: "Armel Bella-Kotchap", position: "Defender" },
    { name: "Jayden Moore", position: "Defender" },
    { name: "Flynn Downes", position: "Midfielder" },
    { name: "Joe Aribo", position: "Midfielder" },
    { name: "William Smallbone", position: "Midfielder" },
    { name: "Adam Lallana", position: "Midfielder" },
    { name: "Mateus Fernandes", position: "Midfielder" },
    { name: "Kamaldeen Sulemana", position: "Midfielder" },
    { name: "Ryan Fraser", position: "Midfielder" },
    { name: "Lesley Ugochukwu", position: "Midfielder" },
    { name: "Samuel Amo-Ameyaw", position: "Midfielder" },
    { name: "Tyler Dibling", position: "Midfielder" },
    { name: "Romeo Akachukwu", position: "Midfielder" },
    { name: "Joseph O'Brien-Whitemarsh", position: "Midfielder" },
    { name: "Adam Armstrong", position: "Forward" },
    { name: "Ross Stewart", position: "Forward" },
    { name: "Ben Brereton Díaz", position: "Forward" },
    { name: "Cameron Archer", position: "Forward" },
    { name: "Maxwel Cornet", position: "Forward" },
    { name: "Paul Onuachu", position: "Forward" },
    { name: "Jay Robinson", position: "Forward" }
    ],
    "Tottenham" : [
        { name: "Guglielmo Vicario", position: "Goalkeeper" },
    { name: "Fraser Forster", position: "Goalkeeper" },
    { name: "Brandon Austin", position: "Goalkeeper" },
    { name: "Alfie Whiteman", position: "Goalkeeper" },
    { name: "Sergio Reguilón", position: "Defender" },
    { name: "Radu Drăgușin", position: "Defender" },
    { name: "Destiny Udogie", position: "Defender" },
    { name: "Cristian Romero", position: "Defender" },
    { name: "Pedro Porro", position: "Defender" },
    { name: "Djed Spence", position: "Defender" },
    { name: "Ben Davies", position: "Defender" },
    { name: "Micky van de Ven", position: "Defender" },
    { name: "Alfie Dorrington", position: "Defender" },
    { name: "Dante Cassanova", position: "Defender" },
    { name: "Yves Bissouma", position: "Midfielder" },
    { name: "James Maddison", position: "Midfielder" },
    { name: "Archie Gray", position: "Midfielder" },
    { name: "Lucas Bergvall", position: "Midfielder" },
    { name: "Dejan Kulusevski", position: "Midfielder" },
    { name: "Pape Matar Sarr", position: "Midfielder" },
    { name: "Rodrigo Bentancur", position: "Midfielder" },
    { name: "Callum Olusesi", position: "Midfielder" },
    { name: "Son Heung-Min", position: "Midfielder" },
    { name: "Richarlison", position: "Forward" },
    { name: "Timo Werner", position: "Forward" },
    { name: "Dominic Solanke", position: "Forward" },
    { name: "Brennan Johnson", position: "Forward" },
    { name: "Wilson Odobert", position: "Forward" },
    { name: "Will Lankshear", position: "Forward" },
    { name: "Mikey Moore", position: "Forward" },
    { name: "Damola Ajayi", position: "Forward" },
    { name: "Luca Williams-Barnett", position: "Forward" }
    ],
    "West Ham United" : [
        { name: "Łukasz Fabiański", position: "Goalkeeper" },
        { name: "Wes Foderingham", position: "Goalkeeper" },
        { name: "Alphonse Areola", position: "Goalkeeper" },
        { name: "Aaron Cresswell", position: "Defender" },
        { name: "Vladimír Coufal", position: "Defender" },
        { name: "Konstantinos Mavropanos", position: "Defender" },
        { name: "Jean-Clair Todibo", position: "Defender" },
        { name: "Max Kilman", position: "Defender" },
        { name: "Aaron Wan-Bissaka", position: "Defender" },
        { name: "Emerson", position: "Defender" },
        { name: "Kaelan Casey", position: "Defender" },
        { name: "Oliver Scarles", position: "Defender" },
        { name: "Carlos Soler", position: "Midfielder" },
        { name: "Lucas Paquetá", position: "Midfielder" },
        { name: "Mohammed Kudus", position: "Midfielder" },
        { name: "Edson Álvarez", position: "Midfielder" },
        { name: "Guido Rodríguez", position: "Midfielder" },
        { name: "Tomáš Souček", position: "Midfielder" },
        { name: "Andrew Irving", position: "Midfielder" },
        { name: "Crysencio Summerville", position: "Forward" },
        { name: "Michail Antonio", position: "Forward" },
        { name: "Niclas Füllkrug", position: "Forward" },
        { name: "Luis Guilherme", position: "Forward" },
        { name: "Danny Ings", position: "Forward" },
        { name: "Jarrod Bowen", position: "Forward" }
    ],
    "Wolverhampton Wanderers" : [
        { name: "José Sá", position: "Goalkeeper" },
    { name: "Daniel Bentley", position: "Goalkeeper" },
    { name: "Sam Johnstone", position: "Goalkeeper" },
    { name: "Tom King", position: "Goalkeeper" },
    { name: "Matt Doherty", position: "Defender" },
    { name: "Rayan Aït-Nouri", position: "Defender" },
    { name: "Santiago Bueno", position: "Defender" },
    { name: "Yerson Mosquera", position: "Defender" },
    { name: "Craig Dawson", position: "Defender" },
    { name: "Nélson Semedo", position: "Defender" },
    { name: "Toti Gomes", position: "Defender" },
    { name: "Bastien Meupiyou", position: "Defender" },
    { name: "Pedro Lima", position: "Defender" },
    { name: "Alfie Pond", position: "Defender" },
    { name: "Mario Lemina", position: "Midfielder" },
    { name: "Boubacar Traoré", position: "Midfielder" },
    { name: "André", position: "Midfielder" },
    { name: "João Gomes", position: "Midfielder" },
    { name: "Tommy Doyle", position: "Midfielder" },
    { name: "Pablo Sarabia", position: "Midfielder" },
    { name: "Jean-Ricner Bellegarde", position: "Midfielder" },
    { name: "Luke Cundle", position: "Midfielder" },
    { name: "Luke Rawlings", position: "Midfielder" },
    { name: "Jørgen Strand Larsen", position: "Forward" },
    { name: "Matheus Cunha", position: "Forward" },
    { name: "Hwang Hee-Chan", position: "Forward" },
    { name: "Sasa Kalajdzic", position: "Forward" },
    { name: "Rodrigo Gomes", position: "Forward" },
    { name: "Carlos Forbs", position: "Forward" },
    { name: "Gonçalo Guedes", position: "Forward" },
    { name: "Enso González", position: "Forward" }
    ]
}