const wnbaPlayerData = {
    "Atlanta Dream": [
        { name: "Laeticia Amihere", position: "Forward" },
        { name: "Maya Caldwell", position: "Guard" },
        { name: "Jordin Canada", position: "Guard" },
        { name: "Tina Charles", position: "Center" },
        { name: "Nia Coffey", position: "Forward" },
        { name: "Lorela Cubaj", position: "Forward" },
        { name: "Allisha Gray", position: "Guard" },
        { name: "Naz Hillmon", position: "Forward" },
        { name: "Rhyne Howard", position: "Guard" },
        { name: "Haley Jones", position: "Guard" },
        { name: "Ezinne Kalu", position: "Guard" },
        { name: "Cheyenne Parker-Tyus", position: "Forward" },
        { name: "Aerial Powers", position: "Guard" }
    ],
    "Chicago Sky": [
        { name: "Lindsay Allen", position: "Guard" },
        { name: "Rachel Banham", position: "Guard" },
        { name: "Kamilla Cardoso", position: "Center" },
        { name: "Chennedy Carter", position: "Guard" },
        { name: "Kaela Davis", position: "Forward" },
        { name: "Diamond DeShields", position: "Guard" },
        { name: "Dana Evans", position: "Guard" },
        { name: "Isabelle Harrison", position: "Forward" },
        { name: "Moriah Jefferson", position: "Guard" },
        { name: "Michaela Onyenwere", position: "Forward" },
        { name: "Angel Reese", position: "Forward" },
        { name: "Brianna Turner", position: "Forward" },
        { name: "Elizabeth Williams", position: "Center" }
    ],
    "Connecticut Sun": [
        { name: "Caitlin Bickle", position: "Forward" },
        { name: "DeWanna Bonner", position: "Forward" },
        { name: "Veronica Burton", position: "Guard" },
        { name: "DiJonai Carrington", position: "Guard" },
        { name: "Tyasha Harris", position: "Guard" },
        { name: "Brionna Jones", position: "Forward" },
        { name: "Marina Mabrey", position: "Guard" },
        { name: "Tiffany Mitchell", position: "Guard" },
        { name: "Astou Ndour-Fall", position: "Center" },
        { name: "Olivia Nelson-Ododa", position: "Center" },
        { name: "Alyssa Thomas", position: "Forward" }
    ],
    "Dallas Wings": [
        { name: "Kalani Brown", position: "Center" },
        { name: "Jaelyn Brown", position: "Guard" },
        { name: "Natasha Howard", position: "Forward" },
        { name: "Lou Lopez Senechal", position: "Guard" },
        { name: "Teaira McCowan", position: "Center" },
        { name: "Arike Ogunbowale", position: "Guard" },
        { name: "Satou Sabally", position: "Forward" },
        { name: "Jacy Sheldon", position: "Guard" },
        { name: "Maddy Siegrist", position: "Forward" },
        { name: "Stephanie Soares", position: "Center" },
        { name: "Sevgi Uzun", position: "Guard" }
    ],
    "Golden State Valkyries": [
        { name: "Natalie Nakase", position: "Coach"},
    ],
    "Indiana Fever": [
        { name: "Grace Berger", position: "Guard" },
        { name: "Aliyah Boston", position: "Forward" },
        { name: "Caitlin Clark", position: "Guard" },
        { name: "Damiris Dantas", position: "Forward" },
        { name: "Temi Fagbenle", position: "Center" },
        { name: "Lexie Hull", position: "Guard" },
        { name: "Kelsey Mitchell", position: "Guard" },
        { name: "Katie Lou Samuelson", position: "Forward" },
        { name: "Victaria Saxton", position: "Forward" },
        { name: "NaLyssa Smith", position: "Forward" },
        { name: "Kristy Wallace", position: "Guard" },
        { name: "Erica Wheeler", position: "Guard" }
    ],
    "Las Vegas Aces": [
        { name: "Kierstan Bell", position: "Guard" },
        { name: "Alysha Clark", position: "Forward" },
        { name: "Sydney Colson", position: "Guard" },
        { name: "Queen Egbo", position: "Center" },
        { name: "Chelsea Gray", position: "Guard" },
        { name: "Megan Gustafson", position: "Center" },
        { name: "Tiffany Hayes", position: "Guard" },
        { name: "Kate Martin", position: "Guard" },
        { name: "Kelsey Plum", position: "Guard" },
        { name: "Kiah Stokes", position: "Center" },
        { name: "A'ja Wilson", position: "Center" },
        { name: "Jackie Young", position: "Guard" }
    ],
    "Los Angeles Sparks": [
        { name: "Cameron Brink", position: "Forward" },
        { name: "Lexie Brown", position: "Guard" },
        { name: "Rae Burrell", position: "Guard" },
        { name: "Zia Cooke", position: "Guard" },
        { name: "Crystal Dangerfield", position: "Guard" },
        { name: "Dearica Hamby", position: "Forward" },
        { name: "Rickea Jackson", position: "Forward" },
        { name: "Aari McDonald", position: "Guard" },
        { name: "Kia Nurse", position: "Guard" },
        { name: "Odyssey Sims", position: "Guard" },
        { name: "Azura Stevens", position: "Forward" },
        { name: "Stephanie Talbot", position: "Forward" },
        { name: "Li Yueru", position: "Center" }
    ],
    "Minnesota Lynx": [
        { name: "Bridget Carleton", position: "Forward" },
        { name: "Napheesa Collier", position: "Forward" },
        { name: "Olivia Epoupa", position: "Guard" },
        { name: "Natisha Hiedeman", position: "Guard" },
        { name: "Myisha Hines-Allen", position: "Forward" },
        { name: "Dorka Juhasz", position: "Forward" },
        { name: "Kayla McBride", position: "Guard" },
        { name: "Diamond Miller", position: "Forward" },
        { name: "Alissa Pili", position: "Forward" },
        { name: "Alanna Smith", position: "Forward" },
        { name: "Courtney Williams", position: "Guard" },
        { name: "Cecilia Zandalasini", position: "Forward" }
    ],
    "New York Liberty": [
        { name: "Kennedy Burke", position: "Forward" },
        { name: "Marquesha Davis", position: "Guard" },
        { name: "Ivana Dojkic", position: "Guard" },
        { name: "Leonie Fiebich", position: "Forward" },
        { name: "Sabrina Ionescu", position: "Guard" },
        { name: "Jonquel Jones", position: "Forward" },
        { name: "Betnijah Laney-Hamilton", position: "Forward" },
        { name: "Nyara Sabally", position: "Forward" },
        { name: "Jaylyn Sherrod", position: "Guard" },
        { name: "Breanna Stewart", position: "Forward" },
        { name: "Kayla Thornton", position: "Forward" },
        { name: "Courtney Vandersloot", position: "Guard" }
    ],
    "Phoenix Mercury": [
        { name: "Rebecca Allen", position: "Guard" },
        { name: "Amy Atwell", position: "Forward" },
        { name: "Monique Billings", position: "Forward" },
        { name: "Natasha Cloud", position: "Guard" },
        { name: "Kahleah Copper", position: "Guard" },
        { name: "Sophie Cunningham", position: "Guard" },
        { name: "Brittney Griner", position: "Center" },
        { name: "Mikiah Herbert Harrigan", position: "Forward" },
        { name: "Natasha Mack", position: "Forward" },
        { name: "Charisma Osborne", position: "Guard" },
        { name: "Diana Taurasi", position: "Guard" },
        { name: "Celeste Taylor", position: "Forward" }
    ],
    "Seattle Storm": [
        { name: "Skylar Diggins-Smith", position: "Guard" },
        { name: "Joyner Holmes", position: "Forward" },
        { name: "Jordan Horston", position: "Guard" },
        { name: "Jewell Loyd", position: "Guard" },
        { name: "Ezi Magbegor", position: "Center" },
        { name: "Nika Muhl", position: "Guard" },
        { name: "Nneka Ogwumike", position: "Forward" },
        { name: "Mercedes Russell", position: "Center" },
        { name: "Victoria Vivians", position: "Guard" },
        { name: "Sami Whitcomb", position: "Guard" },
        { name: "Gabby Williams", position: "Forward" }
    ],
    "Washington Mystics": [
        { name: "Ariel Atkins", position: "Guard" },
        { name: "Shakira Austin", position: "Center" },
        { name: "Stefanie Dolson", position: "Center" },
        { name: "Aaliyah Edwards", position: "Forward" },
        { name: "Emily Engstler", position: "Forward" },
        { name: "Sika Kone", position: "Forward" },
        { name: "Jade Melbourne", position: "Guard" },
        { name: "Karlie Samuelson", position: "Guard" },
        { name: "Sug Sutton", position: "Guard" },
        { name: "Brittney Sykes", position: "Guard" },
        { name: "Julie Vanloo", position: "Guard" },
        { name: "Shatori Walker-Kimbrough", position: "Guard" }
    ]

}